### ISSUE TITLE
Can't find any online and idle self-hosted runner

### ISSUE THREAD

**Issue by duartealexf** [philips-labs/terraform-aws-github-runner#1004]
I'm not sure this is the place for such an issue, but lately this message has been showing really often:

![image](https://user-images.githubusercontent.com/5911016/126685017-1296bcf1-0ab5-4d5e-a467-0db6ac778661.png)

And it is starting to be a burning issue, mainly because I'm developing reusable NodeJS-based Github Actions, and to test them out I need to run them... if it takes 5 minutes to run it, then it really slows me down.

Please let me know if this issue is in the right place and what is the status, thank you.

**Comment by npalm** [comment]
By default the runners scale back to zero, so it will take some time to get the runner ready. The following parameters involves the scaling:
- time the message is waiting on the queue `delay_webhook_event`
- time that it takes to boot the runner, instance type will impact the time as well. You can prebuild AMI's to boot faster
- there are also setting to keep runners idle up and running.

**Comment by duartealexf** [comment]
> You can prebuild AMI's to boot faster
>
> There are also setting to keep runners idle up and running.


How do I do these? Thank you

**Comment by duartealexf** [comment]
As discussed via Teams with @npalm I will open this issue in https://github.com/philips-internal/github-runner-research-aws-pgn in case it happens again.
