### ISSUE TITLE
Deregister runner on shutdown

### ISSUE THREAD

**Issue by mrmeyers99** [philips-labs/terraform-aws-github-runner#1006]
We're having an issue where sometimes we need to manually kill a runner if it gets into a bad state, however if I terminate the runner, it doesn't de-register itself from github first, so github continues to report it as offline.  Can we add a shutdown hook that deregisters the runner?

**Comment by npalm** [comment]
Thanks for reporting. Yes would be great if we can find a good way to remove those orphan runners in github. But the module does not keep track of created runners (no state). The name of the runner in github is the same as the id of instance, so once the instance in gone we don't know the name of runner anymore. 

Maybe an idea to hook to the AWS terminate event

**Comment by npalm** [comment]
Also related to #804

**Comment by jpalomaki** [comment]
@npalm Is the runner GitHub token stored somewhere in the file system? I was just wondering if we could bake in (e.g. in custom AMI) a systemctl shutdown job or some such, to run on the instance when the instance is shutting down, to run `$ ./config.sh remove --token XXX`
