### ISSUE TITLE
Add runner name prefix

### ISSUE THREAD

**Issue by mrmeyers99** [philips-labs/terraform-aws-github-runner#1114]
It would be great if we had the ability to put a runner name prefix, so the runner name could be something like "<appname>-<instanceId>".  It would make it easier to know what you're looking at when you're looking in the github ui, especially when you have two types of runners in the same runner group.

**Comment by npalm** [comment]
Note: max length for a runner name is 64 chars

**Comment by russmac** [comment]
@mrmeyers99 Use the environment parameter for this. Just put your prefix there. I use dev-foo-bar as mine.

**Comment by mrmeyers99** [comment]
@russmac The EC2 instance names are using the environment prefix, but the runner names is GitHub are just the instance IDs, unless I'm missing something.

**Comment by russmac** [comment]
@mrmeyers99  I understand now you want the tag "Name" value displayed as well as the instanceid.

I just align/classify my runner labels to the name as the runner "Name" tag and GH app so my label for dev-foo-bar runners is just that , so then you see that runner name displayed in the UI at the start of the workflow as a label and know through convention. Tag name would be useful if they didn't align for some reason. Or all tags.

**Comment by gertjanmaas** [comment]
> @russmac The EC2 instance names are using the environment prefix, but the runner names is GitHub are just the instance IDs, unless I'm missing something.

Indeed and at this moment that is our only link between the registration in GitHub and the actual EC2 instance. We could add a prefix to that, but it also requires changing the current runner lookup logic.

@mrmeyers99 Just for clarification, how do you have two different runners in one group? Either via the `instance_types` variable, or set up this module multiple times with different configurations? Just to know if one global prefix for the module would be sufficient or we need to adapt the `instance_types` variable

**Comment by mrmeyers99** [comment]
I have multiple instances of the module, although it would be nice to be able to have multiple configurations, but that would be another ticket 😃
