### ISSUE TITLE
Scale up Lambda doesn't trigger new runner instance

### ISSUE THREAD

**Issue by Srikanth1992** [philips-labs/terraform-aws-github-runner#1165]
Hello @npalm @gertjanmaas ,

I have Idle config configured in our environment as below:

   idle_config = [{
     cron      = "* * 9-17 * * *"
     timeZone  = "America/New_York"
     idleCount = 2
   }]

So I was in assumption that when we set the idle config to 9am to 5pm, I was thinking, scale up lambda will launch ec2 instance at 9am daily 

But it's not happening. I waited till 10am, then later on I triggered some actions in few repo then ec2 instance got launched and based on idlecount value they were running.

Please let if it's expected behaviour

ISSUE 2:

Since I've Idle Count value as 2 I should have two ec2 instance running all the time right. So when I terminated1 instance from 2 running instance,  scale up lambda didn't trigger a new ec2 instance based on idle count value which is set.

Please let me know if this is expected behaviour

Thanks,
Srikanth

**Comment by mcaulifn** [comment]
Please see https://github.com/philips-labs/terraform-aws-github-runner#idle-runners for the details on idle runners. Runners are only launched on-demand.

**Comment by npalm** [comment]
Indeed, the system will only scale once it receives an event. The idle config only avoids that runners will be terminated. By default the system wil scale back to zero. Once the idle config is configured some runners can be kept idle. So also for you second issues, runners are only re-created when new events come in. Please feel free to improve explanation in the readme.
