### ISSUE TITLE
How to run spot and on demand runners(hybrid) in AWS 

### ISSUE THREAD

**Issue by halil9** [philips-labs/terraform-aws-github-runner#1179]
We want to run our self-hosted runners as spot and on-demand in AWS. 

- Is there any way to do achieve this in current modules?
- if not Do you have any improvement in your roadmap?

Thanks in advance

**Comment by halil9** [comment]
In our case,

Our one self-hosted runner runs on-demand. Because it is required for our critical jobs. Other runners should be running as spot instances.

**Comment by halil9** [comment]
Hi, guys is there any way to do this?

**Comment by npalm** [comment]
Closing the issue due to in activity. Please feel free to re-open.
