### ISSUE TITLE
Module is not compatible with the GovCloud region

### ISSUE THREAD

**Issue by aidan-mundy** [philips-labs/terraform-aws-github-runner#1245]
I will add more problems here as I find them, initial problem in my GovCloud journey is that the GovCloud region ARNs start with "arn:aws-us-gov:" and the module hardcodes ARNs as "arn:aws:". (A similar problem will cause this module to fail in the China regions)
https://github.com/philips-labs/terraform-aws-github-runner/blob/1e6c8b02f498be71238975eebe0aee18a3668084/modules/runners/policies-runner.tf#L29

**Comment by npalm** [comment]
I assume we have hard coded this even on more places. Feel free to sugges an absraction in a PR. Thanks for taking the time to create an issue.

**Comment by aidan-mundy** [comment]
@npalm Surprisingly, changing that single line was enough to make the module work in my GovCloud environment with GHES. I am using the root module, default KMS, and most of the standard options. 

I will be doing more testing with some of the more niche options to find other GovCloud incompatibilities. Once I'm satisfied with my hard-coded changes, I'll write up an abstraction for it (hopefully automated, but potentially with an input variable) and put up a PR.

**Comment by npalm** [comment]
@aidan-mundy is you issue resolved?

**Comment by aidan-mundy** [comment]
I havent found any additional issues in the module (related to GovCloud anyway). Haven't had the chance to throw up an MR for this, but I can do that in the next week or two.

**Comment by aidan-mundy** [comment]
@npalm I havent found any additional issues in the module (related to GovCloud anyway). Haven't had the chance to throw up an MR for this, but I can do that in the next week or two.

**Comment by jokreliable** [comment]
I believe that with the merge mentioned above, this issue can be resolved.

**Comment by aidan-mundy** [comment]
Agreed, this appears to resolve the issue I had detected, as well as other potentially related issues. It appears this fell off my radar at some point, thanks for picking up the slack @jokreliable

**Comment by jokreliable** [comment]
No worries - Took me a month to get back on my radar too..  😄 -- Glad it helped!
