### ISSUE TITLE
Provide a webhook broker setup

### ISSUE THREAD

**Issue by toast-gear** [philips-labs/terraform-aws-github-runner#1282]
**Feature Request**
If you are running many runner groups in your GitHub Organisation you have to deploy an instance of the module for each runner group. In addition you need to configure a webhook per stack. This leads to lots of duplication and I can see how eventually it becomes a bit of a management nightmare.

In an ideal world you would have:
Single DNS entry -> API Gateway webhook broker service -> Lambda webhook broker service -> job added to the relevant stacks SQS queue -> relevant stacks lambdas scale up / down

It would be cool if you could make the webhook lambda optional for each stack and instead have have a module for deploying a webhook broker service which can add jobs into the right SQS queue for this module.

This feature request probably goes beyond the scope of the project though so feel free to close with comments if it does.

Even the ability to not deploy the webhook API Gateway and an example somehow integrating the webhook lambda with a well supported AWS webhook broker service in [examples](https://github.com/philips-labs/terraform-aws-github-runner/tree/develop/examples) would be cool

**Comment by Makeshift** [comment]
Since GHA doesn't provide the labels with the `check_run` webhook, this is kind of a pain, but I think this pseudocode will work to get the runs-on label requirements for the node that is currently being executed:

```javascript
const checkRunWebhook = "<the check_run webhook output>"
const thisRun = get(`${checkRunWebhook.repository.url}/actions/runs`).workflow_runs.filter(workflow => workflow.check_suite_id === checkRunWebhook.check_suite.id && workflow.head_sha === checkRunWebhook.check_run.head_sha)[0];
const workflowFileName = `${thisRun.name}.yml`
const actionFileURL = `${checkRunWebhook.repository.url}/contents/.github/workflows/${workflowFileName}?ref=${thisRun.head_sha}`
const thisStepName = checkRunWebhook.check_run.name

const actionFile = yaml.load(get(actionFileURL))
const thisStepRunsOn = actionFile.jobs[thisStepName]["runs-on"]
```

If the above works, a broker service becomes a lot more doable.

**Comment by Makeshift** [comment]
@npalm I'm curious if you think this is too large of a scope for this module?

**Comment by npalm** [comment]
I already thinking some time about supporting some scenario like this. Extending the module to support multiple deployment for groups and tags is certainly fine. But I had simply not the time to work on an implementation yet.

I see roughly 2 approaches. One as mention let the webhook function as a broker and put a message on the relevant SQS queue to let the matching scale up runner take up the message from the queue and crate a runner. Drawback it complicates the deployment. 

Option 2 is to add the relevant stack info the queue message and let the scale up runner to create the right runner. This wil increase the complexity of the lambda. Which I don't prefer. 

So any good suggestion and help is very welcome

**Comment by npalm** [comment]
> Since GHA doesn't provide the labels with the `check_run` webhook, this is kind of a pain, but I think this (incredibly ugly) pseudocode will work to get the runs-on label requirements for the node that is currently being executed:
> 
> ```js
> const checkRunWebhook = "<the check_run webhook output>"
> const thisRun = get(`${checkRunWebhook.repository.url}/actions/runs`).workflow_runs.filter(workflow => workflow.check_suite_id === checkRunWebhook.check_suite.id && workflow.head_sha === checkRunWebhook.check_run.head_sha)[0];
> const workflowFileName = `${thisRun.name}.yml`
> const actionFileURL = `${checkRunWebhook.repository.url}/contents/.github/workflows/${workflowFileName}?ref=${thisRun.head_sha}`
> const thisStepName = checkRunWebhook.check_run.name
> 
> const actionFile = yaml.load(get(actionFileURL))
> const thisStepRunsOn = actionFile.jobs[thisStepName]["runs-on"]
> ```
> 
> If the above works, a broker service becomes a lot more doable, although there would need to be a lot more checks and probably some extra permissions involved!

This could indeed work, and it would require extra permissions to read files in the repo. But I think we should move slowly away from support the `check_run` event as soon it becomes available in GHES. Are you running on GHES?

**Comment by Makeshift** [comment]
> Are you running on GHES?

I'm not, no. I'm guessing you're thinking about switching to the `workflow_job` webhook? A quick glance at [the docs](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-example-50) implies that my pseudocode would be much the same as it doesn't seem to supply much more information than `check_run`.

**Comment by toast-gear** [comment]
There is a major issue with this, queued workflow_jobs don't contain runner group information.

```json
{
  "action": "queued",
  "workflow_job": {
...
    "status": "queued",
    "conclusion": null,
    "started_at": "2021-11-05T13:14:32Z",
    "completed_at": null,
    "name": "build-matrix",
    "steps": [

    ],
...
    "labels": [
      "ubuntu-latest"
    ],
    "runner_id": null,
    "runner_name": null,
    "runner_group_id": null,
    "runner_group_name": null
  },
...
```
