### ISSUE TITLE
Distribution Lambda occasionally fails after creation

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#13]
## Summary

Distribution syncer lambda sometimes not working after a terraform apply, cause unclear. Removing the lambda and run an apply again solves the issue.

## Steps to reproduce
Not reproduceable, happens occasionally.

**Comment by jpalomaki** [comment]
@npalm Are you still seeing this? Just wondering if it might be an issue with this [trigger](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runner-binaries-syncer/runner-binaries-syncer.tf#L93-L125), e.g. eventual consistency (IAM, event dispatch or s3).

Would it make sense to try and run the first sync using this [data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_invocation) instead?

**Comment by npalm** [comment]
Seems not to be an issue anymore, due to inactivity I close the issue. Feel free to re-open. Thanks for reporting!
