### ISSUE TITLE
Provide a minimal permissions deployment role and output its ARN

### ISSUE THREAD

**Issue by toast-gear** [philips-labs/terraform-aws-github-runner#1309]
Given this is an opinionated solution it would be nice if it would also create a minimal permissions policy for deploying this solution and output its ARN. It would make pipeling this solution easier for the end user who wants to implement a least privilege pipeline. The creation of this role should be toggleable with a variable for those that are deploying multiple stacks. For example you might have a repository like the below where this module resides `$GITHUB_WORKSPACE/modules/actions-runner/`. 

```
$GITHUB_WORKSPACE/modules/actions-runner/ <--- philips-labs module
$GITHUB_WORKSPACE/runner-groups/Default <--- runner group specific module wrapper to philips-labs module
$GITHUB_WORKSPACE/runner-groups/foo <--- runner group specific module wrapper to philips-labs module
$GITHUB_WORKSPACE/runner-groups/bar <--- runner group specific module wrapper to philips-labs module
$GITHUB_WORKSPACE/runner-groups/baz <--- runner group specific module wrapper to philips-labs module
```

You are then deploying an instance of this module on a per runner group basis. Those runner groups source the philips-labs module held in `modules` structure and variablise it for that specific runner group.

What would be great is is you could have the standard deployment policy created by this module. In the above example the `Default` runner group would have this policy creation enabled and maybe its ARN outputted, the definition would be managed here. Whatever role your pipeline's deployment role is would have this policy attached which is defined and managed in the `Default` runner group. Then all other runner groups would have the creation of this policy disabled so you don't have up with N number of instances of the same policy.

The alternative is one is just documented outside of the module, either in the README.md or as a seperate terraform IAM resource. Either way it would be nice for this solution to come with a minimal permissions deployment role.

**Comment by npalm** [comment]
Sorry missed your question. You should use something like an assume role / or user to use the role created with the permission boundary

**Comment by nnWhisperer** [comment]
So, as far as I understood, one must use like an admin user, to run this terraform module to create an iam role in aws, then either manually or using aws's cli, to create a new user with that role. Afterwards, that user may be used for any other part of this repository, without requiring the admin user. Is that correct? Thank you
