### ISSUE TITLE
Donation: Runner AMI template + slimmed-down `user_data` to match

### ISSUE THREAD

**Issue by skyzyx** [philips-labs/terraform-aws-github-runner#1313]
terraform-aws-github-runner v0.21.0 \
Terraform 1.0.9

I built out a custom AMI for GHA Runners, based on Amazon Linux 2. Had to pre-compile some packages that aren't in Amazon’s `yum` repos, but I got there. Cool, I've got a runner AMI.

After digging into the code, trying to figure out the nitty-gritty for how this project works, I found that the default `user_data` file attempts to do a lot of extra (for me, unnecessary) work at boot. I was able to slim it down to only the things it needed, and pass the filename to the proper Terraform parameter.

I'm wondering if the developers feel there's value in providing a standard Packer template for producing an AL2 AMI ready to use as a GHA Runner. The idea being, if a user wants to use this template to generate their own Base AMI, then this project could _also_ ship a slimmed-down `user_data` file that focuses exclusively on connecting itself to the Actions system.

I have both written right now. I'd need a little time to clean things up before having a complete, e2e, Terraform-y implementation done to open a ready-to-PR, but I wanted to know if this is something that would be welcome. I used the word "donation" in the title because I could always donate the code to you, then _you_ could decide how to use/expose it to your end-users. Either way, I'm cool.

**Comment by ScottGuymer** [comment]
@skyzyx I have started to add exactly this functionality in #1444 with a sample AMI that provides the same OOTB functionality as the current user_data

**Comment by npalm** [comment]
We have added hooks so you can build a custom AMI, also an example for building an AMI with packer is added.
