### ISSUE TITLE
[Tutorial] How to configure some runners as `x64` and others as `arm64`?

### ISSUE THREAD

**Issue by skyzyx** [philips-labs/terraform-aws-github-runner#1316]
Similar but different from #991:

We have lots and lots of `x86_64` AMIs and software, as I expect most people do. I also know that this module generates a Launch Template for spawning new instances.

I'd be interested in a tutorial (whenever, if ever this support exists) that explains how to set up scalable `arm64` instances (assuming I/we have an `arm64` AMI) so that certain jobs can specify the `arm64` label and get one of those runners.

I would hate to ask you to duplicate the Launch Template for `x86_64` vs. `arm64` builds, but perhaps some kind of code-generation could simplify the process of maintaining consistency with small tweaks for each type?

**Comment by Makeshift** [comment]
Similar to #1282, #508 and #73 also.

**Comment by ScottGuymer** [comment]
There is now some documentation and support for different runner architectures here https://github.com/philips-labs/terraform-aws-github-runner#arm64-support-via-gravitongraviton2-instance-types
