### ISSUE TITLE
dist bucket has no SSE configuration

### ISSUE THREAD

**Issue by marekaf** [philips-labs/terraform-aws-github-runner#1320]
Hi, would it be possible to add optional SSE configuration to all the s3 bucket resources?

https://github.com/philips-labs/terraform-aws-github-runner/blob/65aab803262e0616a8895d2fdbc0bc112e2572f9/modules/runner-binaries-syncer/main.tf#L5

I'l be happy to implement it.

**Comment by gautamkrishnar** [comment]
@npalm this can be closed right
