### ISSUE TITLE
Don't error if the webhook event only has GitHub owned labels

### ISSUE THREAD

**Issue by toast-gear** [philips-labs/terraform-aws-github-runner#1348]
I have webhooks setup at the organisation level in my organisation as I don't want to install them at the repo level as that would result in having to manage hundreds of webhooks. When a `workflow_job` event is sent to my API Gateway the webhook is marked as failed as it receives a HTTP 403 response. The errors in my logs are these 2 over and over again:

```
2021-10-27T14:46:31.491Z	4ff42805-6636-4c5e-89c3-11b0c1225917	
DEBUG	Received workflow job event with labels: '["ubuntu-latest"]'. 
The event does NOT match the configured labels: 'default,self-hosted'

2021-10-27T14:46:31.491Z	4ff42805-6636-4c5e-89c3-11b0c1225917	
ERROR	Received event contains runner labels 'ubuntu-latest' that are not accepted.
```

This is confusing as it makes it look like there is a problem with the configuration of the webhook when really the webhook is fine. I know we added support for ignoring known GitHub self-hosted labels in this PR https://github.com/philips-labs/terraform-aws-github-runner/pull/1244. Given many (probably the majority) of organisations running self-hosted runners will also utilise GitHub's runners too it would be great is we could also make it so when the webhook lambda receives a `workflow_job` event that only contains `runs-on` labels for GitHub owned labels such as `ubuntu-latest`, we ignore them, log the ignore at the debug level (as we do now) and return a HTTP 200 response instead. 

Fixing this so the webhook still receives a HTTP 200 response marking it as green in the GitHub UI regardless of if the job is bound for a philips-labs runner or not would enable an administrator to more easily see real configuration errors such as a mismatched webhook secret.

EDIT the current GitHub managed labels can be found here https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources, workflow jobs that are marked only for any of these should not result in a non HTTP 200 response (or any other label combination imo)

EDIT As a more concrete example, here are what some of my webhooks look like atm on the organisation webhook screen:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/15716903/139224450-4cc7b119-b43d-4c23-86d9-c2efa70056f4.png">

And here are some `Recent Deliveries` in the one of the webhook settings.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/15716903/139224810-8c745596-1cf1-4449-927c-153e67da4091.png">

They are all working fine but it looks like I have a major configuration issue. This leads to lots of confusion unless the adminstrator investigating the webhook errors is:

A) familiar with the GitHub Actions platform
B) familiar with the implementation details of this module

**Comment by npalm** [comment]
@toast-gear put it on my list to check.

**Comment by npalm** [comment]
First of returning a 403 is certainly not correct. It should be either an error in the 500 range or an OK in the range of 200s. 

The check is added for a couple of reason
- To avoid scaling kicks in for jobs that should not be processed by the runner.
- Since once I introduced the event and enabled by default, I though logically to return an error in case the event is ingorred.
- To prepare to be able to support different type of runners (configuration)

I think the best way forward is to:
1. Return 200 (instaed of 403), or even better a 202 as also the GitHub docs suggest.  And maybe add some extra info to the body in case the labels are not matching.
2. Change the default indeed to disabled

**Comment by toast-gear** [comment]
> To avoid scaling kicks in for jobs that should not be processed by the runner.

We certainly don't want to break this! Just prevent a non 2XX response code being returned to GitHub if the labels don't match.

**Comment by toast-gear** [comment]
Perhaps I've missunderstood what `disable_check_wokflow_job_labels` does. I've deploy my stacks with this enabled and I scale for any job now.

Perhaps I should describe what I think is ideal.

Labels are checked when the webhook is recieved to see if the job is bound for that stacks runners i.e. the label. If it finds a matching label then the job is queued onto the SQS queue. If the labels do not matched then the job is ignored, not added onto the SQS queue, dropped and a HTTP 2XX response code is returned.

This just seems like the behaviour everyone would want to me?
