### ISSUE TITLE
Ephemeral runners

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#1372]
## Description

The current runners are short lived but not ephemeral. A runner can process multiple jobs till it got killed by the `scale-down` lambda. Ephemeral runners guarantee a clean environment for every job to improve security. Avoiding any shared state, or left overs between jobs.

## How

GitHub have introduced the `workflow_job` to support scaling ephemeral runners. The runner agent is extended with the option `--ephemeral` which will terminate the agent after a run and de-register it.

- Enable via option `ephemeral` to runners #1375 
- Boot instances faster, e.g. via pre-build ami
- Have an optional pool available of runner
- Handle events that cannot processed due to limits or exceptions

## Implementation

For tracking implementation a GitHub [project](https://github.com/philips-labs/terraform-aws-github-runner/projects/1) is crated to track progress. All work will be first merged to the branch `feature/ephemeral`. Active development (also via PR) on ephemeral runnes can done via PR's to this branch.

**Comment by skyzyx** [comment]
‡ …for GitHub.com.

For GHES, `workflow_job` does not exist in v3.2, and neither does `--ephemeral`. The latter is supposed to be coming in v3.3. There has been no public announcement of `workflow_job` coming to GHES one way or the other.

See also https://github.com/philips-labs/terraform-aws-github-runner/issues/182.

**Comment by npalm** [comment]
@skyzyx thanks for the notice, we will keep the module backwards comptabile. But I planning only to support hte ephemeral runners together with the `workflow_job` event

**Comment by aidan-mundy** [comment]
@skyzyx @npalm Enterprise Server 3.3.0.rc1 dropped yesterday with support for ephemeral runners and `workflow_job`.

**Comment by ScottGuymer** [comment]
Implementing this is in progress. Closing this in favour of #1372. Will track the implementation of this there.

**Comment by aidan-mundy** [comment]
@ScottGuymer 🤔 this _is_ #1372

**Comment by ScottGuymer** [comment]
oops

**Comment by ScottGuymer** [comment]
This is now implemented and released
