### ISSUE TITLE
metadata_options → http_tokens = "required" is NOT a safe assumption.

### ISSUE THREAD

**Issue by skyzyx** [philips-labs/terraform-aws-github-runner#1373]
This is not a safe assumption to make:

https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/main.tf#L62

For example, we have Base AMIs where certain actions are performed early (as part of `/etc/rc.local`) which make calls to the IDMS service. Force-requiring a token means that the nodes boot up incorrectly, and never get around to processing the `user_data` where we connect to Actions.

This should either be configurable, or you need to **explicitly** point out how this may affect people using the on-board IDMS service, so that they can pre-bake their AMIs with this in-mind. Users need to perform a step to explicitly fetch a token, then include that token in all additional curl calls to `169.254.169.254`.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

**Comment by npalm** [comment]
Thanks for creating the issue, any suggestion how to solve this in a better way?

**Comment by Makeshift** [comment]
A warning to those who update, realise that http_tokens are now required, then try to rollback: Terraform will NOT delete metadata option from your launch configurations. You will need to manually edit all of your launch configurations to remove this setting, or delete them and have terraform remake them.

**Comment by npalm** [comment]
What would be the best way forward? Removing the option for the moment and do the implementation in a new PR?

**Comment by Makeshift** [comment]
That would be my suggestion. It would be fairly simple to make the option configurable and have it false by default?

**Comment by npalm** [comment]
Drawback of setting the option to false is that the default provided user_data script is not working anymore, am I correct?

**Comment by Makeshift** [comment]
I don't _think_ so, I believe it should still work, as the [recommended path for upgrading](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) implies that IMDSv2 is still usable even if it isn't explicitly required by metadata options.

Unless there's a `ec2:RoleDelivery` condition key I missed somewhere, I think that's the only thing that would need changing, although I haven't looked too deep into it yet as I've been fixing my actions setup this morning 😅

**Comment by npalm** [comment]
I will create a PR to make the feature configurable, and set the default to optional

**Comment by npalm** [comment]
@Makeshift @skyzyx I have created a fix, feel free to make comments on the PR (#1377)
