### ISSUE TITLE
[ephemeral] Add option ephemeral runners

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#1375]
As part of #1372 we first the option to enable ephemeral runners. 

The option will be only `enable_ephemeral_runners` will be by default set to false. Once switch to true in combination with the `workflow_job` event runners will be created with `--ephemeral` once the job is finished the instance will be terminated.

**Comment by keenan-v1** [comment]
So glad to see this is coming. I'm researching self-hosted runners, so I'm curious what the ETA might be for this feature?

**Comment by npalm** [comment]
No ETA yet on best effort, but the goal is to implement the different parts separatly. First making ephemeral possible as a kind of beta feature. Next also find a way ot have a pool to start builds faster, and a base ami. Any help is welcome

**Comment by ScottGuymer** [comment]
Working on adding a pre-built AMI in #1444
