### ISSUE TITLE
index.scaleUpHandler is undefined or not exported

### ISSUE THREAD

**Issue by GregoryVds** [philips-labs/terraform-aws-github-runner#1402]
Hi,

First thanks for this nice project :-)
I started having issues recently (on latest version 0.24.0) where the ci-scale-up would fail.

I get the following logs in CloudWatch;

 ```
2021-11-12T10:03:04.252Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "index.scaleUpHandler is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: index.scaleUpHandler is undefined or not exported",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

I downgraded from 0.24.0 to 0.22.0 and it seems to have solved the issue.

I found out about [PR#1228](https://github.com/philips-labs/terraform-aws-github-runner/pull/1228/commits/42f40ea51fbe3933800f02af5f1bf71671540ca5) that was merged in 0.22.0 and that renames this handler [here](https://github.com/philips-labs/terraform-aws-github-runner/blame/develop/modules/runners/scale-up.tf#L9).

Could it be related? I didn't get time to investigate more in details... 

Thanks for the help

**Comment by mcaulifn** [comment]
@GregoryVds Did you re-compile the lambdas or re-download/deploy the zips?

**Comment by GregoryVds** [comment]
@mcaulifn Thanks for the answer!

I am not sure what happened, it is actually my CI that run and must have automatically updated the terraform-aws-github-runner setup (it was using  `version = "~> 0.18 "`). It might not have updated the zips... I am still not sure about what happened.

Anyways, I reinstalled by hand 0.24 by hand and it works now.
