### ISSUE TITLE
Github runner not getting created

### ISSUE THREAD

**Issue by ashishamway** [philips-labs/terraform-aws-github-runner#1504]
I am getting below error in **gh-ci-webhook** Lambda. I have followed steps given in documentation and it is not clear to me why runner is not getting created. In debugging, I found that this lambda run on request but fail due to below error. Any idea how I can solve this issue?

 `2021-12-08 10:51:57.320  ERROR [:a0d139ee-f3f4-4b90-a6d5-8c2e56e40447 index.js:85868  verifySignature] Unable to verify signature! {} 
`

**Comment by ashishamway** [comment]
It turn out that random string contain certain character which are not same as present in SSM added by code.

**Comment by dvdgitman** [comment]
> It turn out that random string contain certain character which are not same as present in SSM added by code.

Hey I׳m facing the issue, I will happy if you can help

**Comment by skjensen** [comment]
I ran into the same issue and wasn't sure what the error meant. I ran `terraform apply` again, and then 

`terraform output -raw webhook_secret`

Coped the new secret over into the github app and it worked. Not sure why it didn't work the first time around.
