### ISSUE TITLE
Question about resuable workflows

### ISSUE THREAD

**Issue by teodor-daskalov** [philips-labs/terraform-aws-github-runner#1530]
Hi @npalm,

About 3 months ago we implemented your solution (v0.18.1) and we're really happy with it, because it provides us with a way to have dynamic EC2 instances as self-hosted runners and free up resources for other things from our own on-prem machines.

A colleague of ours is trying to implement the new feature of reusing workflows that was released last month:
https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

So far no success. The workflows that call a reusable workflow cannot trigger the spawning of new AWS runners.

Have you tried this on your end and could it work in theory with the version that we have on our end?

Thanks in advance for your support!

**Comment by npalm** [comment]
Yes, we have the reusable workflows / templates working. Did you grant org level access to the repo containing the shared workflow?

**Comment by teodor-daskalov** [comment]
@npalm thanks for your response. I think I found out the reason behind this, after I re-checked the webhook lambda's logs:

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/86970293/146936161-3d77eae7-0406-4802-b969-ed04a1f9c586.png">

So what I fail to understand is why doesn't the lambda recognize the 3 default labels for any linux OS runner: 
`self-hosted`, `linux`, `x86` ?

In our Terraform config we have defined 3 custom labels: `aws-runner`, `ubuntu-18.04`, and `test`.
But the lambda rejects a request that has labels `self-hosted` + `linux` because the label `linux` doesn't seem to be taken into consideration.

Am I missing something or is this the expected behavior?

Of course, at this time it is an easy thing to fix, we just always have to target the exact set of labels defined or a specific part of them, without introducing an "unknown" to the lambda label.

**Comment by npalm** [comment]
The webhook is checking if the labels in the event are matching the configured labels. So in your case the labels aws-runner, ubuntu-18.04, and test should be used in the workflow triggering the build. The predefined github labels are ignored in the check. You can also set `disable_check_wokflow_job_labels` which should disable the label check and accept any workflow job event to the webhook. 

The labels check is relative new, and was introduced together with the workflow job even.

**Comment by teodor-daskalov** [comment]
Thanks a lot for the info! Btw, do you think all the configured labels have to be used in the workflow or one or two is enough?

**Comment by npalm** [comment]
Actually, I doubt a bit about what to do with the labels. I even think to disable the check by default. So would suggest to siable them for now.

**Comment by teodor-daskalov** [comment]
Alright, thanks very much for your help. I'll close this one.
