### ISSUE TITLE
Syncer lambda is not downloading GitHub runner release into S3 bucket

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#1541]
## Problem
The latest [release](https://github.com/actions/runner/releases/tag/v2.286.0) of GitHub runners contains a lot more artifacts.  The syncer Lambda is downloading the GitHub runner release based on a prefix with architecture and os. Per arch and os this leads now to mutliple matches wich cause the error "Cannot find GitHub release asset". 

## Work around
Download the latest GitHub release for the runner to the S3 bucket created by the module (Terraform). You can find the name of the bucket and object as part of the config of the Lambda. For example, via the AWS console or `terraform resources`. Look for `S3_BUCKET_NAME` and `S3_OBJECT_KEY`.  The Lambda in the bucket also uses tags for the object, but the tags are not used by the install script which fetch the distribution from the bcket.

## Fix
Release 0.27.2+ see also PR #1542

**Comment by npalm** [comment]
Kept the issue for some time open, to indicate the problem clearly. A patch is available since version `0.27.2`.

**Comment by dhaven** [comment]
Hello there,

I've stumbled on this issue while working with windows instances and version 0.32.0 of this module. Can you confirm that the lambda syncer is expected to work when downloading the windows binary?

I've done some investigation and found the following :

the release filename to be downloaded should look like : actions-runner-win-x64-2.287.1.zip

looking at the lambda function code [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/syncer.ts#L67) the runner_os variable is used in the filename. For windows this variable used to be "win" but has recently been changed to "windows" (as of #1591 ). I might be wrong but this seems to be the source of the error.

Thanks,

**Comment by ScottGuymer** [comment]
@dhaven I think you are exactly right with this. We changed it to windows as it then matched up with the automatically added GitHub os label.

Is this still not working correctly in the latest version?

**Comment by krlydm** [comment]
I can confirm that I have the same issue with the latest v0.34.0.

**Comment by ScottGuymer** [comment]
Hopefully #1716 will address this.
