### ISSUE TITLE
Issue trying to use ubuntu based runners with 0.27.2

### ISSUE THREAD

**Issue by nparfait** [philips-labs/terraform-aws-github-runner#1560]
I was previously using version 0.18.1 of this module. I decided to upgrade to the latest 0.27.2. However came across an issue.

I'm trying to use ubuntu runner ( i have copied user-data.sh from examples/ubuntu/templates/ )
Using the defaults the runner was registering with GIthub.

I then tried using the flag
runner_as_root = true

this then registered the runner but caused me some permissions issues between actions/checkout and my steps running in a container.

Finally i tried updating SSM parameter xxx/runner/run-as
to: runners

and this was able to run successfully.

Looking here 
https://github.com/philips-labs/terraform-aws-github-runner/blob/v0.27.2/modules/runners/runner-config.tf#L4

the run as is either root or ec2-user. 
The ubuntu image doesn't have an ec2-user so not sure if this is a problem or not.

Can you please advise?

**Comment by npalm** [comment]
Thanks for creating the issue, the ubuntu example is indeed broken. I have just created a fix in PR #1572
