### ISSUE TITLE
The request include parameter that is not valid for this queue type.

### ISSUE THREAD

**Issue by maathor** [philips-labs/terraform-aws-github-runner#1562]
Hi,
I'm trying to implement this current stack. Into the application log (into github > app > advance I retrieve my attempts)
They are all failing with : 
`{"message":"Internal Server Error"}`

From cloudwatch, the webhook lambda I get:

```
    "message": "Value 4643128775 for parameter MessageGroupId is invalid. Reason: The request include parameter that is not valid for this queue type.",
    "code": "InvalidParameterValue",
    "name": "InvalidParameterValue"
```

I used the ubuntu example with the lastest lambdas version (v0.27.2).
From the app configuration side I set:

```
- Repository:
   Actions: Read-only (check for queued jobs)
   Checks: Read-only (receive events for new builds)
   Metadata: Read-only (default/required)
   Administration: Read & write (to register runner)

- Organization
     Self-hosted runners: Read & write (to register runner)

- In the "Permissions & Events" section and then "Subscribe to Events"
subsection, check "Workflow job"
```

I didn't any message into my SQS queue due to this failing webhook lambda.

**Comment by npalm** [comment]
Looks like the the webhook lambda is including `MessageGroupId` in the SQS message. This value is only valid vor an FIFO queue. Can you check what type of queue is created?

**Comment by maathor** [comment]
a standard one, yes, you're right ! seems legit !

**Comment by npalm** [comment]
The variable `sqs_build_queue_fifo` should match the queue type. This variable is passed as input to the webhook lamda. You can check in the configuration tab in AWS lambda / webhook what value is used.

**Comment by maathor** [comment]
yes, thank you so much. it works like a charm now !
