### ISSUE TITLE
Errror: Cannot find GitHub release asset.

### ISSUE THREAD

**Issue by PrateekKhatri** [philips-labs/terraform-aws-github-runner#1574]
Getting error: Cannot find GitHub release asset.

Information:
Instance is created successfully while there are no active runners present. But after instance creation instance did not appear on github runner page.

While going through logs found below error:
{
    "errorType": "Error",
    "errorMessage": "Cannot find GitHub release asset.",
    "stack": [
        "Error: Cannot find GitHub release asset.",
        "    at /var/task/index.js:43048:15",
        "    at Generator.next (<anonymous>)",
        "    at fulfilled (/var/task/index.js:42948:58)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}

Could you please help with the above error?

**Comment by npalm** [comment]
Which release are you using? We have provided a fix in the latest release. See also #1541

**Comment by PrateekKhatri** [comment]
I am using v0.18.0

**Comment by npalm** [comment]
Please have a look at #1541 GItHub have changed the structure of the release, which broke the sync lambda. You have either to upgrade or download manually the distribution into the bucket.

**Comment by PrateekKhatri** [comment]
Hi,

This is my main.tf file. Is there something that I am missing?

module "runners" {
  source  = "philips-labs/github-runner/aws"
  version = "0.27.2"

  aws_region  = var.region
  vpc_id      = var.vpc_id
  subnet_ids  = var.public_subnet_ids
  environment = var.env

  github_app = {
    key_base64     = var.github_app_private_key
    id             = var.github_app_id
    client_id      = var.github_app_client_id
    client_secret  = var.github_app_client_secret
    webhook_secret = random_password.random.result
  }

  webhook_lambda_zip                = "./lambdas/webhook.zip"
  runner_binaries_syncer_lambda_zip = "./lambdas/runner-binaries-syncer.zip"
  runners_lambda_zip                = "./lambdas/runners.zip"
  enable_organization_runners       = false
  instance_types                    = ["t3.large"]
}

**Comment by npalm** [comment]
Did you double checked you also downloaded the lambda's? So not using accordantly the old ones?

**Comment by PrateekKhatri** [comment]
Thanks it is working fine now.

Do we have any tool to load test the GitHub runners?

**Comment by npalm** [comment]
No load tests available, we use some inhouse workflows that generate 400+ jobs.
