### ISSUE TITLE
Pull-based autoscaling support

### ISSUE THREAD

**Issue by axel3rd** [philips-labs/terraform-aws-github-runner#1588]
According GitHub [Recommended autoscaling solutions](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#recommended-autoscaling-solutions), this solution doesn't support **Pull-based autoscaling** feature.

I'm not sure to fully understand what is this feature, but it could be nice to support it 😁 (as the other major solution).

(No many historic found from [af32d](https://github.com/github/docs/commit/af32d9ab4250324cc0f9e4fe3d1c24077ddacd1e)).

**Comment by npalm** [comment]
It seems for pull based support a list of repositories is configured which are queried for pending jobs to decide to scale. We have chosen essentialy to scale based on events. For our own deployment we must handle 1000+ repositories. So by querying contuous 1000+ repos will hit rate limits. But we are of course open to explore how pull based can be supported if needed.

**Comment by toast-gear** [comment]
Pull based scaling is where the controller scales runners based on a metric every poll period (sync period), the 2 current metrics are:

1. the workflow queue depth on a defined list of repositories (very high API call intensive metric)
2. the number of busy runners (very low API call intensive metric)

It's useful for people that:
* can't or don't want to use webhooks
* have low scaling requirements and want something simple
* want a high degree of control over runner allocation server-side and are happy with overhead of named repositories server-side
* run a GHES environment where you can control your rate limit budget, including disabling rate limiting entirely

**Comment by npalm** [comment]
@toast-gear Thanks for the clarification! I worked last week on a PR to add a so called "simple pool" that checks every x interval the number of idle runners wanted, and once not meeting the setting scales up with the required number. See #1577

**Comment by npalm** [comment]
In PR #1577 we add a simple way for pull based scaling.  This change let you define a pool based on a cron expression and a desired pool size. Based on the cron expression lambda is triggered which will update the pool to the required size. Configuration will be provided as a list, so multiple combination of cron expression and pool sizes can be defined. For example to support a different poolsize on weekdays and weekends.

**Comment by toast-gear** [comment]
@npalm Sounds very interesting and similar-ish to some of the stuff in actions-runner-controller (ARC)! You can setup a [schedule](https://github.com/actions-runner-controller/actions-runner-controller#scheduled-overrides) to override the min and / or max replica count on a per runner set basis. It's helpful if you just want a basic scale up during core businesss hours to a set amount and scale down outside of core business hours to a set amount setup. With ARC being k8s based it's also helpful for cost optimisation too as you may want to scale your runner node group/s down to 0 outside of core business hours to save £££.

The pull based scaling stuff is more centred around continously scaling up and down from a poll period driven from some metric.

**Comment by axel3rd** [comment]
> In PR #1577 we add a simple way for pull based scaling

So can we consider that *[Pull-based autoscaling](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#recommended-autoscaling-solutions)* feature is(/will) supported ?
If "yes", I will change PR https://github.com/github/docs/pull/13742 by "[yes](http://link_to_simple_pool_doc) (org-level runners)"  and stage until merged.

**Comment by toast-gear** [comment]
It sounds sort of close enough right? It's just an informal term really so @npalm's work sounds like it's close enough that it could be considered ticked off feature wise once released?

**Comment by npalm** [comment]
> In terms of as a comparison to ARC it sounds more like schedules but it's sort of close enough right? It's just an informal term really so @npalm's work sounds like it's close enough that it could be considered ticked off feature wise once released? Up to @npalm really though.

@toast-gear you are right. The trigger is scheduled. The lambda is checking for the number of active runners before scaling. Do you have any other suggestion that fits in our approach?

**Comment by axel3rd** [comment]
*(PR https://github.com/github/docs/pull/13742 updated, will be un-draft when https://github.com/philips-labs/terraform-aws-github-runner/pull/1577 merged)*

**Comment by toast-gear** [comment]
I guess knowing a bit of the history would help.

Originally actions-runner-controller only had a single scaling metric, the `TotalNumberOfQueuedAndInProgressWorkflowRuns` pull based metric. Subsequent to that the `PercentageRunnersBusy` pull based metric was added and after that the webhook server was added introducing support for webhooks. As a result we needed a way of differentiating between the 2 scaling options as they were funamentally different, the former were built around a poll period, the latter an event. Pull based scaling was chosen for the former as the scaling is driven from environmental details discovered by the controller and webhook based scaling for the latter as the scaling is driven from an event provided by GitHub.

I'd say the key detail which is what makes both pull based and webhook based scaling pull based / webhook based scaling is the scaling is based on some environmental metric e.g. queue depth, how busy runners are or an event. For me, scheduled scaling is a different feature as it isn't really responding to an environmental metric, it has an arbrtiary runner count as defined by the schedule and will keep the count at that level regardless of the environment. In the case of ARC, you can even combine scheduled scaling with pull or webhook driven scaling so it really is its own feature.

So if we want to stay true to the pull based scaling term (which is a fairly informal term so it's not the end of the world) then the docs probably need a new column `Scheduled scaling` and with https://github.com/philips-labs/terraform-aws-github-runner/pull/1577 merged philips-labs/terraform-aws-github-runner can be said to support this feature. That said I'm not spent the time to go into detail on your new feature so if you feel it fulfills the pull based scaling well enough then feel free to make that call.

**Comment by axel3rd** [comment]
*❤️ pernickety discussions 😁*

So perhaps updating the [feature name](https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners#recommended-autoscaling-solutions) could be more accurate, proposal:

Features | actions-runner-controller | terraform-aws-github-runner
-- | -- | --
How runners can be scaled | Webhook events, Scheduled, Pull-based | Webhook events, Scheduled (org-level runners only) |

**Comment by axel3rd** [comment]
Can be closed with https://github.com/philips-labs/terraform-aws-github-runner/pull/1577.
GitHub doc following in https://github.com/github/docs/pull/13742.
