### ISSUE TITLE
Add an optional `project` variable to use for resource names

### ISSUE THREAD

**Issue by rashidnhm** [philips-labs/terraform-aws-github-runner#1630]
I am not sure if this is an existing functionality with the module but it would be a good feature to have.

## Use case
Having multiple deployments of the module in the same AWS Account. Currently if two projects require their own deployment of the infrastructure, there would be name conflicts if the environment is the same.

This would be the same as a "prefix"
```
module "github_runners" {
  # Inputs ...

  project = "projectA"
  environment = "dev"
}
```
In which case the resources deployed would have names:
```
projectA-dev-webhook
```

One way to implement this could just be a new local?

```
locals {
  resource_prefix = var.project != "" ? "${var.project}-" : ""
}
```

And then resource names can be for example:
```
resource "aws_resource" "example" {
   name = "${local.resource_prefix}${var.environment}-this-resource"
}
```

**Comment by ScottGuymer** [comment]
We currently deploy multiple instances of the module into the same account. 

We vary the environment variable to achieve this

`windows-production`
`linux-production` 

etc.

Is this not an option for you?

**Comment by rashidnhm** [comment]
> We currently deploy multiple instances of the module into the same account.
> 
> We vary the environment variable to achieve this
> 
> `windows-production` `linux-production`
> 
> etc.
> 
> Is this not an option for you?

Thank you for the response, that is what I have started doing.

It seems then the `Environment` tag is being set to that full value (as expected). However, I would ideally like to keep Environment to dev/staging/prod etc. I tried passing `Environment` as a tag when calling the module but seems it was not being honoured either.

In any case, I think an explicit way to set a prefix would be nice and more intuitive.

**Comment by ScottGuymer** [comment]
We are intending to remove built in tagging from the module in light of being able to use default tags at the provider level. The only thing that will remain are tags that are required for functionality of the module. And these will be prefixed with `ghr:`.

https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider

With this you could setup the provider with the required tags and automatically have them applied without having to change the module at all.

**Comment by rashidnhm** [comment]
Ah, well for my usecase that would suffice! 

Any roadmap on when built-in tagging will be removed? 

For now I will set up my tf code with provider default tagging so once the module is updated it will be a switch without any refactoring. Thanks for all the help!

**Comment by ScottGuymer** [comment]
Great! Let me know if you run into any showstoppers.

No roadmap yet, but we are looking at a few other changes that will likely come together.
