### ISSUE TITLE
Lamda functions creation fails with any number of concurrency

### ISSUE THREAD

**Issue by Dmitry1987** [philips-labs/terraform-aws-github-runner#1671]
Hello,
I am trying to deploy the setting for windows runners, and for some reason the Lambda functions step always fails no matter if I use the "-1" unlimited concurrency, or "1" or any other number. The account has a default concurrency limit, shouldn't it be able to run these lambdas at least in some form? (let's say a CI build runs once a day on average, why would it need more concurrency that the existing defaults on aws account) I am a bit struggling to understand if there's a bug or a problem with my settings?

The error looks like this (runs from the examples folder for windows runners): 

```
module.runners.module.runners.aws_lambda_function.scale_up: Destroying... [id=windows-scale-up]
module.runners.module.runners.aws_lambda_function.scale_up: Destruction complete after 2s
module.runners.module.runners.aws_lambda_function.scale_up: Creating...
module.runners.module.runners.aws_lambda_function.scale_up: Still creating... [10s elapsed]
module.runners.module.runners.aws_lambda_function.scale_up: Still creating... [20s elapsed]
module.runners.module.runners.aws_lambda_function.scale_up: Still creating... [30s elapsed]
╷
│ Error: error setting Lambda Function (windows-scale-up) concurrency: InvalidParameterValueException: Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [50].
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "e42a8d10-x-x-x-818a4698487d"
│   },
│   Message_: "Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [50]."
│ }
│ 
│   with module.runners.module.runners.aws_lambda_function.scale_up,
│   on ../../modules/runners/scale-up.tf line 1, in resource "aws_lambda_function" "scale_up":
│    1: resource "aws_lambda_function" "scale_up" {
│ 
```

I tried to set the scale_up_reserved_concurrent_executions to 1 and -1 , still the same. Any suggestions? would it only run after the limit increase (it takes AWS more than 3 days to respond for a limit increase, they're saying lambda is their most abused service and they're investigating our request lol)

**Comment by Dmitry1987** [comment]
After raising the account limits from defaults to 1000, I was able to deploy, just still confused why default limits are not enough even if specified concurrency would be 1 🤔  really strange. But that's AWS question I assume 😅  will resolve this ticket, but if anyone stumbles upon the same trouble, the real solution is to raise lambda concurrency account limits in the region where you're deploying this. Cheers :)

**Comment by npalm** [comment]
Looks like a time out of the Lambda, in one of the latest releases we decreased the default time out from 60 to 30 for the scale up lambda.  Try to set [`runners_scale_up_lambda_timeout `](https://github.com/philips-labs/terraform-aws-github-runner/blob/a7f9eb1571f7e719e1140fa9363a2076c31b4aaa/variables.tf#L96) to 60

**Comment by Dmitry1987** [comment]
> Looks like a time out of the Lambda, in one of the latest releases we decreased the default time out from 60 to 30 for the scale up lambda. Try to set [`runners_scale_up_lambda_timeout `](https://github.com/philips-labs/terraform-aws-github-runner/blob/a7f9eb1571f7e719e1140fa9363a2076c31b4aaa/variables.tf#L96) to 60

no, based on my knowledge of AWS error messages, this one is really about a specific param and not a timeout, also I tried many times over, and it had the same result until our account got a limit increase to 1000 total in region (from 50 or something) and then it worked immediately after the increase 🤷‍♂️

**Comment by Dmitry1987** [comment]
What's strange to me, is that it was failing both with -1 and 1 and 0 set. While after the increase it's happy for any number. The -1 I thought should work because it's a "best effort" kind of, with no reserve of capacity, but it didn't.

**Comment by npalm** [comment]
In case you set it to 0, the lambda should not be triggered. But this value should set the max number of concurrent lambda's that can run to hnadle the events on the queue and scale the runners. But your logs show that after 30 seconds the creation of the insstance is cancelled, which correlates with the lambda time out.

**Comment by folex** [comment]
Hi @npalm!

We happened to run into the same problem. And increasing timeout to 60 didn't actually help.

I'm having trouble wrapping my head around the error message
> Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [50].

As far as I can see, `50` is the "quota value", not a minimum 🤔 

Here's how it is described in AWS Lambda dashboard:
> The maximum number of events that functions can process simultaneously in the current Region.

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/1949356/175521667-7448ad8c-e518-4704-9cc1-b51b72c163f8.png">

**Comment by nahsi** [comment]
In our case setting `scale_up_reserved_concurrent_executions` to `-1` actually helped.

```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.19.0
```
