### ISSUE TITLE
GitHub Runner APP Permission 

### ISSUE THREAD

**Issue by PrateekKhatri** [philips-labs/terraform-aws-github-runner#1692]
Hi Team,

We are setting up GitHub Runner app and we need some information regarding assigning permission to GitHub App.

We need information why do we need to assign Administration "Read and Write" permission.

Permissions for repo level runners only:

- Repository:
- Administration: Read & write (to register runner)

We tried to give "Read only" permission, but that is not working.

Is there any specific reason to assign "Read and Write" permission Administration. 

Thanks

**Comment by ScottGuymer** [comment]
Thanks for the question.

The lambdas use the GH App to register and de-register runners from the repo or org. This is what the permissions are for. For a repo deployment without the permission is it not able to do this as you experienced and will not be able to function.

**Comment by PrateekKhatri** [comment]
Thanks for the information.
