### ISSUE TITLE
Add option to disable auto update of github runner

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#1694]
## Description

GitHub released an option to disable the auto update of runners. https://github.blog/changelog/2022-02-01-github-actions-self-hosted-runners-can-now-disable-automatic-updates/ Now we can add an option to support this by the module

## Default

Question is what should be the default?

- Without AMI. Keep the current behaviror. With the S3 we haven't any issue for months.
- With the AMI. The whole purpose of the AMI is to boot as fast as we can. So think we should consider to disable the auto update for AMI's. AMI templates are provided as example

**Comment by ScottGuymer** [comment]
This feature is merged
