### ISSUE TITLE
Add repository name when running in Ephemeral at Org level

### ISSUE THREAD

**Issue by Fgerthoffert** [philips-labs/terraform-aws-github-runner#1696]
Hi,

Thanks for the work on this terraform module at the Org level via a GitHub App.

One thing that does not appear to be supported (yet?) is the ability to quickly identify which repository triggered ephemeral runner creation while in "Org" mode.

I'm interested in two particular use cases:
- For billing purposes, to get a breakdown of cost per repo
- For debugging purposes, by looking at the EC2 console, to quickly match a runner with the repository that initiated it

Both of which could be addressed by attaching a 'Repository' tag to the EC2 resource:
https://github.com/philips-labs/terraform-aws-github-runner/blob/6dbff131cdacb5d5518ec68c099bda4f707f2171/modules/runners/lambdas/runners/src/aws/runners.ts#L157-L166

The repository name appears to be always available, whether running the module in ["Org" or "Repo" level](https://github.com/philips-labs/terraform-aws-github-runner#major-configuration-options). 

https://github.com/philips-labs/terraform-aws-github-runner/blob/6dbff131cdacb5d5518ec68c099bda4f707f2171/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts#L160

And I was able to confirm that in Org mode, the actual payload does contain `repositoryName`.

I'm happy to submit a PR to add a `Repository` tag by trickling `repositoryName` down to `createRunner`, but wanted to get your input before doing so.

The easiest option would be to add a `Repository` tag which we could take the value `${payload.repositoryOwner}/${payload.repositoryName}`. 
Although it would be a duplicate of `Owner` for those in `Repo` mode, it would ease filtering for `Org` users (compared to having only the repo name).

Thoughts?

**Comment by npalm** [comment]
Thanks for creating the issue. But solving measuring the cost is not that simply. Tagging an instance with the event that leads to instance creation is not hard. Besides a repo trigger it could also be the pool lambda. But once an instance is created, for example by the workflow_job event of a repo. There is no guarantee that the agent starting in the instance will pick up a job of tht repo. The only thing we know i will take up a job. Which could be also from another repo. The orchestration / selection is done by GiHub. And we cannot influence that. 

The logs of runner agents contain information about which repo job is executed. This will make generating billing information much more complex.

**Comment by Fgerthoffert** [comment]
I did indeed miss the fact that a runner could be created by a repo but used by another one.

Thanks for the clarification.
