### ISSUE TITLE
[Scaling Up]Runner created but not registered in github

### ISSUE THREAD

**Issue by wippyz** [philips-labs/terraform-aws-github-runner#1715]
Hi we suddenly have problem where the scaled up runner are created successfully but not registered in github (not showing in the runner menu in github)
would appreciate any help to where to start troubleshooting it.
Thank you very much

**Comment by npalm** [comment]
Two options for quick checks
- look up the logs in cloudwatch
- in ec2, select instance, select connect, select ssm. Next check the logs in /vag/log

**Comment by mahela-aws** [comment]
I'm also experiencing a similar issue when I change the ami to `ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*` but works fine with `amzn2-ami-hvm-2.*-x86_64-gp2` ami.

I will try to check `/var/logs` as suggested above, I'm curious if this has been tested with ubuntu images @npalm

**Comment by mahela-aws** [comment]
also I cannot see anything suspicious in cw logs, scaling up and down work just fine but runners are not registered in github organisation

**Comment by wippyz** [comment]
i couldnt find anything suspicious in /var/logs ... will try to take a look at the ami

**Comment by ScottGuymer** [comment]
The userdata script will log to `/var/log/user-data.log` you should see at least something in this log.

If not then its likely that the userdata functionality is not working as expected and the script is not being triggered.

Do you customise the userdata script in any way?

**Comment by mahela-aws** [comment]
this is what I see in user-data.log

```
ssm-user@ip-10-0-1-93:/var/snap/amazon-ssm-agent/4046$ cat /var/log/user-data.log
/var/lib/cloud/instance/scripts/part-001: line 6: yum: command not found
```

**Comment by npalm** [comment]
Are you using amazon linux2?

**Comment by ScottGuymer** [comment]
If you are using Ubuntu or some other debian derivative you need to customise the user-data script something like this example

https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/examples/ubuntu/templates/user-data.sh

**Comment by mahela-aws** [comment]
yeah I noticed it now.
https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/templates/user-data.sh
this script is not compatible with ubuntu

**Comment by mahela-aws** [comment]
@ScottGuymer if we want to switch between `ubuntu` and `amzn-linux` runners how can we achieve this ? we are referencing your module in our code base

**Comment by mahela-aws** [comment]
by default is it using `amzn-linux` compatible user-data script ?

**Comment by ScottGuymer** [comment]
By default it assumes amzn linux but you can look at the ubuntu example for a way run unbuntu agents..

**Comment by scream314** [comment]
What do you think about adding the example Ubuntu scripts to `modules/runners/templates/` as `$name-ubuntu.sh`, adding 1 additional key (eg. `linux-ubuntu`) to each of the locals `default_ami `, `default_userdata_template`, `userdata_install_runner` and `userdata_start_runner`, so one could use the variable `runner_os` (eg. set it to `linux-ubuntu`) to control what kind of runner is created.

I think adding more support for Ubuntu would be great, as
 * there are already examples for building an Ubuntu-based AMI
 * many of the public actions do not really support AMZ2

**Comment by ScottGuymer** [comment]
I have opened #2022 to consider moving fully to ubuntu for the module.

Closing this to have further discussion there.
