### ISSUE TITLE
Is it possible to run this module over two aws accounts?

### ISSUE THREAD

**Issue by dvdgitman** [philips-labs/terraform-aws-github-runner#1759]
I׳m trying to have github runners on two different aws accounts.

**Comment by ScottGuymer** [comment]
Yes, this is possible and is in fact what we do internally in Philips.

You have to use the modules in the `/modules` folder directly rather than the main module and then glue them together yourself, using the main module as inspiration.

**Comment by dvdgitman** [comment]
I see thanks, is it possible to run a runner per job? Because every job that i do waits for the first one to finish

**Comment by npalm** [comment]
The module has several options to scale. The ephemeral mode is using a runner only once for a job. Once done the instnace is destroyed.

**Comment by dvdgitman** [comment]
Thanks!
