### ISSUE TITLE
Ephemeral runner wait time

### ISSUE THREAD

**Issue by prashanthbgoud** [philips-labs/terraform-aws-github-runner#1766]
Hello All,

We have tested the ephemeral runners in our organization and it works like charm.
we would like to share some feedback and ask if there is a way to decrease the the wait time of the job.

**Scenario 1:**
we have used default ami's from the module, when I triggered 1 pipeline with 5 jobs, below is the time it took to start the job.

job num  | wait time in seconds to start job
--------- | --------------------------------
1st Job    | 2:25
2nd Job  | 2:54
3rd Job   | 3:08
4th Job   | 3:21
5th Job   | 3:56

**Scenario 2:**
We have the pre-built ami's using packer, when use this ami's

job num  | wait time in seconds to start job
--------- | --------------------------------
1st job     | 1:26
2nd job   | 1:44
3rd job   | 1:45
4th job   | 2:10
5th job   | 2:43

**terraform code:**

```
module "github-runner" {
  source = "git::https://github.com/philips-labs/terraform-aws-github-runner.git?ref=v0.34.2"

  aws_region = var.default_region
  vpc_id     = data.aws_vpc.vpc.id
  subnet_ids = data.aws_subnet_ids.private.ids

  enable_ssm_on_runners = true
  environment           = "github-runners-ephemeral"
  instance_types        = ["m4.large", "m5.large", "m4.xlarge"]
  runners_maximum_count = 10
  ami_filter            = { name = [var.ami_name_filter] }
  ami_owners            = ["self"]

  github_app = {
    key_base64     = var.github_app.key_base64
    id             = var.github_app.id
    webhook_secret = random_id.random.hex
  }

  webhook_lambda_zip                  = "lambdas-download/webhook.zip"
  runner_binaries_syncer_lambda_zip   = "lambdas-download/runner-binaries-syncer.zip"
  runners_lambda_zip                  = "lambdas-download/runners.zip"
  enable_organization_runners         = true
  runner_extra_labels                 = "ephemeral"
  volume_size                         = 10
  create_service_linked_role_spot     = true
  delay_webhook_event                 = 0
  enable_ephemeral_runners            = true
  log_level                           = "debug"
}
```

**Questions:**
Do you have any suggestions to decrease the wait time?
is it possible to have some pool of idle runners in case of ephemeral?

**Comment by prashanthbgoud** [comment]
@ScottGuymer Thanks for the reply.

if I understood correctly can I use `idle_config` to setup some idle runners. if that is the case this pool of runners act as an ephemeral runners or as the normal runners?

**Comment by ScottGuymer** [comment]
If you have the ephemeral config turned on, all runners will be ephemeral.

**Comment by prashanthbgoud** [comment]
`idle_config` did not for work for me, can you point me to the configuration of pool of runners?

**Comment by prashanthbgoud** [comment]
I tried pool with below variables, but unfortunately it did not show up any additional runners.

```
  pool_runner_owner = "xxx-xxx"
  pool_config = [{
    size                = 10 
    schedule_expression = "cron(* * * * ? *)"
  }]

```

**Comment by prashanthbgoud** [comment]
there is a typo in the org name, Thanks for your help I am closing this.

**Comment by juldou** [comment]
Hi, have any of you found a way how to know when to increase a pool? (e.g. from metric, logs, etc...). The best would be to fire some alarm.
