### ISSUE TITLE
GitHub Runner API Endpoint - Custom Domain

### ISSUE THREAD

**Issue by PrateekKhatri** [philips-labs/terraform-aws-github-runner#1767]
Hi Team,

I am trying to add custom domain to GitHub Runner API Endpoint, but after adding custom domain to the GitHub app, instances are not creating also logs are not getting generated for same.

Do you have any idea on this, how we can attach custom domain?

**Comment by PrateekKhatri** [comment]
Hi Team,

Any updates on this?

**Comment by ScottGuymer** [comment]
At this moment its not something we have found the need to do or try internally so we cant really guide you with any common issues.

How are you adding the domain to the API GW?

**Comment by PrateekKhatri** [comment]
Hi,

I created one custom domain and added to API GW.

The issue resolved now, we  just need to disable "Default endpoint" in API GW.
