### ISSUE TITLE
Best way to keep a number of warm runners when using ephemeral runners

### ISSUE THREAD

**Issue by jonb-ifit** [philips-labs/terraform-aws-github-runner#1784]
I'm using ephemeral runners. I would like to reduce time to start jobs by keeping a couple instances warm. 

I see that there is both `pool_config` and `idle_config`. I have played around both, but I don't fully understand the options and how well they play with ephemeral runners.

Here's a majority of my config:
```tf
module "runners" {
  # bare minimum stuff to get it running
  source                          = "philips-labs/github-runner/aws"
  version                         = "0.34.1"
  create_service_linked_role_spot = true
  aws_region                      = var.region
  vpc_id                          = var.vpc_id
  subnet_ids                      = var.subnet_ids
  # blah blah ...

  # enable access to the runners via SSM
  enable_ssm_on_runners = true

  instance_types = ["t4g.medium", "c6g.medium"]
  runners_maximum_count = 6
  pool_config = [{
    size                = 2
    schedule_expression = "cron(* 0,14-23 * * ? *)" # 7am-15:59 MST
  }]

  # Ephemeral runners will be terminated after a single job
  # When using ephemeral runners there is no need to wait
  enable_ephemeral_runners = true
  delay_webhook_event      = 0

  # override scaling down
  scale_down_schedule_expression = "cron(* * * * ? *)"

  runner_architecture = "arm64"
}
```

When I've used this config, it seems like it always starts up 4 instances immediately, not 2.

What's the right way to keep a couple warm instances when using ephemeral runners? I'm probably doing it wrong.

**Comment by npalm** [comment]
The `pool_config` is meant for the ephemeral runners. This should start 2 runners. Fer every `workflow_job` event received from GitHub a neww runners should be created. Did you configure the app for only `workflow_jobs`. The `scale_down_schedule_expression` config is a lambda that terminates idle instances and respect the `idle_config`. The `idle_config` should not be configured. Is meant for the non-ephemeral runners to avoid stopping stop them. You could set this two 2 asl well but should not interfere. 

Will also check our environment tomorrow.

**Comment by jonb-ifit** [comment]
Cool, thanks for the info! So, I guess it sounds like I'm doing it the right way if I want to keep a couple pre-warmed instances? Here's my full configs.

Throughout the day, even when there were no jobs being run (especially with the strict label matching enabled) I would often see 4 running instances, but not all day. I haven't debugged specifics yet. Maybe it really is receiving webhook messages twice? Maybe SQS messages are piling up? I can debug further later, but thanks for the sanity check!

```tf
module "runners" {
  # bare minimum stuff to get it running
  source                          = "philips-labs/github-runner/aws"
  version                         = "0.34.1"
  create_service_linked_role_spot = true
  aws_region                      = var.region
  vpc_id                          = var.vpc_id
  subnet_ids                      = var.subnet_ids

  environment = var.env

  github_app = {
    key_base64     = var.github_app_key_base64
    id             = var.github_app_id
    webhook_secret = random_id.random.hex
  }

  webhook_lambda_zip                = local.webhook_file
  runner_binaries_syncer_lambda_zip = local.runner_binaries_syncer_file
  runners_lambda_zip                = local.runners_file

  enable_organization_runners             = true
  runner_enable_workflow_job_labels_check = true
  runner_extra_labels                     = "my-label"

  enable_ssm_on_runners = true

  instance_types = ["t4g.medium", "c6g.medium"]
  runners_maximum_count = 6
  pool_runner_owner = "xyz"
  pool_config = [{
    size                = 2
    schedule_expression = "cron(* 0,14-23 * * ? *)"
  }]
  enable_ephemeral_runners = true
  delay_webhook_event      = 0
  scale_down_schedule_expression = "cron(* * * * ? *)"
  runner_architecture = "arm64"
}
```

**Comment by jonb-ifit** [comment]
I confirmed that "Workflow job" is the only event type selected on the app
![image](https://user-images.githubusercontent.com/44378459/155456820-2fb10bc2-59d0-4832-93cb-bfc33d26e5d3.png)

**Comment by jonb-ifit** [comment]
When I _first_ set the pool config, I got this in the logs 
![image](https://user-images.githubusercontent.com/44378459/155459007-e06a4446-5fec-4a10-91fb-7a4a30847529.png)
This may be intended for a reason. I'm not sure

**Comment by npalm** [comment]
> When I _first_ set the pool config, I got this in the logs where it added 2 instances and then added 2 more instances before it determined that the pool was full ![image](https://user-images.githubusercontent.com/44378459/155459007-e06a4446-5fec-4a10-91fb-7a4a30847529.png) This may be intended for a reason. I'm not sure

Looks like you got indeed four instances, according to the log. The pool size is maintained by a lambda which in you cased will be triggered ever minute. The pool check is looking for instances that are idle and can take a job. Most likely it takes more than one minute to boot and register the instance. Which means the second time the pool lambda is chenking it doesn't find a warm instance, and create two more instances.

**Comment by jonb-ifit** [comment]
Yeah, the cold starts seem to take about 90s. It sounds like my choices would be to modify the pool config to check less or just let it ride and end up with more instances for a short time and let the scale down level it off later.

Thanks again for the sanity check. I'm cool with closing this.

**Comment by killersalt** [comment]
I would like to add that the pool size is being doubled I don't know why... So, if you want 1 idle worker you should set pool size to 0.5 ahahahahahahaah hilarious!!! :D Really cool easter egg!

**Comment by killersalt** [comment]
I would like to add that this answer is correct. If you increase the schedule expression inside pool_config from * * * * * ? * (one minute) to */2 * * * ? * (to minutes) the lambda function behaves as expected. So the take into account the cold start from the ec2 instance.
