### ISSUE TITLE
Add lambda linter for runners

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#18]
Add linting and update workflow, check webhook for examples

**Comment by mcaulifn** [comment]
@npalm Got any more detail for this one?

**Comment by npalm** [comment]
Other lambda's has a linter for code checking, the lambda webhook is still missing a linter setup

**Comment by buamod** [comment]
I thought of working on this but I didn't understand the problem

**Comment by npalm** [comment]
@buamod always great to get some help. For TypeScript we use eslint to run code cecks local and in CI. In this module https://github.com/philips-labs/terraform-aws-github-runner/tree/develop/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer you will find an `eslint` configuration, task in `package.json` and in the `.github/workflows` you can see that the linter is running in CI. Same holds for the webhook. For the component runners https://github.com/philips-labs/terraform-aws-github-runner/tree/develop/modules/runners/lambdas/runners the eslinter is missing.
