### ISSUE TITLE
SSM parameters not cleaned up

### ISSUE THREAD

**Issue by samuelb** [philips-labs/terraform-aws-github-runner#1808]
Hello

I found today that we have hundreds of AWS System Manager Parameters defined. The lambda is creating those when starting a new runner instance to pass the authentication token and other parameters to the runner agent software.

It's so many, that `aws ssm describe-parameters` runs into rate limits. It's not only about keeping things clean, but also it has functional impact. 

Can a cleanup of unneeded parameters get implemented?

**Comment by samuelb** [comment]
To clean up the parameters, I ran `aws ssm describe-parameters --filter "Key=Name,Values=action-runner-" | jq -r ".Parameters[].Name" | xargs -n 10  aws ssm delete-parameters --names`

**Comment by tonyc-blastpoint** [comment]
Still an issue.

**Comment by tonyc-blastpoint** [comment]
Still an issue.

**Comment by tonyc-blastpoint** [comment]
Still an issue.

**Comment by tonyc-blastpoint** [comment]
Still an issue!

**Comment by tonyc-blastpoint** [comment]
...still an issue.

**Comment by samuelb** [comment]
Still an issue, but a PR is on the way

**Comment by chasemgray** [comment]
@samuelb did your PR get merged to fix this?

**Comment by samuelb** [comment]
I meant PR #2587. I'm not the author of it and no, it didn't got merged till now.

**Comment by chasemgray** [comment]
Is anyone going to reopen and merge the PR? We hit a 10,000 SSM parameter limit due to old parameters not being cleaned up.
