### ISSUE TITLE
Due to the squash merge approach release notes are not transparent/incomplete and semver is broken

### ISSUE THREAD

**Issue by marcofranssen** [philips-labs/terraform-aws-github-runner#1810]
The release workflow has a **bug** due to squashing PRs.

- If a PR starts with a `bugfix` commit, and following PRs contain a `feat` commit only the bugfix commit is picked by semver after squashing the PR. Causing Semver to be broken. (patch number is incremented, the minor should have been bumped)

- The release notes do only contain the first commit in a PR.

Both these issues complicate tremendously how consumers of this module can identify breaking changes (not mentioned in release notes), neither to make an upgrade plan to bump to newer version.

Due to the lack of proper release notes and correct semver (broken due to squashing PRs) consumers of this module need to be very deep into the terraform code to figure out what are the changes and what has to be updated in case of new releases.

1. Can you change your PR merge approach to **only** use a normal merge or a rebase?
    This will resolve the **semver** and release notes **documentation** **bug**.
2. Can you manually update the release notes for the last couple of releases to make those also more transparent for consumers of this module?

**Comment by ScottGuymer** [comment]
The approach that we use is 
- PRs are squashed into the develop branch to create a single commit per PR (preserving any important notes from the PRs commits)
- Develop branch uses a regular merge to main which preserves the PR commits
- Tags are created on main branch
- Release notes are created from the commits on main (which are directly each related to a PR)

The intent is that each PR should address a single issue and so have a single type of semantic commit. I'm sure this isn't always the case but is where we strive to be.

Can you share some instances where the release notes are not correct that we need to solve?

**Comment by marcofranssen** [comment]
E.g. the v0.34.0 release only shows the following in the release notes.

However if you look at the merged PR it also resolved some bugs which are not mentioned in the release notes.

https://github.com/philips-labs/terraform-aws-github-runner/pull/1676/commits

In general all releases state only one release note while there have been multiple fixes, chores, features.

This heavily complicates it to see what changes are actually in the release without having the need to look at PRs and their commits and sometimes even the code itself to understand the impact of a release.

I see [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/.release/package.json) semantic release is used. I also see people are using the commit convention to be able to use semantic release, but due to the squashing all that value is thrown away. Besides that it makes the changelogs not really transparant and releases look like very undocumented.

**Comment by ScottGuymer** [comment]
The PR you mentioned ended in a single line change but contained 4 commits after changes from reviews.

![image](https://user-images.githubusercontent.com/956825/157643759-874bdb3f-da41-473e-a741-894063d8007c.png)

I don't see the value in any of the other commits in this PR being in the changelog or release notes. It would make then even harder to read and be polluted with lots of commits that are purely part of the PR process.

The delta between the releases can be seen by clicking on the link and shows all the commits that were in a release including the chores and other things omitted from the release notes. [Example](https://github.com/philips-labs/terraform-aws-github-runner/compare/v0.33.0...v0.34.0)

The chores do seem to be omitted from the release notes, which again seems sensible as they should be inconsequential bumps of packages and are mostly from dependabot. Including all these would have little value to an end user.


Where there have been multiple fixes or features in a release they are displayed correctly, like in [v0.32.0](https://github.com/philips-labs/terraform-aws-github-runner/releases/tag/v0.32.0) for example.

We dont require commit signing on the repo from contributors.
