### ISSUE TITLE
Error: remote: Invalid username or password. │ fatal: Authentication failed

### ISSUE THREAD

**Issue by PrateekKhatri** [philips-labs/terraform-aws-github-runner#1877]
Hi Team,

We have enabled 2FA on our GitHub organisation and after that we are facing issue while running jobs on self-hosted runner. We are getting below error when we are trying to clone one repo from other:

**remote: Invalid username or password. │ fatal: Authentication failed for**

Also, when we run the same job at GitHub hosted runner, job ran successfully .

Any idea why it is happening?

Thanks in advace.

**Comment by npalm** [comment]
@PrateekKhatri  still facing the issue? Or can we close this issue?
