### ISSUE TITLE
Feature: Expose throughput for block device mappings

### ISSUE THREAD

**Issue by Octogonapus** [philips-labs/terraform-aws-github-runner#1887]
This is a feature request to please expose the throughput parameter for block device mappings. It will be [this parameter](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#throughput).

**Comment by npalm** [comment]
We expose the parameter, see iops https://github.com/philips-labs/terraform-aws-github-runner#input_block_device_mappings
