### ISSUE TITLE
Running both windows and linux instances

### ISSUE THREAD

**Issue by AlexShemeshWix** [philips-labs/terraform-aws-github-runner#1901]
Hi
Is it possible to have both windows and linux instances?
I have ci jobs that are running on both windows and linux machines at the same time.
My goal is to have a fleet of windows and linux machines without creating 2 separate terraform deployments.
Is it even possible?

**Comment by shashidhar087** [comment]
I have created and managing multiple runner types. I created a new folder and created terraform file for each runner type  and invoked terraform module. From deployment standpoint, Yes it is single deployment. No need to have multiple deployments.

**Comment by npalm** [comment]
@shashidhar087 but you require still multiple apps? Or are you using a strict check on the job?  

See also discussion #518

**Comment by shashidhar087** [comment]
@npalm Yes we need multiple runners like Linux 2, Ubuntu, Windows supporting both x64 and arm64 arch.
We set custom runner labels for each type of runner. We use Ephemeral + Pool of runners.
When a workflow job need a runner, the job is assigned to runner immediately and do not wait for the workflow to lanch the runner which could take 3-5 mins to setup runner.

Hence, we have multiple terraform files invoking the module per runner type. Currently we have 3 runner types - Amazon Linux 2 x64 and arm64, Ubuntu 1804 arm64 type
