### ISSUE TITLE
Question: What is the behavior with dependencies between jobs?

### ISSUE THREAD

**Issue by killersalt** [philips-labs/terraform-aws-github-runner#1902]
Hello!
As the title says I would like to know how the module behaves when there are dependencies between the jobs, like needs in GitHub Actions or when there are jobs that have outputs that are used in another jobs.
Thank you

**Comment by ScottGuymer** [comment]
Jobs inside a workflow file are presented as independent jobs to the runners and can be allocated to different runners. The dependencies between jobs are handled by the GH control plane and jobs will only be passed to the runners when their needs are satisfied (e.g. a previous completed jobs).

the handling of passing outputs etc is handed by the GH control plane and not this module. There is nothing special needed to enable this.
