### ISSUE TITLE
Wrong instance type

### ISSUE THREAD

**Issue by alberthuang24** [philips-labs/terraform-aws-github-runner#1903]
The type I set does not include (m1.small).

![image](https://user-images.githubusercontent.com/20190812/161084554-5ca2c685-37b0-4b7e-b297-0867e87c41f9.png)

![image](https://user-images.githubusercontent.com/20190812/161084613-d45862ba-1105-4270-b54e-eb01d13cf33c.png)

**Comment by npalm** [comment]
The log you are showing is not matching your configuration. Are you sure they are alligned? Still having the issue?
