### ISSUE TITLE
How to debug windows instances

### ISSUE THREAD

**Issue by AlexShemeshWix** [philips-labs/terraform-aws-github-runner#1927]
Hi ive deployed module with windows instances. 
When i queue job for this instance, i can see its scaled up in aws. I can see the instance. But it never registers to github action runners, and jobs hangs forever.
How can i see logs of the github runner on windows instance?
Thanks

**Comment by AlexShemeshWix** [comment]
Another related question. Can i create my own AMI that is not based on windows core ami. I need to install software on it, the fact that its cmd line only without ui complicates things.

**Comment by ScottGuymer** [comment]
hi

I feel your pain in trying to debug this. I assume if you have no logs in cloudwatch then the runner userdata script is not finishing and therefore logs are not being shipped. Meaning you need access to the host.

Firstly the default AMI for windows is a server-core version meaning no UI so you will connect via the console.

Ill share the workflow I ended up with.

- Ensure `enable_ssm_on_runners` is set to true to give you access 
- when the instance scales up remove the environment tag to prevent scaling down
- use "connect via console" in the AWS UI to connect
- If it all works you should end up with a terminal
- Take a look in `C:/UserData.log` to see what went wrong
- If that doesnt help you can try running the userdata script in the terminal to debug.

**Comment by ScottGuymer** [comment]
> Another related question. Can i create my own AMI that is not based on windows core ami. I need to install software on it, the fact that its cmd line only without ui complicates things.

Yes you can definitely build an AMI, which base OS you use is up to you YMMV. There is a packer example [here](https://github.com/philips-labs/terraform-aws-github-runner/tree/develop/images/windows-core-2019)

**Comment by AlexShemeshWix** [comment]
> hi
> 
> I feel your pain in trying to debug this. I assume if you have no logs in cloudwatch then the runner userdata script is not finishing and therefore logs are not being shipped. Meaning you need access to the host.
> 
> Firstly the default AMI for windows is a server-core version meaning no UI so you will connect via the console.
> 
> Ill share the workflow I ended up with.
> 
> * Ensure `enable_ssm_on_runners` is set to true to give you access
> * when the instance scales up remove the environment tag to prevent scaling down
> * use "connect via console" in the AWS UI to connect
> * If it all works you should end up with a terminal
> * Take a look in `C:/UserData.log` to see what went wrong
> * If that doesnt help you can try running the userdata script in the terminal to debug.

Hi. Windows example has no userdata script. Do i need userdata to startup github runner on windows instance?

**Comment by ScottGuymer** [comment]
The standard windows userdata can be found here https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/templates/user-data.ps1

**Comment by AlexShemeshWix** [comment]
Hi. Sorry fro resurecting this one.
Ive circled back to this issue with windows instances.
https://github.com/philips-labs/terraform-aws-github-runner/issues/3095
For some reason merging choco profile into powershell env, causes problems with GITHUB_PATH mechanism of github runner.
i can solve this problem by simply not installing choco on my machines. Not sure why do you need it anyway. But in order to do this i need to force tf module to use my user-data or not use any user-data at least. Because its injected by lambda when instance is created. 
Can i make it not execute user data at all?
