### ISSUE TITLE
CloudWatch does NOT show required labels

### ISSUE THREAD

**Issue by bumbummen99** [philips-labs/terraform-aws-github-runner#1942]
For some reason my CloudWatch does not show anything generated by `logger.debug`, this does lead to the required labels not being shown.

**Comment by npalm** [comment]
@bumbummen99 please can you share the logging configuration. By default only info level is logged. By setting `log_level` to `debug` the lamba's should log on debug level. To check if changes are correctly applied you can go to the lambda in the AWS console and check the environment variables of the lamba's

**Comment by bumbummen99** [comment]
> `log_level`

Thanks that is exactly what i was looking for, i have no clue how i did not find it since i did ctrl+f `debug` on the readme...
