### ISSUE TITLE
Moving the file descriptors to different places at the start of user-data is potentially unwanted, can it be made optional?

### ISSUE THREAD

**Issue by Makeshift** [philips-labs/terraform-aws-github-runner#1959]
Hi,

Specifically, this line right at the start of user-data: https://github.com/philips-labs/terraform-aws-github-runner/blob/58bfec0f1a3ee7a55054f1e7ebd77e0ee156c04a/modules/runners/templates/user-data.sh#L2
interferes quite significantly with the normal expected output of `/var/log/cloud-init-output.log`, and also makes cloudinit think that userdata is finishing _much_ faster than it actually is, as it uses stdout as an indicator of when a script has finished running. With that line in place, userdata finishes in ~6 seconds, even though the rest of my userdata takes a further 90 or so seconds to complete.

This means we're getting not-fully-provisioned hosts starting github actions jobs, which is causing some undesired behaviour.

As part of #1956 I made the user_data gzipped, I could add to this PR to make the file descriptor changes optional or remove it entirely if `cloud-init-output.log` is good enough for most debugging tasks? (the output of cloudinit is streamed to the console anyway, so right clicking ec2 -> view logs will still show the output even if you don't have this exec in place)

Cheers

**Comment by ScottGuymer** [comment]
This is a nice catch. Definitely not desired behaviour at all.

I think that removing this and adding the correct config to push the existing logs to cloudwatch is a better solution all round.

**Comment by Makeshift** [comment]
I think in that case, the only thing that would need changing is removing the above line and editing this one:
https://github.com/philips-labs/terraform-aws-github-runner/blob/58bfec0f1a3ee7a55054f1e7ebd77e0ee156c04a/modules/runners/logging.tf#L15
to be `/var/log/cloud-init-output.log`, unless I'm missing something.

**Comment by ScottGuymer** [comment]
That seems about right to me.

Do you happen to know where the windows one would be too?

**Comment by Makeshift** [comment]
I'm afraid I'm not sure where the default one for Windows is. I know we're specifying one here for the output https://github.com/philips-labs/terraform-aws-github-runner/blob/58bfec0f1a3ee7a55054f1e7ebd77e0ee156c04a/modules/runners/templates/user-data.ps1#L4
but I don't think that messes with descriptors or anything so I think it's safe?

**Comment by ScottGuymer** [comment]
indeed seems to work in a different way.
