### ISSUE TITLE
RUNNER_LABELS contains trailing ',' if runner_extra_labels is not set

### ISSUE THREAD

**Issue by lmeynberg** [philips-labs/terraform-aws-github-runner#1961]
If you not set any extra labels with `runner_extra_labels`, because the default ones `"self-hosted,${var.runner_os},${var.runner_architecture}` would be good enough, you cannot use `runner_enable_workflow_job_labels_check` as this prevent scaling of any runners:
```
 Received workflow job event with labels: '["self-hosted","linux","arm64"]'. The event does NOT match the runner labels: 'self-hosted,linux,x64,'
```

A dummy label in `runner_extra_labels` would be a workaround but then one must  update any `runs-on: [self-hosted, linux, x64]` to `runs-on: [self-hosted, linux, x64, dummy]` as long as https://github.com/philips-labs/terraform-aws-github-runner/issues/1714 is unsolved.  

Maybe `runner_labels` could be a added as variable of the main module with `"self-hosted,${var.runner_os},${var.runner_architecture}` as default value. So it can be overridden completely of needed. Then `runner_extra_labels` is not needed anymore.

**Comment by shashidhar087** [comment]
We need `runner_extra_labels` as we have multiple runner types based on Linux OS. We use custom labels to assign the workflow job to one particular runner type.

**Comment by ScottGuymer** [comment]
The labels `self-hosted,OS,ARCH` are automatically added by the agent when registering the runner to GH. 

I think you are correct in that this is related to #1714 and the label matching logic needs some work and this particular use case needs to be added into the tests.

**Comment by jonohill** [comment]
This is still an issue. If runner_extra_labels is empty then it should not be appended to the list of labels.
