### ISSUE TITLE
Github App permission issue

### ISSUE THREAD

**Issue by theabrar** [philips-labs/terraform-aws-github-runner#200]
## Summary

I have followed the README and created the Github App and setup the terraform modules, however, can't get the runners created. Please see the error below, I guess its something to do with App permissions but I have tried them all and have been at this for a while, but no luck, not sure what I'm missing!!

## Steps to reproduce
Run the example module and try to create a runner
## What is the current *bug* behavior?
Does not create a runner

## What is the expected *correct* behavior?

Should create a runner

## Relevant logs and/or screenshots

```
2020-09-08T12: 53: 03.620Z	61a6e96f-ddd4-5bd3-ac59-bebe5d0eb4b7	ERROR	RequestError [HttpError
]: Not Found
    at /var/task/index.js: 14863: 23
    at processTicksAndRejections (internal/process/task_queues.js: 97: 5) {
  status: 404,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue,
    08 Sep 2020 12: 53: 03 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '404 Not Found',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'DFE0: 5DBC: 88B16E0:A4C558A: 5F577EAF',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4986',
    'x-ratelimit-reset': '1599572823',
    'x-ratelimit-used': '14',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https: //api.github.com/orgs/theabrar/actions/runners/registration-token',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/18.0.3 octokit-core.js/3.1.1 Node.js/12.18.2 (linux; x64)',
      authorization: 'token [REDACTED
      ]',
      'content-length': 0
    },
    request: { hook: [Function: bound bound register
      ]
    }
  },
  documentation_url: 'https: //docs.github.com/rest/reference/actions#create-a-registration-token-for-an-organization'
}
```

## Possible fixes

I think this issue can be resolved by automating the GitHub app creation, possibly using probot.

**Comment by JeroenKnoops** [comment]
I know there is some extra info in the blog Niek wrote in may.
It seems that you need to manually add a runner, in order to kickstart the process.

https://040code.github.io/2020/05/25/scaling-selfhosted-action-runners

I think we need to update the documentation here in order to avoid startup problems.

**Comment by theabrar** [comment]
Thanks for the reply, I have referred the blog too, also added a manual runner(the job worked fine on the manual runner)and the above are the logs from cloudwatch of the scale-up lambda, Github app is sending the events as it has green ticks. 
Not sure what's wrong with the registration-token thing, I even gave Actions and self-hosted permissions.

**Comment by theogravity** [comment]
I'm actually having the same problem as well. I did the manual runner, which is offline, get the same issue as the OP.

**Comment by theabrar** [comment]
I think the issue for me was, my account is not an organisation and the Gihtub API didn't like that, hence, a 404. Got it working for repo-level runner.
