### ISSUE TITLE
Getting 500 error on webhook lambda

### ISSUE THREAD

**Issue by jgilnom-san** [philips-labs/terraform-aws-github-runner#2015]
Hi all. I'm getting with the version 0.40.2 the error 500 with the following message in the webhook lambda:
TypeError  Cannot read property 'full_name' of undefined

but when I go to the github app I see the full_name value correctly:

      "full_name": "xxxxx/aws-repo",

What could be the problem?

My tf code looks like:
```
module "github-runner" {
  source  = "philips-labs/github-runner/aws"
  version = "v0.40.2"

  aws_region = var.aws_region
  vpc_id     = data.terraform_remote_state.vpc.outputs.vpc.vpc_id
  subnet_ids = local.runners_subnets

  environment = var.environment

  github_app = {
    key_base64     = data.aws_secretsmanager_secret_version.key_base64_version.secret_string
    id             = var.github-runners.github_app_id
    webhook_secret = random_id.random.hex
  }

  webhook_lambda_zip                = module.lambdas.files[0]
  runners_lambda_zip                = module.lambdas.files[1]
  runner_binaries_syncer_lambda_zip = module.lambdas.files[2]
  enable_organization_runners       = true

  instance_types        = var.github-runners.instance_types
  delay_webhook_event   = 5
  runners_maximum_count = 5
  fifo_build_queue      = true
  enable_ssm_on_runners = true
  runner_extra_labels   = "${var.environment},ubuntu,sas"

  pool_runner_owner = "xxxx" 
  pool_config = [{
    size                = 2
    schedule_expression = "cron(* * * * ? *)" 
  }]

  tags = merge(local.required_tags, var.github-runners.tags)
}
```

**Comment by ScottGuymer** [comment]
Is this on the webhook lambda?
Can you post the logs from the lambda to help get an idea of where this is happening?

**Comment by jcamp-revc** [comment]
I'm running into the same issue and just got:
https://gist.github.com/jcamp-revc/d3d4e9643ec76e93276898785c1dd8d7

**Comment by jcamp-revc** [comment]
I'm not sure what the event was, but I think I was looking at the webhook trying to parse some sort of "first-time" webhook registration event. Now that I'm using a repo-level webhook that is properly set up by the README, I'm further along in the process.

fwiw: here is the body of the "first-time" webhook event I get when I register a requestbin style webhook.
`{"zen":"Half measures are as bad as nothing at all.","hook_id":357375334,"hook":{"type":"App","id":357375334,"name":"web","active":true,"events":[],"config":{"content_type":"json","insecure_ssl":"0","url":"https://<redacted>.m.pipedream.net"},"updated_at":"2022-05-09T22:05:49Z","created_at":"2022-05-09T22:05:49Z","app_id":199033,"deliveries_url":"https://api.github.com/app/hook/deliveries"}}`

**Comment by jgilnom-san** [comment]
For some reason, destroying the entire module and recreating all again corrected it. Not sure what was wrong really but working now 😮

**Comment by adamist521** [comment]
おー なんかはじまった

自分でWebhook 登録するのか. selfhosted みたいにRunner登録する感じじゃないのね

![image](https://user-images.githubusercontent.com/2974951/168627705-5afff927-c961-47dc-85c4-703bde06ba7e.png)
