### ISSUE TITLE
Some additional info needs to be added to readme

### ISSUE THREAD

**Issue by theogravity** [philips-labs/terraform-aws-github-runner#203]
I managed to fix the issues I encountered regarding `Resource not accessible by integration` and `Not Found`:

- In the app permissions, also need to do `Repository permissions > Actions > Read-only` (regardless if you're an organization or not)

Also need to add into the terraform file (via https://github.com/philips-labs/terraform-aws-github-runner/issues/104):

```
resource "aws_iam_service_linked_role" "spot" {
  aws_service_name = "spot.amazonaws.com"
}
```

(this is for the `0.5.0` version)

**Comment by npalm** [comment]
Yepz agree, will update the README once we got #212 merged

**Comment by npalm** [comment]
Is already solved
