### ISSUE TITLE
[feature request] match for some labels instead of every label in webhook

### ISSUE THREAD

**Issue by sblack4** [philips-labs/terraform-aws-github-runner#2122]
Right now the github action has to match [EVERY](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every) labels[see this function](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/webhook/lambdas/webhook/src/webhook/handler.ts#L174) which means the github actions need to have all the labels as defined in  `runner_labels` (`"self-hosted,${var.runner_os},${var.runner_architecture},${var.runner_extra_labels}"`)

I would like to have the webhook function match if [some](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) of the labels are present. 

Ideally, there would be a variable I could pass in to change the behavior to accommodate both use cases. Right now I achieve the same effect by manually updating the `RUNNER_LABELS` Environment Variable on the webhook lamda. 

:D

**Comment by lmeynberg** [comment]
That would be a duplicate of this issue https://github.com/philips-labs/terraform-aws-github-runner/issues/1714 but that has been auto-closed by inactivity  as well as https://github.com/philips-labs/terraform-aws-github-runner/issues/1961

🤷

**Comment by sblack4** [comment]
I'm not sure I'm the best namer of variables but here's the implementation: https://github.com/philips-labs/terraform-aws-github-runner/pull/2123
