### ISSUE TITLE
terraform apply work fine and webhook configured but the instance is not creating

### ISSUE THREAD

**Issue by chandradeepcawstudios** [philips-labs/terraform-aws-github-runner#2158]
I have created all the resources using this module and everything works fine but the instance is not created.

Cloudwatch logs of lambda function scale-up show received event but no instance gets registered.
And INFO  Received workflow_job from cawstudios/cypress-blueprint {}.
And logs of lambda function scale-down show No active runners found for the environment: 'ubuntu'.

And no logs are created for the runner, Syslog, and user data.
Is anyone else facing this issue?

**Comment by npalm** [comment]
Maybe the hints in the [README](
<img width="250" alt="image" src="https://user-images.githubusercontent.com/11609620/173754377-011a1e0f-856c-475d-9155-b66151db3903.png">
) are helpfull. 

The webhook should logs `Successfully queued job for ...` and sent a message to SQS. Once the message is on SQS, by default the scale-up lambda should process the message.

**Comment by chandradeepcawstudios** [comment]
> Maybe the hints in the README are helpfull.
> 
> The webhook should logs `Successfully queued job for ...` and sent a message to SQS. Once the message is on SQS, by default the scale-up lambda should process the message.

Scale-up lambda is triggered but it is not processing the job.
In the logs of scale-up, I am getting one info that Received workflow job from my repo is {}.
