### ISSUE TITLE
EC2 instances are not launched

### ISSUE THREAD

**Issue by ArgyrisKefalas2022** [philips-labs/terraform-aws-github-runner#2192]
EC2 instances are not launched and I see in Cloudwatch logs events of the scale up lambda the following warning :   
WARN [scale-runners:39de33c0-3928-5166-8619-68ee553b9454 index.js:113061  Runtime.handler] Ignoring error: [@octokit/auth-app] appId option is required

**Comment by pfnsec** [comment]
How did you resolve this? We're currently hitting this error.

**Comment by ArgyrisKefalas2022** [comment]
hi @pfnsec 
if I remember correct I was setting some terraform inputs as github secrets (and they should be secrets)
but as  it turned out the syntax I was using to input them on terraform was not acceptable,, it was not showing any error, 
but the secrets where not passing..in aws key management the keys had empty value..
I did temporary try to give those secret keys as variables in terraform and then it worked

**Comment by pfnsec** [comment]
For future readers, we had simply mixed up our app ID and client ID :)
