### ISSUE TITLE
Confirmation about how to call those runners from within your workflow since they are not registered yet

### ISSUE THREAD

**Issue by ArgyrisKefalas2022** [philips-labs/terraform-aws-github-runner#2193]
I have a question, the first time you are applying a workflow  and you want to call those self-hosted runners you are doing like this?
```
runs-on: self-hosted
```

even that  at that point of time there are not yet available registered runners in your repo with label "self-hosted",
cause those runners with that label will be registered only after they are launched

Can someone explain please?

**Comment by Hasinibitla2404** [comment]
Hi @ArgyrisKefalas2022 

Did you get the answer for the above question, if so can you please explain me how it is possible?

thanks in Advance!!

**Comment by hasinireddy24** [comment]
Hi @ArgyrisKefalas2022 

Did you get the answer for the above question, if so can you please explain me how it is possible?

Thanks in advance!!

**Comment by ArgyrisKefalas2022** [comment]
Hi @hasinireddy24 , in the workflow I am using the label that I have set in the terraform file,  even that this label is not visible in the in the repo UI as available runners, its working like this

but anyway my issue back then was different, if I remember correct the reason of failure was the authentication key of github app that I was using as input to terraform
