### ISSUE TITLE
http proxy for talking to github URL

### ISSUE THREAD

**Issue by dimitriosstander** [philips-labs/terraform-aws-github-runner#2231]
Hello,

I must use proxy for all outgoing communications - including talking to github.
in gh-auth.ts , I can add to ocktokitOptions something like:
`auth: token,
    request: {
      agent: new HttpsProxyAgent('http://1.2.3.4.5:80'),
    },`

But for createAppAuth that is not possible. I found https://github.com/octokit/auth-app.js/issues/54 but I was unable to get it working. Any suggestions?

Thank you

**Comment by ScottGuymer** [comment]
The good news is that this is already mostly implemented here

https://github.com/philips-labs/terraform-aws-github-runner/pull/1256

We have been struggling to add the required level of testing for it.


Maybe you could help us add that and we can get it merged?

**Comment by dimitriosstander** [comment]
Hello,

I was only able to get https://github.com/philips-labs/terraform-aws-github-runner/blob/4f50689f84815d000e5953987090658da5ade5d9/modules/runners/lambdas/runners/src/gh-auth/gh-auth.ts#L19
working because they had the same issue at https://github.com/semantic-release/github/issues/87. Rewriting the rest of the functions is beyond my current level. I roughly know what needs to be done since I used a similar process in a bash script: get an app private key, generate a token, use that token to register a runner. typescript and the likes I have never worked on before. I thought https://github.com/octokit/auth-app.js/issues/54 would be a direct replacement, but that does not appear to be the case because of the various "Promise" entries. 

So I would be able to submit some broken code, and hope that someone can fix it. At best.
