### ISSUE TITLE
Adding the Pre-requisites for Scaling the Self hosted runner 

### ISSUE THREAD

**Issue by hasinireddy24** [philips-labs/terraform-aws-github-runner#2249]
Hi Team,

We are thinking to implement the Autoscaling for Self Hosted runner. But I have one concern here, for our application settings.xml is required where we add the plugin groups etc. While deploying the application in github actions through self hosted runner it will look for settings.xml file which is in the inside self hosted runner. 

Now if I go for autoscaling how can we add the requried details in each self hosted runner? And also the other Pre-requisites is need to install the Gradle, Maven, Docker, Terraform etc in self hosted runner  before running the workflow. How all this will get managed?

Any suggestions will be really helpfull.

Thanks in advance!

**Comment by npalm** [comment]
This module onluy provide you the framework to setup auto-scaling GitHub runners on AWS. Which means the tools you need, you have to setup yourself. The typical option is to let the job setup the tools, via docker or an setup action. You can also prebuild you own AWS AMI instead of using the default one. And install the required tools. See images directory for some packer examples

**Comment by hasinireddy24** [comment]
Thank you for the information!

I'm trying to download the lambdas through the terraform script and also manually, none of them is not working. I'm getting below error for runner.zip, webhook.zip and runner-binaries-syncer.zip.

Is the download lambdas URL's are working fine? 



 ```
Error: local-exec provisioner error
│
│   with null_resource.download[2],
│   on main.tf line 10, in resource "null_resource" "download":
│   10:   provisioner "local-exec" {
│
│ Error running command 'curl -o runner-binaries-syncer.zip -fL
│ https://github.com/philips-labs/terraform-aws-github-runner/releases/download/v0.11.0/runner-binaries-syncer.zip':
│ exit status 22. Output:   % Total    % Received % Xferd  Average Speed
│ Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
  0     9    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--
│ 0
│ curl: (22) The requested URL returned error: 404



```

**Comment by hasinireddy24** [comment]
@npalm  Thanks for the information!

 I have created an EC2 instance in AWS console and installed all the required tools and took the AMI image from the instance. But when I try to add the ami id in the module "github-runners" in ami_filter variable it is not taking and throwing me the error. 
 
 `Error: Your query returned no results. Please change your search criteria and try again.
│
│  with module.github-runner.module.runners.data.aws_ami.runner,
│  on .terraform/modules/github-runner/modules/runners/main.tf line 42, in data "aws_ami" "runner":
│  42: data "aws_ami" "runner" {
│
╵
Error: Process completed with exit code 1.`

I was able to fetch the ami_id with aws_ami data source. 
Not sure how to get rid of this error, please let me know if anything is wrong.

Thank you!!
