### ISSUE TITLE
│Error: InvalidParameterValue: The filter 'value' is invalid

### ISSUE THREAD

**Issue by hasinireddy24** [philips-labs/terraform-aws-github-runner#2253]
Hi Team,

I have created the AWS EC2 AMI image from the AWS console and I'm trying to use that AMI id in module "github-runner" in the ami_filter field. 

```
ami_filter = { 
    name = ["ami_name"] #aws AMI image name
    value = ["ami-id"] #aws AMI image id
  }
``` 
  
While I'm executing the script I'm getting below error
```
Error: InvalidParameterValue: The filter 'value' is invalid
│	status code: 400, request id: 293b3de3-2036-4206-9e7f-bbe917c79096
│
│  with module.github-runner.module.runners.data.aws_ami.runner,
│  on .terraform/modules/github-runner/modules/runners/main.tf line 42, in data "aws_ami" "runner":
│  42: data "aws_ami" "runner" {

```
I'm using my prebuilt image in the module, Is there anywhere I'm doing wrong?

Any  help is Appreciated, Thanks in Advance!!

**Comment by npalm** [comment]
We have an example of a pre-build image, please check https://github.com/philips-labs/terraform-aws-github-runner/blob/98eff98158381bd57d59e9a54efc3ee5db294110/examples/prebuilt/main.tf#L36
