### ISSUE TITLE
InvalidParameterValueException: Could not unzip uploaded file

### ISSUE THREAD

**Issue by hasinireddy24** [philips-labs/terraform-aws-github-runner#2269]
Hi,

I'm using the module "github-runner_download-lambda" to download the zip files and the tfstatefiles of the zipfiles is stored in s3 bucket.

Now I'm trying to fetch the zip files of "webhook, runner and runner syncer" from the s3 tfstatefile. In the module "github-runner" I have given the lambda_s3_bucket varaible as the bucket is in which I have the zip file tfstate and for webhook_lambda_s3_key syncer_lambda_s3_key, runners_lambda_s3_key variables I have given the zip files tfstate object key. But when I run the script I'm getting the below error.

`Error: error creating Lambda Function (1): InvalidParameterValueException: Could not unzip uploaded file. Please check your file, then try to upload again.
│{
│  RespMetadata: {
│    StatusCode: 400,
│    RequestID: "61e634d4-7ffb-497c-a158-90acb652d4b6"
│  },
│  Message_: "Could not unzip uploaded file. Please check your file, then try to upload again.",
│  Type: "User"
│}
│
│  with module.github-runner.module.runner_binaries.aws_lambda_function.syncer,
│  on .terraform/modules/github-runner/modules/runner-binaries-syncer/runner-binaries-syncer.tf line 10, in resource "aws_lambda_function" "syncer":
│  10: resource "aws_lambda_function" "syncer" {
`
Please let me know where I'm doing wrong. Thanks in Advance!!

**Comment by RobertAlbus** [comment]
Sorry to necro this thread - @hasinireddy24 did you ever manage to resolve this? I am running into it with the zips uploaded to S3
