### ISSUE TITLE
Allow runner-binaries-syncer lambda deployment to be optional

### ISSUE THREAD

**Issue by rashidnhm** [philips-labs/terraform-aws-github-runner#2274]
We are currently using pre-built AMIs for deploying our runners and it is working well. However, as far as I'm aware, if the runner software is pre-baked into the image, then it will not be pulling a fresh version of the github actions software from S3 on boot, but currently even if you have a pre-built AMI, the runner-binaries-syncer module is still deployed, which creates the syncer lambda and the distribution bucket.

I was wondering if a feature could be introduced to disable it? Maybe a new variable? So if you have pre-baked images being produced, no need to create this portion of the infrastructure

**Comment by npalm** [comment]
Making the submodule optional is ineed a good idea.
