### ISSUE TITLE
Config counts all runners created at org level irrespective of how they were created.

### ISSUE THREAD

**Issue by ib-ak** [philips-labs/terraform-aws-github-runner#2289]
I have multiple processes running that creates self hosted runners for an org.
2 instances uses this tf module. third one uses  something totally different.

Actual : Pool config  and/or scale_down option for one module uses total count of all runners running.
Expected: Pool config  and/or scale_down option should only count runners created by the module

**Comment by npalm** [comment]
Thx for reporting, good catch. Needs some investigation.
