### ISSUE TITLE
Configuring Runners for x86 and arm Requires Two GitHub Apps

### ISSUE THREAD

**Issue by bliles** [philips-labs/terraform-aws-github-runner#2326]
This is just a question, it seems like if you need x86 and arm GH runners, you need to setup two GH apps each with their own webhook. Is that correct?

**Comment by npalm** [comment]
Yes that is still a limitation. We are looking for ways to implement the runners in such way you can have one app, one webhook and multiple runner modules. See also https://github.com/philips-labs/terraform-aws-github-runner/discussions/1428

**Comment by bliles** [comment]
Thanks for the quick response! Looks like #1428 covers the feature, I'll close this.
