### ISSUE TITLE
Queued workflow not picked up by AWS runner

### ISSUE THREAD

**Issue by ldormoy** [philips-labs/terraform-aws-github-runner#238]
Hi,

Whenever I trigger a workflow run while there are no running EC2 runner instances, the following happens:

1. Lambda webhook gets the check_run event and queues it to SQS
2. SQS triggers the scale-up Lambda
3. Lambda scale-up starts an EC2 instance
4. EC2 instance properly registers as a self-hosted runner (visible in the GH repository "Actions" settings page
5. The workflow run isn't picked up by the runner and stays in the queue forever, until I cancel it manually

If I trigger another workflow run while the EC2 runner is started, it gets properly picked up and executed.

Any idea what the problem is here?

Thanks!

**Comment by npalm** [comment]
I think it is / was related to this issue, https://github.com/actions/runner/issues/679.

**Comment by woter1832** [comment]
A slightly different problem to OP, but @npalm is referencing #679, which is what I am experiencing. It appears that I have to be running the latest version of the runner to be able to run any pipeline. My runners were running `2.273.4` and worked fine last week, however, today no job would run until I upgraded them to `2.273.5`. 

The jobs were queued with the infamous "starting your workflow run..." message.

T.I.A

**Comment by npalm** [comment]
Still having those issues, our runners our picking jobs as expected

**Comment by ryanoolala** [comment]
I'm facing this issue with the `2.273.5` runners

**Comment by ryanoolala** [comment]
still happening on 2.274.0, did anyone found a workaround for this issue? not sure if its due to the runners anymore.

**Comment by npalm** [comment]
Our workflows are running fine as long we always have an offline runner registered.

**Comment by ryanoolala** [comment]
okay i understand why now, my offline runner was registered at the organisation level, but my account is on the free tier.

For this to work, the offline runners need to be registered on the repository level, since the runner module is installed by repository as well.

**Comment by npalm** [comment]
You can run the runner module on either org or repo level. But not mixed.

**Comment by bumbummen99** [comment]
I am experiencing this on 2.274.2.

I have installed the App to my Org and all its repositories. The runners register as org runners and i also have an offline runner on the repo. The jobs just stay queued and will not be picked up except if they are being queued within the runners lifetime.

@ryanoolala What do you mean by free tier? Did you get this to work?

**Comment by ryanoolala** [comment]
@bumbummen99 free tier meaning i'm running a github org, but i'm not on any billing plans.

I had to register 1 runner for each repository that i want to use the self hosted jobs. The org runner cannot be used, i believe it needs to be on a paid plan to get it to work but i don't have one to test it out. 
Although I only installed the app to the org.

**Comment by npalm** [comment]
You can use runners also on a free org, select your org, next settings and actions

**Comment by bumbummen99** [comment]
> @bumbummen99 free tier meaning i'm running a github org, but i'm not on any billing plans.
> 
> I had to register 1 runner for each repository that i want to use the self hosted jobs. The org runner cannot be used, i believe it needs to be on a paid plan to get it to work but i don't have one to test it out.
> Although I only installed the app to the org.

@ryanoolala That is kinda the scenario i have tougth that i'll have to use the org runner i guess since we have multiple repos that need a more capable runner.

> You can use runners also on a free org, select your org, next settings and actions

@npalm I am not 100% sure on what to configure there but at `Org->Settings->Actions` i have allowed actions for all repositories, all action sources, no fork runs. Group is named `Default Group` and can be used by all (private) repos too - the repo to test this out with is private ofc.

It does pick up the jobs but only if they are queued within the idle lifetime. Is this really related to Org/Repo setup and not the runner? This is exactly what was described on actions/runner#679 but i am on 2.274.2 (i guess, thats the version i found in the files of the s3 runner archive).

**Comment by anupash147** [comment]
Any update on this issue, yeah i see it too??

**Comment by npalm** [comment]
Seems not to be an issue anymore, due to inactivity I close the issue. Feel free to re-open. Thanks for reporting!
