### ISSUE TITLE
Couldn't label runner with labels which contains spaces

### ISSUE THREAD

**Issue by vladget** [philips-labs/terraform-aws-github-runner#2391]
Have an issue with your GitHub action runner deployment.
Labels with spaces in them don't work, looks like something cut the rest of the extra-label string when it finds the first space char.
The environment variable of webhook lambda looks good, but runners are configured with the wrong labels.

Here is what I have in webhook lambda:
```
RUNNER_LABELS | ["self-hosted","linux","x64","test","test2","amazon linux 2"]
```
but in runner I have something like:
```
"self-hosted","linux","x64","test","test2","amazon"
```

Lambda and module version is 1.8.1.

**Comment by npalm** [comment]
Looks like Github does not have a speck of allowed labels. Did you test manually that spaces in labels are working?
