### ISSUE TITLE
Resource Groups are no longer working 

### ISSUE THREAD

**Issue by jake-naughton** [philips-labs/terraform-aws-github-runner#2417]
It looks like after a change went out to update the `Environment` tag to `ghr:environment` that the Resource Group was not updated to match this.

When I navigate to the Resource Group in AWS I cannot see any related infrastructure since the tag query it is using is:
Environment: prefix

If I update this to:
ghr:environment: prefix

It fixes the issue.

**Comment by jake-naughton** [comment]
It should be a simple fix, just need to update the resource-group.json from 

```
{
  "ResourceTypeFilters": ["AWS::AllSupported"],
  "TagFilters": [
    {
      "Key": "Environment",
      "Values": ["${environment}"]
    }
  ]
}
```

to

```
{
  "ResourceTypeFilters": ["AWS::AllSupported"],
  "TagFilters": [
    {
      "Key": "ghr:environment",
      "Values": ["${environment}"]
    }
  ]
}
```

Happy to put up a PR.

**Comment by npalm** [comment]
Good catch, please feel free to create a PR

**Comment by npalm** [comment]
We are not setting a predefined tag to all resources. Which means we cannot create a tag based resource group vai the module. Via the provider you can set a tag to all resources. This means we have to remove the resource group from the module at let it to the user to define a resource group in the deployment.

**Comment by jake-naughton** [comment]
@npalm I have added a PR (#2512) to fix this if you could please review when you get a chance.

**Comment by npalm** [comment]
I have created a PR #2514 to create resource groups for the examples
