### ISSUE TITLE
Cloudwatch configuration does not get applied

### ISSUE THREAD

**Issue by nirlo** [philips-labs/terraform-aws-github-runner#2460]
After following the documentation, the `cloudwatch_config` doesn't seem to do as it says. 

It looks to be similar `runner_log_files`, but since it doesn't take an object, there doesn't seem to an explanation to how this configuration is used as a replacement for direct objects.

Either a more detailed explanation of how the file is created and applied or switching the variable to an object would be beneficial.

**Comment by joaoluiznaufel** [comment]
This is still a issue
