### ISSUE TITLE
runners are not getting registered to github

### ISSUE THREAD

**Issue by Amanraj0007** [philips-labs/terraform-aws-github-runner#2522]
am trying to build an custom ami from images/ubuntu-jammy
ami is getting build successfully..
but not getting registered to github...

**Comment by rlove** [comment]
Look at your cloud watch logs for spin up.    Typically, this occurs when you have GitHub.Base64 encoded value set incorrectly.

**Comment by mshade** [comment]
I think you need to set this to `false`: https://github.com/philips-labs/terraform-aws-github-runner#input_enabled_userdata

The packer templates already pre-install the runner and start the service on boot, so what happens is it tries to start the runner twice and there's a race condition (I believe).
