### ISSUE TITLE
Feature: Fallback to "on-demand" when no spot capacity available

### ISSUE THREAD

**Issue by foxylion** [philips-labs/terraform-aws-github-runner#2566]
We recently ran into a capacity issues for certain instance types. The default configuration is to use Spot instances.
This is great and cost efficient, but in case there is no spot capacity available I would like to fallback on "on-demand" instances.
Because otherwise the ephemeral runners will fail to execute the scheduled job.

It could be a new option for `instance_target_capacity_type` named `prefer-spot` that would create on-demand instances, when the spot request failed.

This was already suggested in https://github.com/philips-labs/terraform-aws-github-runner/issues/1744 but was closed as stale.

**Comment by npalm** [comment]
The AWS API does not support this, which mean it need to be tailored. For example by catching an exception and creating in a retry an on-demand instance. We create on a day over 10K of instances spread 3 zones and have rarely an issue with spot. But that can all depend on the region and type of instances as weel. We also have added to the option an more expensive instance as backup and select based on best price

**Comment by foxylion** [comment]
As we are using ephemeral runners every hiccup in scheduling instances meaning a hanging or failed build we try to prevent any issues with scheduling instances.

We rely on `t3a.xlarge` instances in `eu-central-1` (in all AZs). We start ~700 instances within 1:30 hours every morning. At the end (when Germany starts their working day) we start seeing errors due to missing spot capacity. I might try adding similar instances as fallback.

> For example by catching an exception and creating in a retry an on-demand instance.

Exactly what I thought. :-)

**Comment by npalm** [comment]
Would you have time to dig in and propose a PR?

**Comment by dgokcin** [comment]
I am also looking forward for this feature. Although I have multiple runners with multiple instance types enabled with spot instances, if there is no spot capacity, the github action just hangs. Any workaround that you come up with @foxylion

**Comment by dgokcin** [comment]
And also for my case, I do not mind using a different instance type that I specified in my configuration. With the following configuration, if there is no spot capacity available with m5n.4xlarge, I expected the scale up lambda to try also for 8xlarge but I believe that is not the current behaviour. Am I missing anything? @npalm 

![image](https://user-images.githubusercontent.com/33603535/220421434-8d75cde9-c2ab-4296-93c7-04b3c12fb9e1.png)

**Comment by npalm** [comment]
Available since release https://github.com/philips-labs/terraform-aws-github-runner/releases/tag/v5.5.0
