### ISSUE TITLE
Fetch binary from github directly

### ISSUE THREAD

**Issue by pdeveltere** [philips-labs/terraform-aws-github-runner#2593]
Instead of having this binary sync logic, you could just fetch the binary directly from github?

in the `install-runner.sh` script you can have:
```
# the following command automatically downloads the latest github actions binary
curl -s https://api.github.com/repos/actions/runner/releases/latest | grep -o -m 1 "https:\/\/github\.com\/actions\/runner\/releases\/download\/v[0-9\.]*\/actions-runner-linux-x64-[0-9\.]*\.tar\.gz" | wget -O actions-runner-linux-x64.tar.gz -qi -
echo "Un-tar action runner"
tar xzf ./actions-runner-linux-x64.tar.gz
echo "Delete tar file"
rm -rf actions-runner-linux-x64.tar.gz
```

In our company, we forked this repository, removed all the binary sync logic, and implemented it this way to reduce complexity and costs, and it works like a charm. But I thought it can perhaps be implemented here as well? That way we could just use this module 🙏🏽

**Comment by npalm** [comment]
We started with this back in the days, but once we start scaling out we found out that the download via GitHub can be slow. Adding a minute or more to the boot time of the runners. Therefore we have introduced the binary cache lambda, and agree it is adding complexity. Today we don't use the binary lambda anymore (it can be disabled). And we pre-built AMI's containting the full install.

**Comment by npalm** [comment]
I would say we keep for now the binary syncer in place, checked last week the times in the AMI builds and still can take up to 15 seconds to fetch the GH binary. this keeps the module as peformanend as possible without having custom AMI.
