### ISSUE TITLE
Retry scaling up when fleet request fails with `InsufficientInstanceCapacity`

### ISSUE THREAD

**Issue by hatf0** [philips-labs/terraform-aws-github-runner#2612]
Hi. We currently use this to provision high-performance compute for CI jobs, and a frequent problem we run into is that the scale-up runner will fail (silently) due to insufficient AWS capacity (especially for runners of an instance type of `c6a.16xlarge` or bigger). This failure is typically transitory and is resolved by just retrying once or twice -- so it should be fairly trivial to just bake in some basic exponential retry logic into the scale-up lambda function, and fail after a given number of tries. 

Additionally, would it be possible to mark the job as a failure if there's an error in the scale-up lambda function? Currently, when the scale-up function fails, the job is left "pending" and leads to some developer confusion, so if it could just fail the job entirely, that would be much better. I'm not too familiar with the GitHub API, though, so do let me know if this would be possible.

**Comment by npalm** [comment]
For ephemeral runners the lambda scale-up uses a list of predefined errors which leads to an auto retry. The errors in the list are marked as errors valid for a retry, and the messages is put back to the queue.

https://github.com/philips-labs/terraform-aws-github-runner/blob/37149afa4ca5a3f3daf1caa5589764d8d6912390/modules/runners/lambdas/runners/src/aws/runners.ts#L216-L223

I agree that the error `InsufficientInstanceCapacity` seems a valid error for retry. Would you like to propose a change in a PR?

**Comment by npalm** [comment]
AWS reference https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html
