### ISSUE TITLE
[Feature Request] Ability to run a multi-arch docker buildx with a pair of EC2 instances.

### ISSUE THREAD

**Issue by dmarkey** [philips-labs/terraform-aws-github-runner#2638]
Hey,

Thanks for the work on this project.

One thing that would be nice is the ability to bring up "paired" workers of different architectures for a build of a project without the need to emulate the CPU with qemu(hella slow) for a `docker buildx --platform linux/arm64,linux/amd64 --push ...`

For a "multiarch" build a pair of EC2 instances would have to be bought up and both docker instances would have to be registered with docker buildx  for the duration of the build.

Thanks!

David

**Comment by npalm** [comment]
See #2472 and #2517 would that work for you?

**Comment by dmarkey** [comment]
The problem i see is that the 2 EC2 instances (one amd64 and one arm64) need to be aware of each other in order for docker buildx to be able to direct the architecture specific build to the correct EC2 instance. It there that kind of metadata available within the EC2 instances?
