### ISSUE TITLE
Is it possible to run this module over two different VPC׳s?

### ISSUE THREAD

**Issue by dvdgitman** [philips-labs/terraform-aws-github-runner#2703]
I have this module already running perfectly using the stage vpc , is it possible to add another VPC to the module? I would like to run the runners on prod VPC as well..

**Comment by npalm** [comment]
Not possible, this requires two deployments.

**Comment by dvdgitman** [comment]
How do I deploy the terraform again? Since it's gonna use the same modules and roles it's probably gonna say some stuff are already in use with same name no?

**Comment by dvdgitman** [comment]
Bump, how do I redeploy the tf module, if I already have it installed and configured on my Account with a specific VPC, and I want to add another one.. I think it will failed since it has the same name already

**Comment by dvdgitman** [comment]
> Not possible, this requires two deployments.

bump, can you tell me how do I add another deployment ? Since If i would run it again it will ( same modules and roles )

**Comment by npalm** [comment]
There is a prefix variable, when you set this all names should be unique. You can also have on Issue  #2517 which tracks the work for v2.x to support in a simplere way.

**Comment by dvdgitman** [comment]
> prefix variable,

Hey! thanks for the reply, does it also set the lamb functions a different name as well?
