### ISSUE TITLE
[multi-runner] - Add support for multiple label arrays to matcher

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#2715]
Currently a multi runner is implement, see next branch (#2517 ) The configuration supports matching based on a single array of labels.

```
      matcherConfig : {
        labelMatchers = ["self-hosted", "linux", "x64", "ubuntu-latest"]
        exactMatch    = true
      }
```

But it will give a bit more flexicility to also allow to match on multiple arrays of runner labels like:

```
      matcherConfig : {
        labelMatchers = [["self-hosted", "linux", "x64", "ubuntu-latest"], ["self-hosted", "linux", "x64", "ubuntu-2204"]]
        exactMatch    = true
      }
```

**Comment by mariusfilipowski** [comment]
Looks like this feature is already available, right?

**Comment by npalm** [comment]
yup, so closing. Thanks @mariusfilipowski
