### ISSUE TITLE
Issue with 1.17.0 when upgrading

### ISSUE THREAD

**Issue by jkritzen** [philips-labs/terraform-aws-github-runner#2732]
If we upgrade to 1.17.0 we get the following error:

**Error**: error modifying Lambda Function (atc-cgbp-syncer) configuration : InvalidParameterValueException: The provided execution role does not have permissions to call CreateNetworkInterface on EC2

Is there anything missing?

**Comment by jkritzen** [comment]
Is seems a issue within the module, we do not use custom roles in the deployment.

The full error message:

module.github-runner.module.runner_binaries[0].aws_lambda_function.syncer: Still modifying... [id=atc-cgbp-syncer, 4m50s elapsed]
╷
│Error: error modifying Lambda Function (atc-cgbp-syncer) configuration : InvalidParameterValueException: The provided execution role does not have permissions to call CreateNetworkInterface on EC2
│{
│  RespMetadata: {
│    StatusCode: 400,
│    RequestID: "44d753f7-a90e-4ce4-8eed-3c93a4406fa0"
│  },
│  Message_: "The provided execution role does not have permissions to call CreateNetworkInterface on EC2",
│  Type: "User"
│}
│
│  with module.github-runner.module.runner_binaries[0].aws_lambda_function.syncer,
│  on .terraform/modules/github-runner/modules/runner-binaries-syncer/runner-binaries-syncer.tf line 10, in resource "aws_lambda_function" "syncer":
│  10: resource "aws_lambda_function" "syncer" {
│
╵

**Comment by npalm** [comment]
Frow which version to which version are you upgrading?

**Comment by GuptaNavdeep1983** [comment]
@jkritzen , the error is quite confusing. Based on the error message, its not clear why lambda function would try to create ec2 network interface but regardless, can you check if these permissions (ec2:CreateNetworkInterface) are missing to the role which is used to execute this terraform code?

**Comment by GuptaNavdeep1983** [comment]
@jkritzen, this issue has been addressed as per latest release v1.18.0, can you please check and revert.

**Comment by GuptaNavdeep1983** [comment]
solved, feel free to re-open if any need

**Comment by jkritzen** [comment]
@GuptaNavdeep1983 : Thanks for fixing, with v.1.18.0 it works as expected:
![image](https://user-images.githubusercontent.com/43033899/207058783-bcd594ac-c243-468a-81b2-5862f7fd066b.png)
