### ISSUE TITLE
No instance are being created.

### ISSUE THREAD

**Issue by AayushbajajCAW** [philips-labs/terraform-aws-github-runner#2745]
### Discussed in https://github.com/philips-labs/terraform-aws-github-runner/discussions/2738

<div type='discussions-op-text'>

<sup>Originally posted by **AayushbajajCAW** December  9, 2022</sup>
I have been trying to test and implement self hosted runners but the issue is that instances are turning on even after everything is connected. I have followed every step github apps and everything but still the instances are not turning up. Cloudwatch registers the request but for some reason the request to create instances are not working. I have attached the main.tf file clould anyone please help in sorting this issue out.
 The main.tf file

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.44.0"
    }
  }
}

provider "aws" {
  region     = var.aws_region
  access_key = "access_key"
  secret_key = "secret_key"
}

data "aws_caller_identity" "current" {}

resource "random_id" "random" {
  byte_length = 20
}
resource "aws_iam_service_linked_role" "spot" {
  aws_service_name = "spot.amazonaws.com"
}
module "github-runner" {
  create_service_linked_role_spot = true
  source  = "philips-labs/github-runner/aws"
  version = "2.0.0-next.1"

  aws_region = var.aws_region
  vpc_id     = module.vpc.vpc_id
  subnet_ids = module.vpc.private_subnets

  prefix = var.prefix

  github_app = {
    key_base64     = "key"
    id = "id"
    webhook_secret = random_id.random.hex
  }

  webhook_lambda_zip                = "lambdas-download/webhook.zip"
  runner_binaries_syncer_lambda_zip = "lambdas-download/runner-binaries-syncer.zip"
  runners_lambda_zip                = "lambdas-download/runners.zip"
  enable_organization_runners = true
  runner_extra_labels         = "default,example"


  # enable access to the runners via SSM
  enable_ssm_on_runners = true

  instance_types = ["m5.large", "c5.large"]
  # Uncomment to enable ephemeral runners
  runner_run_as = "ubuntu"
  enable_ephemeral_runners = false
  # enabled_userdata         = true
  delay_webhook_event      = 0
  runners_maximum_count = 20

  idle_config = [{
    cron      = "* * o-23 * * *"
    timeZone  = "Europe/Amsterdam"
    idleCount = 3
  }]


  # fifo_build_queue = true
  enable_job_queued_check = true
  # override scaling down
  scale_down_schedule_expression = "cron(* * * * ? *)"
}
```
Could anyone point to what i am doing worng it would be great help thanks in advnace</div>

**Comment by npalm** [comment]
I hope this section in the [readme](https://github.com/philips-labs/terraform-aws-github-runner#debugging) can help you to drill down the problem.

**Comment by timothyclarke** [comment]
@npalm Im getting similar. In the cloudwatch scale-up log I'm seeing `index.js:120511 Runtime.handler] Ignoring error: error:0908F066:PEM routines:get_header_and_data:bad end line {"runnerType":"Org"` would that be related ?
