### ISSUE TITLE
[Feature Request] Add possibility to give a nice domain name to the webhook api

### ISSUE THREAD

**Issue by mvanbaak** [philips-labs/terraform-aws-github-runner#2762]
So you can use eg `https://builds.company.com` as webhook endpoint instead of the aws generated api gateway url

**Comment by npalm** [comment]
A good idea. But I think we should limit the module to support this by outputting the required information from the API gateway. And leave it to the user to bind a nice domain name (via Route53 e.g.)

**Comment by mvanbaak** [comment]
Yeah, if the needed info is available one could use it in their own module.
Agreed.

**Comment by M1kep** [comment]
@mvanbaak I believe the module outputs already contain the relevant fields to support this. See line 33 https://github.com/philips-labs/terraform-aws-github-runner/blob/main/outputs.tf

**Comment by mvanbaak** [comment]
> @mvanbaak I believe the module outputs already contain the relevant fields to support this. See line 33 https://github.com/philips-labs/terraform-aws-github-runner/blob/main/outputs.tf

You are completely correct.
Since I first posted this FR, I have been using terraform 'in production' for the first time, and got some more experience with it. So excuse me that I did not see it back in Dec.

Closing the issue as everything I need is there.
