### ISSUE TITLE
The event does match the configured labels

### ISSUE THREAD

**Issue by timothyclarke** [philips-labs/terraform-aws-github-runner#2766]
I'm using the lambdas provided by release v1.18.0 on this repo. I don't think the environment is being parsed correctly

I am receiving the following
```
<timestamp>	<UUID>	DEBUG	Received workflow job event with labels: '["self-hosted","test-runner"]'. The event does  match the configured labels: '{}'
```
I've tried setting `runner_extra_labels` to various values and when I look at the lambda environment I am seeing 
`RUNNER_LABELS   ["self-hosted","linux","x64","test-runner","sandbox"]` so I think the terraform side of it is working.
I'm also seeing `LOG_LEVEL info` but per above I'm seeing debug logs in cloudwatch. If I set a value in `REPOSITORY_WHITE_LIST` that seems filter correctly (as in if the repo is not in the list it will not run the job)

**Comment by npalm** [comment]
You can disable label checks, or check them partial. See

- https://github.com/philips-labs/terraform-aws-github-runner#input_runner_enable_workflow_job_labels_check_all
- https://github.com/philips-labs/terraform-aws-github-runner#input_runner_enable_workflow_job_labels_check

**Comment by timothyclarke** [comment]
@npalm Thanks, however I want it to be available to multiple repo's, and only for workflows with appropriate labels to use it. 
The core issue here is why the lambda logs `configured labels: '{}'` rather than a much longer list eg the one that it's being passed via an environmental variable

**Comment by timothyclarke** [comment]
Closing, I must have pulled the wrong artefacts I've recompiled them locally and it works. https://github.com/philips-labs/terraform-aws-github-runner/blame/v1.18.0/modules/webhook/README.md#L11 says Node 12 is required however when I first tried to compile it required atleast Node 14

With `runner_enable_workflow_job_labels_check = true` and `runner_enable_workflow_job_labels_check_all = false` my expectation would be that a match of any label would cause a run
The variables `runner_enable_workflow_job_labels_check` and `runner_enable_workflow_job_labels_check_all` are confusing and the documentation isn't all that clear. I think  `runner_enable_workflow_job_labels_check`  enables label checking, with `runner_enable_workflow_job_labels_check_all` toggling a match any / match all. A single variable with `["disable", "any", "all"]` options would be less confusing.
