### ISSUE TITLE
Request Limit Exceeded?

### ISSUE THREAD

**Issue by nomeelnoj** [philips-labs/terraform-aws-github-runner#278]
Seeing runners fail to delete.  The underlying AWS instances get purged with "orphaned runner deleted" log messages, but for some reason we are getting rate limited somewhere (I think in AWS) and then the Github runners never get removed.

If we wait long enough, we have seen as many as 800 offline runners...

Here are some relevant lambda logs from the scale down lambda:

```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "RequestLimitExceeded: Request limit exceeded.",
    "reason": {
        "errorType": "RequestLimitExceeded",
        "errorMessage": "Request limit exceeded.",
        "code": "RequestLimitExceeded",
        "message": "Request limit exceeded.",
        "time": "2020-10-19T12:00:12.277Z",
        "requestId": "eb9ecb84-5f5a-4317-974b-10371c2df8f7",
        "statusCode": 503,
        "retryable": true,
        "stack": [
            "RequestLimitExceeded: Request limit exceeded.",
            "    at Request.extractError (/var/task/index.js:40075:35)",
            "    at Request.callListeners (/var/task/index.js:46386:20)",
            "    at Request.emit (/var/task/index.js:46358:10)",
            "    at Request.emit (/var/task/index.js:17843:14)",
            "    at Request.transition (/var/task/index.js:17177:10)",
            "    at AcceptorStateMachine.runTo (/var/task/index.js:25384:12)",
            "    at /var/task/index.js:25396:10",
            "    at Request.<anonymous> (/var/task/index.js:17193:9)",
            "    at Request.<anonymous> (/var/task/index.js:17845:12)",
            "    at Request.callListeners (/var/task/index.js:46396:18)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: RequestLimitExceeded: Request limit exceeded.",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:315:20)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}


[ERROR] [1603108812400] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403. | [ERROR] [1603108812400] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 403.
-- | --

```

Any ideas what could be going on here?  Thanks in advance for your help!

**Comment by npalm** [comment]
We having similar issues, not with 800. We still figuring out the cause. But in case the the spot request fails, a runner is crated in github and not in AWS wich will certainly lead to an offline runner.

**Comment by sjagoe** [comment]
I never took the time to look into the cause, but we "solved" this in the meantime with a cron job that removes offline runners from github with the github API using something like

```
for runner_id in $(
    gh api --paginate orgs/smartlyio/actions/runners |
        jq '.runners[] | select(.status == "offline") | select(.name != "aws-dummy-runner") | .id'
); then
    gh api -XDELETE "orgs/smartlyio/actions/runners/${runner_id}"
fi
```

(gh is the cli from https://github.com/cli/cli)
`aws-dummy-runner` is a offline runner we keep around just to ensure the labels we distribute jobs on exist.

We haven't been using spot instances due to a period of early spot termination that caused many builds to fail. My suspicion is that we got caught by #227 which caused the build-up of runners, and then termination of "orphan" runners.

**Comment by nomeelnoj** [comment]
We are doing the same thing, but with a go binary that queries the GitHub api for any offline runner and removes it.  It is fast, and a sufficient workaround at this time, but not ideal.  Any updates here as to why we keep getting so many offline runners?

**Comment by jpalomaki** [comment]
@npalm Does this bit of [code](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts#L75) cache the list of GH runners? If so, how do items get evicted from the cache (which seems to be keyed by org/repo)?

**Comment by sjagoe** [comment]
That looks like it's caching github API client instances by organization (when using org-level runners) or repository (using repo-level runners). I think in that case cache eviction shouldn't be an issue; it's not keeping any runner state in the cache, just potentially keeping reusable connections to the github API.

**Comment by npalm** [comment]
Seems not to be an issue anymore, due to inactivity I close the issue. Feel free to re-open. Thanks for reporting!
