### ISSUE TITLE
runner not getting registered to GitHub

### ISSUE THREAD

**Issue by atiffarrukh** [philips-labs/terraform-aws-github-runner#2783]
I am using the following to create spot instance runners. The runners are being created whenever GitHub triggers a workflow, but they are not being registered to GitHub.
```
module "runners" {
  source     = "philips-labs/github-runner/aws"
  version    = "v1.18.0"
  aws_region = local.aws_region


  vpc_id           = data.terraform_remote_state.common.outputs.vpcs.euc1.id
  subnet_ids       = [data.terraform_remote_state.common.outputs.git_runners_subnet.private.a, data.terraform_remote_state.common.outputs.git_runners_subnet.private.b]

  github_app = {
    # key_base64     = var.github_app_key_base64
    key_base64     = base64encode(file("app.private-key.pem"))
    id             = var.github_app_id
    webhook_secret = random_id.random.hex
  }

  # Grab the lambda packages from local directory. Must run /.ci/build.sh first
  webhook_lambda_zip                = "download-lambda/webhook.zip"
  runner_binaries_syncer_lambda_zip = "download-lambda/runner-binaries-syncer.zip"
  runners_lambda_zip                = "download-lambda/runners.zip"

  enable_organization_runners = true
  runner_extra_labels         = "spaceos_runners"

  # enable workflow labels check
  runner_enable_workflow_job_labels_check = true

  # enable access to the runners via SSM
  enable_ssm_on_runners = true

  instance_types = ["m5.large", "c5.large"]

  # override delay of events in seconds
  delay_webhook_event = 0

  # Ensure you set the number not too low, each build require a new instance
  runners_maximum_count = 20

  # override scaling down
  scale_down_schedule_expression = "cron(* * * * ? *)"

  enable_ephemeral_runners = true

  enable_job_queued_check = true

  # Enable logging
  log_level = "debug"

}
```
**Logs**
/aws/lambda/github-actions-syncer
```
2022-12-21 06:35:21.070  INFO  [runner-binaries-syncer:f4bd0d5e-9701-4dba-988e-06d9776ea440 index.js:51083 undefined.<anonymous>] The new distribution is uploaded to S3.
--
END RequestId: f4bd0d5e-9701-4dba-988e-06d9776ea440
```
/aws/lambda/github-actions-webhook
```
2022-12-21 07:04:49.267  DEBUG [webhook:3c905eb5-8fe4-4f40-bbb6-cdf51ceddf93 index.js:91589  sendActionRequest] sending message to SQS: 
{
    "QueueUrl": "https://sqs.eu-central-1.amazonaws.com/751301696254/github-actions-queued-builds",
    "MessageBody": "{\"id\":10225047260,\"repositoryName\":\"self-host-runner\",\"repositoryOwner\":\"SpaceOSLtd\",\"eventType\":\"workflow_job\",\"installationId\":32358068}"
}
 
{
    "event": "workflow_job",
    "repository": "SpaceOSLtd/self-host-runner",
    "action": "queued",
    "name": "Explore-GitHub-Actions",
    "status": "queued",
    "workflowJobId": 10225047260,
    "started_at": "2022-12-21T07:04:44Z",
    "completed_at": null,
    "conclusion": null
}
 
2022-12-21 07:04:49.647  INFO  [webhook:3c905eb5-8fe4-4f40-bbb6-cdf51ceddf93 index.js:91759  handleWorkflowJob] Successfully queued job for SpaceOSLtd/self-host-runner 
{
    "event": "workflow_job",
    "repository": "SpaceOSLtd/self-host-runner",
    "action": "queued",
    "name": "Explore-GitHub-Actions",
    "status": "queued",
    "workflowJobId": 10225047260,
    "started_at": "2022-12-21T07:04:44Z",
    "completed_at": null,
    "conclusion": null
}
```
github-self-hosted-runners/github-actions/runner; /github-self-hosted-runners/github-actions/user_data;/github-self-hosted-runners/github-actions/runner-startup all are empty.

**Comment by npalm** [comment]
I hope this section in the [readme](https://github.com/philips-labs/terraform-aws-github-runner#debugging) can help you to drill down the problem.

See also #2745 Feel free to improve the docs when you have resolved the problem.

**Comment by atiffarrukh** [comment]
@npalm, here are logs,
The instance is created
```
2022-12-21 07:27:37.059  INFO  [runners:58e2ff9b-d17c-5a14-a169-a38766eb1210 index.js:120388  createRunner] Created instance(s):  i-01682d4128cd414a2 
{
    "runnerType": "Org",
    "runnerOwner": "SpaceOSLtd",
    "event": "workflow_job",
    "id": "10225354755"
}
```
the job is queued
```
2022-12-21 07:27:32.482  INFO  [webhook:d3ea3daf-d41f-4708-849f-acdaabb36699 index.js:91759  handleWorkflowJob] Successfully queued job for SpaceOSLtd/self-host-runner 
{
    "event": "workflow_job",
    "repository": "SpaceOSLtd/self-host-runner",
    "action": "queued",
    "name": "Explore-GitHub-Actions",
    "status": "queued",
    "workflowJobId": 10225354755,
    "started_at": "2022-12-21T07:27:27Z",
    "completed_at": null,
    "conclusion": null
}
```
I cannot SSM in to the VM
<img width="811" alt="image" src="https://user-images.githubusercontent.com/1938333/208846454-daccb1a4-b244-4a21-85b4-357669cc03df.png">

It seems like SSM Agent and runners agent is not being installed. The logs are empty for `/github-self-hosted-runners/github-actions/runner`

They private seems to be fine
```
openssl rsa -in app.private-key.pem -check
RSA key ok
writing RSA key
<redacted>
```

**Comment by dvdgitman** [comment]
> @npalm, here are logs, The instance is created
> 
> ```
> 2022-12-21 07:27:37.059  INFO  [runners:58e2ff9b-d17c-5a14-a169-a38766eb1210 index.js:120388  createRunner] Created instance(s):  i-01682d4128cd414a2 
> {
>     "runnerType": "Org",
>     "runnerOwner": "SpaceOSLtd",
>     "event": "workflow_job",
>     "id": "10225354755"
> }
> ```
> 
> the job is queued
> 
> ```
> 2022-12-21 07:27:32.482  INFO  [webhook:d3ea3daf-d41f-4708-849f-acdaabb36699 index.js:91759  handleWorkflowJob] Successfully queued job for SpaceOSLtd/self-host-runner 
> {
>     "event": "workflow_job",
>     "repository": "SpaceOSLtd/self-host-runner",
>     "action": "queued",
>     "name": "Explore-GitHub-Actions",
>     "status": "queued",
>     "workflowJobId": 10225354755,
>     "started_at": "2022-12-21T07:27:27Z",
>     "completed_at": null,
>     "conclusion": null
> }
> ```
> 
> I cannot SSM in to the VM <img alt="image" width="811" src="https://user-images.githubusercontent.com/1938333/208846454-daccb1a4-b244-4a21-85b4-357669cc03df.png">
> 
> It seems like SSM Agent and runners agent is not being installed. The logs are empty for `/github-self-hosted-runners/github-actions/runner`
> 
> They private seems to be fine
> 
> ```
> openssl rsa -in app.private-key.pem -check
> RSA key ok
> writing RSA key
> <redacted>
> ```

I was having the same issue - still have but what I did to get logs was to create a EC2 machine template from the launch templates menu , give it elastic IP for Public IP and open 22 ports for SSH access. Once the EC2 launched Ive accessed 
the /var/log/user-data.log.

Let me know what issue you are getting, because for me it says:
![image](https://user-images.githubusercontent.com/5166585/209440773-1c0518b1-79ea-4e80-9c65-dc9ccfab695b.png)

Haven't found a solution yet

**Comment by atiffarrukh** [comment]
@dvdgitman , this is what I am getting
```
cat /var/log/user-data.log
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: amzn2-core/2/x86_64
Could not retrieve mirrorlist https://amazonlinux-2-repos-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com/2/core/latest/x86_64/mirror.list error was
12: Timeout on https://amazonlinux-2-repos-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com/2/core/latest/x86_64/mirror.list: (28, 'Failed to connect to amazonlinux-2-repos-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com port 443 after 2701 ms: Connection timed out')
```

**Comment by dvdgitman** [comment]
> @dvdgitman , this is what I am getting
> 
> ```
> cat /var/log/user-data.log
> Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
> 
> 
>  One of the configured repositories failed (Unknown),
>  and yum doesn't have enough cached data to continue. At this point the only
>  safe thing yum can do is fail. There are a few ways to work "fix" this:
> 
>      1. Contact the upstream for the repository and get them to fix the problem.
> 
>      2. Reconfigure the baseurl/etc. for the repository, to point to a working
>         upstream. This is most often useful if you are using a newer
>         distribution release than is supported by the repository (and the
>         packages for the previous distribution release still work).
> 
>      3. Run the command with the repository temporarily disabled
>             yum --disablerepo=<repoid> ...
> 
>      4. Disable the repository permanently, so yum won't use it by default. Yum
>         will then just ignore the repository until you permanently enable it
>         again or use --enablerepo for temporary usage:
> 
>             yum-config-manager --disable <repoid>
>         or
>             subscription-manager repos --disable=<repoid>
> 
>      5. Configure the failing repository to be skipped, if it is unavailable.
>         Note that yum will try to contact the repo. when it runs most commands,
>         so will have to try and fail each time (and thus. yum will be be much
>         slower). If it is a very temporary problem though, this is often a nice
>         compromise:
> 
>             yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
> 
> Cannot find a valid baseurl for repo: amzn2-core/2/x86_64
> Could not retrieve mirrorlist https://amazonlinux-2-repos-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com/2/core/latest/x86_64/mirror.list error was
> 12: Timeout on https://amazonlinux-2-repos-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com/2/core/latest/x86_64/mirror.list: (28, 'Failed to connect to amazonlinux-2-repos-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com port 443 after 2701 ms: Connection timed out')
> ```

Hey man! I had the same issue, in the end it was a subnet issue.
I had VPC endpoint which was pointing to a specific subnet that I should have made for the runner as well.
The issue was the runner wasnt getting network  for it to update YUM.
Hope this help! Happy new year

**Comment by atiffarrukh** [comment]
@dvdgitman, thanks, it did solve the issue. :)
