### ISSUE TITLE
How can I have different type of runners?

### ISSUE THREAD

**Issue by ay0o** [philips-labs/terraform-aws-github-runner#2788]
Does this module support different type of runners?

I mean, it's possible to set various `instance_types`, but they all apply to the same configuration.
Is it possible to have different groups of configurations such as, for example:

- label: self-hosted-ephemeral, instance_types: t4g.large, pool of 5
- label: self-hosted-compute, instance_types: c6i.xlarge

What would be the approach to have this config? `init` twice the module with different backends, hence, duplicating all the resources?

**Comment by IdanYaffe** [comment]
It is, but it is still a preview version.
checkout this release: 
https://github.com/philips-labs/terraform-aws-github-runner/releases/tag/v2.0.0-next.7

here's an example for how you can set it up:
`module "github-runners" {
  source  = "philips-labs/github-runner/aws//modules/multi-runner"
  version = "2.0.0-next.1"

  # Setup acts on webhook events from a github application
  github_app = {
    key_base64     = var.github_app_key_base64
    id             = var.github_app_id
    webhook_secret = random_id.random.hex
  }

  aws_region                        = local.aws_region
  vpc_id                            = local.vpc_id
  subnet_ids                        = local.subnet_ids
  runners_scale_up_lambda_timeout   = 60
  runners_scale_down_lambda_timeout = 60
  prefix                            = local.environment
  tags = {
    Environment = local.environment
  }
  webhook_lambda_zip                = "lambdas/webhook-2.0.0-next.1.zip"
  runner_binaries_syncer_lambda_zip = "lambdas/runner-binaries-syncer-2.0.0-next.1.zip"
  runners_lambda_zip                = "lambdas/runners-2.0.0-next.1.zip"

  # the actual runners using the information from above
  multi_runner_config = {
    "linux-arm64" = {
      matcherConfig : {
        labelMatchers     = ["self-hosted", "linux", "arm64"]
        exactMatch        = true
      }
      fifo                = true
      delay_webhook_event = 0
      redrive_build_queue = {
        enabled         = true
        maxReceiveCount = 10
      }
      enable_organization_runners       = true
      runner_config = {
        runner_os                       = "linux"
        runner_architecture             = "arm64"
        enable_ssm_on_runners           = true
        create_service_linked_role_spot = true
        instance_types                  = ["t4g.large", "c6g.large"]
        runners_maximum_count           = 5
        scale_down_schedule_expression  = "cron(* * * * ? *)"
      }
    },
    "linux-amd64" = {
      matcherConfig : {
        labelMatchers = ["self-hosted", "linux", "amd64"]
        exactMatch    = true
      }
      fifo                = true
      delay_webhook_event = 0
      redrive_build_queue = {
        enabled         = true
        maxReceiveCount = 10
      }
      enable_organization_runners       = true
      runner_config = {
        runner_os                       = "linux"
        runner_architecture             = "x64"
        enable_ssm_on_runners           = true
        create_service_linked_role_spot = true
        instance_types                  = ["t3a.large", "c6a.large"]
        runners_maximum_count           = 5
        scale_down_schedule_expression  = "cron(* * * * ? *)"
      }
    },
  }
}`
