### ISSUE TITLE
`v2.0.0` Release Missing Some Of the Included Notes

### ISSUE THREAD

**Issue by Kyrluckechuck** [philips-labs/terraform-aws-github-runner#2822]
In the release notes for https://github.com/philips-labs/terraform-aws-github-runner/releases/tag/v2.0.0, it indicates that https://github.com/philips-labs/terraform-aws-github-runner/pull/2809 should have been included in the `v2.0.0` tag / release. 

I can see it was merged into `next`, but from what I can tell it's not actually in the `v2.0.0` release, and it makes me worry that there may have been other commits that were accidentally dropped, too? Worst case this is just an error report for the below two variables/PR 2809:

For example, if you check out this tag and search the repo looking for `enable_fifo_build_queue` or `enable_runner_workflow_job_labels_check_all` do not show any results.

**Comment by npalm** [comment]
will check tomorrow

**Comment by npalm** [comment]
Quick check, and I think something went wrong indeed with this PR. Other changes are fine. Will apply a fix tomorrow. Thanks for the notice

**Comment by npalm** [comment]
@Kyrluckechuck can you have a quick look on PR https://github.com/philips-labs/terraform-aws-github-runner/issues/2822 ?
