### ISSUE TITLE
Question regarding new multi runner sample

### ISSUE THREAD

**Issue by mariusfilipowski** [philips-labs/terraform-aws-github-runner#2845]
I am currently trying to understand the multirunner example and I am wondering why this extra-label has been specified. I expected `amazon` in that case but it is `arm`. Is this by intention?

https://github.com/philips-labs/terraform-aws-github-runner/blob/10a7603949892ea2dd29593e8b24989b0f91fa40/examples/multi-runner/main.tf#L27

Because the label-matcher is configured in such way:
https://github.com/philips-labs/terraform-aws-github-runner/blob/10a7603949892ea2dd29593e8b24989b0f91fa40/examples/multi-runner/main.tf#L15

**Comment by npalm** [comment]
Good question, and this is indeed a mistake in the example, The `runner_extra_labels` are the extra labels added to reunners, besides the default ones GitHub is adding by default. Like `self-hosted`, arch and OS. The labelMatcher is only used in the webhook to delegate the message to a queue. 

So it should be `runner_extra_labels            = "amazon" ` in this case. 

Also quickly checked my deployment test workflow, and there I only had specified `self-hosted, arm64, linux` which explains why the mistake was not found. 

If you have time feel free to propose a PR.

**Comment by mariusfilipowski** [comment]
Okay. I'll give it a try.

**Comment by npalm** [comment]
closing, since the issue is fixed. Thanks @mariusfilipowski
