### ISSUE TITLE
Is the variable really named "enable_enable_fifo_build_queue"?

### ISSUE THREAD

**Issue by mariusfilipowski** [philips-labs/terraform-aws-github-runner#2852]
I just tried out to check the 2.0.2 version with the "simple" runner as it was availble in 1.x.
While migrating the variable names I stumbled upon `enable_enable_fifo_build_queue` (with doubled `enable_`):

https://github.com/philips-labs/terraform-aws-github-runner/blob/448900e4edce8dcd60e9158c1b1652ba82cfd59d/variables.tf#L598

https://github.com/philips-labs/terraform-aws-github-runner/blob/448900e4edce8dcd60e9158c1b1652ba82cfd59d/main.tf#L62

Is this correct? In the release notes and the deprecation warning it says that `DEPCRECATED, replaced by enable_fifo_build_queue` is the correct one: https://github.com/philips-labs/terraform-aws-github-runner/releases/tag/v2.0.1

Looks like a bug to me. But I am not sure.

**Comment by npalm** [comment]
Thanks for reporting, will provide a fix. This is indeed a mistake.
