### ISSUE TITLE
DLQ is created although it is not configured

### ISSUE THREAD

**Issue by mariusfilipowski** [philips-labs/terraform-aws-github-runner#2874]
Using the multirunners, I noticed that we have now corresponding dead letter queues. I did use the following config taken from the multi runner example.

```
      redrive_build_queue = {
        enabled         = false
        maxReceiveCount = null
      }
```
Now I have 2 queue for each runner config. One with the suffix `-queued-builds` and another one with `-queued-builds_dead_letter`
Is this intended?

**Comment by npalm** [comment]
Should not be intended. @GuptaNavdeep1983  ?

**Comment by mariusfilipowski** [comment]
It looks like here a check for `var.redrive_build_queue.enabled` is missing:

https://github.com/philips-labs/terraform-aws-github-runner/blob/fca2ddfd545c2b670adcecf4e7d3107b9f4006b0/modules/multi-runner/queues.tf#L58

and here:

https://github.com/philips-labs/terraform-aws-github-runner/blob/main/modules/multi-runner/queues.tf#L69

Similar to:
https://github.com/philips-labs/terraform-aws-github-runner/blob/main/modules/multi-runner/queues.tf#L39

This check is also part of the "normal" runner module:

https://github.com/philips-labs/terraform-aws-github-runner/blob/main/main.tf#L106

**Comment by npalm** [comment]
Would you have time to create a PR?

**Comment by mariusfilipowski** [comment]
Currently not (sadly). Perhaps next week.

**Comment by mariusfilipowski** [comment]
Please check: https://github.com/philips-labs/terraform-aws-github-runner/pull/2903

**Comment by mariusfilipowski** [comment]
Hi! Just asking if the PR could be reviewed or is sth missing from my side?

**Comment by GuptaNavdeep1983** [comment]
PR is already approved and merged.
