### ISSUE TITLE
Multi runners: Having a too long multi runner name in config fails the deployment

### ISSUE THREAD

**Issue by mariusfilipowski** [philips-labs/terraform-aws-github-runner#2875]
We have the following prefix `toolchain-ubuntu` and the name of the multi runner config in the map is `ubuntu-x64-20-large`.

Deploying this yields the following error:
```
Error: expected length of name to be in the range (1 - 64), got toolchain-ubuntu-ubuntu-x64-20-large-action-scale-down-lambda-role
```

Should this limitation perhaps be documented? Or could we even validate this in the TF variables definition?

**Comment by npalm** [comment]
I see several options, but the limitation should be certainly documented. Other options includes a check with variable validation, or shrink the name back to 64. I prefer understandable names, but this is indeed a drawback.
