### ISSUE TITLE
allow the usage of an encrypted AMI

### ISSUE THREAD

**Issue by v-rosa** [philips-labs/terraform-aws-github-runner#2927]
Currently its not possible to use an AMI encrypted using an external KMS key.

Something like this would fix this issue. https://github.com/v-rosa/terraform-aws-github-runner/tree/allow-using-encrypted-ami

Would be great to have this feature, let me know if these changes are OK for a PR.

Co-authored with @rsmolinski

**Comment by reedloden** [comment]
(random lurker here that just saw this issue)

Wouldn't it make sense to go ahead and submit as a PR versus waiting to hear if you should? Saves an unneeded step. :-)

**Comment by reedloden** [comment]
not stale :-)

**Comment by marko-fabry** [comment]
Hello @v-rosa , I have tried your shared encrypted AMI feature in the 2.4.0 release but I was not able to get the scale-up lambda to actually run an EC2 instance without adding following IAM permission to the role:

```
statement {
    sid    = "AllowKMSCreateGrant"
    effect = "Allow"
    actions = [
      "kms:CreateGrant",
    ]
    resources = [
      var. ami_kms_key_arn
    ]
    condition {
      test     = "Bool"
      variable = "aws:ViaAWSService"
      values   = ["true"]
    }
  }
```

Did you maybe set some special permissions on the KMS key, so that this is not needed?

**Comment by v-rosa** [comment]
Hello @marko-fabry indeed you are right, we're missing the Kms:CreateGrant permission I have it in my example, not sure why I missed it in the initial PR.

Could you open PR to fix it? I can only do it next week.

**Comment by v-rosa** [comment]
In you KMS key policy try to add the following statement:

```json
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::<account-number>:<root-or-iam-role>"
                ]
            },
            "Action": "kms:CreateGrant",
            "Resource": "*"
        }
```

And try again to spin up some runners. With this permission on the key policy I could create runners without specifically add  Kms:CreateGrant on the lambda policy.

**Comment by marko-fabry** [comment]
@v-rosa  I added a PR - https://github.com/philips-labs/terraform-aws-github-runner/pull/3049 :)

**Comment by v-rosa** [comment]
Seems that a new hot fix was released, closing this issue.
