### ISSUE TITLE
Lambdas have excessive permissions

### ISSUE THREAD

**Issue by mbeliayeu** [philips-labs/terraform-aws-github-runner#2935]
Is there a good reason for lambdas to have wildcard `ssm:PutParameter` permission? See [this](https://github.com/philips-labs/terraform-aws-github-runner/blob/a1013e91f0fe380ff7988e20e9efea78e73acea6/modules/runners/policies/lambda-scale-up.json#L27). I would use permission boundary, but it also restricts runners, something I don't want to do.

**Comment by mbeliayeu** [comment]
Alternatively, it would be nice to decouple permission boundaries for lambda and for runners and/or update docs. For example, [this](https://github.com/philips-labs/terraform-aws-github-runner/blob/a1013e91f0fe380ff7988e20e9efea78e73acea6/modules/multi-runner/variables.tf#L202) implies that boundary is only for lambdas, but [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/a1013e91f0fe380ff7988e20e9efea78e73acea6/modules/runners/policies-runner.tf#L7) we can see that it is attached to runners as well.

**Comment by npalm** [comment]
Any improvement to limit the permissions is welcome. The lambda (control plane) requires indeed some more permission. We have tried to keep the permission of the runner to the bare minimum. Since the runners are use by any repo in your org.

**Comment by v-rosa** [comment]
Correct me if I'm wrong, but we could _just_ limit the resources starting witht the [path_prefix](https://github.com/philips-labs/terraform-aws-github-runner/blob/ef548d93e7d61b3ae3e6743a3f9d8b58ba4ee5cc/modules/ssm/variables.tf#L21)

**Comment by npalm** [comment]
@v-rosa I had weeks ago contact with Amazon but IAM does not support a dynamic policy to let the runner only access a resource named to it's insance id

**Comment by npalm** [comment]
Indeed would be certainly possible, help and PR's are welcome :)
