### ISSUE TITLE
Runner not deleted from registered runners when getting swapped

### ISSUE THREAD

**Issue by fffonion** [philips-labs/terraform-aws-github-runner#2939]
Hi, thanks for providing this awesome module.

In our use case, we have spotted that when an instance being swapped away either by scaling or because of AWS,
the old runner instance (with the old instance hostname) keeps existence in Github's runner registration as `Offline`
state and we have to delete them manually.

The runner script does provide switch to remove it by calling `./config.sh remove --token "${TOKEN}" `.

**Comment by npalm** [comment]
You can run the runner in two modes, ephemeral and non ephemeral. When running ephemeral the runner got removed once the job is done. For non ephemeral there is no gracefull shutdown. The scale-down lambda should deregister the runner from GitHub. 

I haven't seen problems in our deployment so far.

**Comment by OlegSupport** [comment]
so. i have the same issue but can't find reason
