### ISSUE TITLE
Output log group arns from the module

### ISSUE THREAD

**Issue by earlofhemsley** [philips-labs/terraform-aws-github-runner#2945]
### Overview
it would be extremely helpful if the log group arns were outputs of the modules.

### Use case
As a consumer of this module, I need to be able to subscribe the cloudwatch log groups created by this module to a lambda function or similar (such as a log exporter function for analytics platforms like datadog) so that I can centralize my logs into a highly visible repository that anyone in my organization can access or analyze without requiring an AWS account login.

### Suggested Change
It took a couple tries, but we figured out how to subscribe the log groups created by the module to a lambda. In order to do that, we had to manually compose the source arns for the subscription. In the interest of clarity, relevant snippets of our terraform code that did what I'm describing is below. It would be really nice if we didn't have to build the `source_arn` prop of the `aws_lambda_permission` from scratch. Those couple hours were really frustrating. It would have been really nice to have had those arns handy as an output.

Thank you so much for this module. It's helped me out a lot.

```
locals {
  log-group-config = {
    "gh-ci/messages"          = "/var/log/messages"
    "gh-ci/user-data"           = "/var/log/user-data.log"
    "gh-ci/runner"                = "/opt/actions-runner/_diag/Runner_**.log"
    "gh-ci/runner-startup"  = "/var/log/runner-startup.log"
  }
}

resource "aws_lambda_permission" "messages-subscription-permission" {
  for_each      = local.log-group-config
  action        = "lambda:InvokeFunction"
  function_name = data.aws_lambda_function.datadog-exporter.function_name
  principal     = "logs.${data.aws_region.current.name}.amazonaws.com"
  source_arn    = "arn:${data.aws_partition.current.partition}:logs:${data.aws_region.current.name}:${data.aws_caller_identity.current.account_id}:log-group:/${each.key}:*"

resource "aws_cloudwatch_log_subscription_filter" "messages-subscription-filter" {
  for_each        = local.log-group-config
  destination_arn = data.aws_lambda_function.datadog-exporter.arn
  filter_pattern  = ""
  log_group_name  = "/${each.key}"
  name            = "${each.key}-subscription-filter"
}
```
and then we used that same local to build the logging inputs in the module
```
(from the module inputs...)
  runner_log_files = [for name, file_path in local.log-group-config : {
    log_group_name   = name
    file_path        = file_path
    log_stream_name  = "{instance_id}"
    prefix_log_group = false
  }]

```

**Comment by npalm** [comment]
I think what you need is that those resources got exported as output.

```
resource "aws_cloudwatch_log_group" "gh_runners" {
  count             = length(local.loggroups_names)
  name              = local.loggroups_names[count.index]
  retention_in_days = var.logging_retention_in_days
  kms_key_id        = var.logging_kms_key_id
  tags              = local. Tags
}

```

Correct?

**Comment by earlofhemsley** [comment]
Correct. I want the log groups exported as output. Or, at minimum, their arns.

**Comment by npalm** [comment]
Feel free to raise a PR to export the log groups.

**Comment by earlofhemsley** [comment]
I will try to find the time to do this. In the meantime, I'd appreciate it if your could tell me if you see merit in this suggestion.

**Comment by npalm** [comment]
I think this one is related: https://github.com/philips-labs/terraform-aws-github-runner/pull/3044

**Comment by earlofhemsley** [comment]
That may have been exactly what I wanted. I'll take a closer look later today and will close this ticket if it is. Thanks!
