### ISSUE TITLE
No instances get created

### ISSUE THREAD

**Issue by Jamesking56** [philips-labs/terraform-aws-github-runner#2962]
No instances get created when running actions, I can see inside my GitHub app that the webhook correctly hits API gateway and that successfully runs the lambdas and uses SQS successfully.

In the scale up lambda, I just see one weird message:

```
Ignoring error: secretOrPrivateKey must be an asymmetric key when using RS256 
```

Would this stop instances being created?

Here is my `main.tf` with secrets removed:

```
module "github-runner" {
  source  = "philips-labs/github-runner/aws"
  version = "v2.2.0"

  aws_region = "eu-west-2"
  vpc_id     = "<snip>"
  subnet_ids = ["<snip>"]

  prefix = "actions-runner"

  github_app = {
    key_base64     = "<snip>"
    id             = "<snip>"
    webhook_secret = "<snip>"
  }

  webhook_lambda_zip                = "lambdas/webhook.zip"
  runner_binaries_syncer_lambda_zip = "lambdas/runner-binaries-syncer.zip"
  runners_lambda_zip                = "lambdas/runners.zip"

  enable_organization_runners = true

  enable_fifo_build_queue = true

  # enable access to the runners via SSM
  enable_ssm_on_runners = true

  runner_run_as = "ubuntu"

  userdata_template = "./templates/user-data.sh"
  ami_owners        = ["099720109477"] # Canonical's Amazon account ID

  ami_filter = {
    name = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  instance_types = ["t3a.small"]

  block_device_mappings = [{
    # Set the block device name for Ubuntu root device
    device_name           = "/dev/sda1"
    delete_on_termination = true
    volume_type           = "gp3"
    volume_size           = 30
    encrypted             = true
    iops                  = null
    throughput            = null
    kms_key_id            = null
    snapshot_id           = null
  }]

  runner_extra_labels = "ubuntu-latest,ubuntu-22.04"

  runner_log_files = [
    {
      "log_group_name" : "syslog",
      "prefix_log_group" : true,
      "file_path" : "/var/log/syslog",
      "log_stream_name" : "{instance_id}"
    },
    {
      "log_group_name" : "user_data",
      "prefix_log_group" : true,
      "file_path" : "/var/log/user-data.log",
      "log_stream_name" : "{instance_id}/user_data"
    },
    {
      "log_group_name" : "runner",
      "prefix_log_group" : true,
      "file_path" : "/opt/actions-runner/_diag/Runner_**.log",
      "log_stream_name" : "{instance_id}/runner"
    }
  ]

  # https://github.com/philips-labs/terraform-aws-github-runner/issues/1671#issuecomment-1165465203
  scale_up_reserved_concurrent_executions = -1

  # For debugging, see if we can have a couple of idle runners
  idle_config = [{
    cron      = "* * * * * *"
    timeZone  = "Europe/London"
    idleCount = 2
  }]
}

```

**Comment by swiftain** [comment]
Hi, 

I am having the same issue. Were you able to figure out the reason?

Thanks

**Comment by Jamesking56** [comment]
@swiftain There is a default delay of 30 seconds before instances are created via the webhook, so I set `delay_webhook_event` to `0` to disable the delay.

**Comment by swiftain** [comment]
@Jamesking56 thanks for replying! Made that change, set delay_webhook_event to 0 but instance is not being created. I see the security group created, but no instance created

**Comment by Jamesking56** [comment]
@swiftain Whats your full `main.tf`?

**Comment by swiftain** [comment]
@Jamesking56, here it is, and it's based on the [default example](https://github.com/philips-labs/terraform-aws-github-runner/blob/main/examples/default/main.tf) 
locals {
  environment = var.environment != null ? var.environment : "default"
  aws_region  = "us-east-1"
}

resource "random_id" "random" {
  byte_length = 20
}

module "base" {
  source = "../base"

  prefix     = local.environment
  aws_region = local.aws_region
}

module "runners" {
  source                          = "../../"
  create_service_linked_role_spot = true
  aws_region                      = local.aws_region
  vpc_id                          = module.base.vpc.vpc_id
  subnet_ids                      = module.base.vpc.private_subnets

  prefix = local.environment
  tags = {
    Project = "ProjectX"
  }

  github_app = {
    id             = ""
    webhook_secret = random_id.random.hex
    key_base64     = ""
  }

  # Grab zip files via lambda_download
  webhook_lambda_zip                = "../lambdas-download/webhook.zip"
  runner_binaries_syncer_lambda_zip = "../lambdas-download/runner-binaries-syncer.zip"
  runners_lambda_zip                = "../lambdas-download/runners.zip"

  enable_organization_runners = true
  runner_extra_labels         = "ubuntu-latest"

  # enable access to the runners via SSM
  enable_ssm_on_runners = true

  instance_types = ["t3a.small"]

  # override delay of events in seconds
  delay_webhook_event   = 0
  runners_maximum_count = 1

  # set up a fifo queue to remain order
  # enable_fifo_build_queue = true

  # override scaling down
  scale_down_schedule_expression = "cron(* * * * ? *)"

  enable_user_data_debug_logging_runner = true

  # prefix GitHub runners with the environment name
  runner_name_prefix = "${local.environment}_"

  scale_up_reserved_concurrent_executions = -1
 
  log_level = "debug"

}

**Comment by swiftain** [comment]
@Jamesking56, here it is, it's based on the default example

locals {
environment = var.environment != null ? var.environment : "default"
aws_region = "us-east-1"
}

resource "random_id" "random" {
byte_length = 20
}

module "base" {
source = "../base"

prefix = local.environment
aws_region = local.aws_region
}

module "runners" {
source = "../../"
create_service_linked_role_spot = true
aws_region = local.aws_region
vpc_id = module.base.vpc.vpc_id
subnet_ids = module.base.vpc.private_subnets

prefix = local.environment
tags = {
Project = "ProjectX"
}

github_app = {
id = ""
webhook_secret = random_id.random.hex
key_base64 = ""
}

**Comment by Jamesking56** [comment]
@swiftain If you go into Cloudwatch do you get any logs for the webhook?

**Comment by Jamesking56** [comment]
@swiftain any other logs you get?

**Comment by swiftain** [comment]
@Jamesking56 Just the webhook and scaleup lambda logs.

**Comment by achaphiv** [comment]
@swiftain 

I see you have:

```
  subnet_ids                      = module.base.vpc.private_subnets
```

In my case, the EC2 instance was being launched, but never registered under

https://github.com/organizations/${ORGANIZATION}/settings/actions/runners

I had to use a public subnet. Maybe you have a similar networking issue.

```diff
-  subnet_ids = module.core_base.outputs.base.vpc.private_subnets
+  subnet_ids = module.core_base.outputs.base.vpc.public_subnets
```

**Comment by cheadman** [comment]
@swiftain I am also having this issue. no runners created, and the same error in cloudwatch. did you figure it out?

**Comment by cheadman** [comment]
Alright, for anyone else that sees this error, This "secretOrPrivateKey" is referring to the "key_base64" value in [the terraform module](key_base64). For me, I was using terraform cloud and I had set a variable in terraform cloud with the value of the key. What worked for me was making the value of the variable the multiline key wrapped in quotes. it should work with \n instead of new lines as well. To fix this error, you probably just need to wrap your variable value in quotes.
