### ISSUE TITLE
Unsupported Event type for all events

### ISSUE THREAD

**Issue by ethanwllms** [philips-labs/terraform-aws-github-runner#2963]
I am receiving the following warning from the webhook lambda upon a Github originated payload is sent.
`WARN [webhook:6e15a587-9710-4451-ac4a-XxXxXxXxXxXxX index.js:71833  handle] Unsupported event type.`

I have toggled between Check Run and Workflow Job to see if that might change anything, and nothing has come of it. As well, I have checked that my permissions are set according to README and they appear to be set correctly. I'm pretty sure I have misconfigured something, but just in case, I didn't see another issue like this so maybe this would help someone in the future.

In general, I am running on default module. Using organizational runners (followed all org instructions), S3 lambda source, and role created/used on apply.

**Comment by Haagy** [comment]
Facing the same problem. Re-applying terraform scripts and re-installing the GitHub app won't do the trick either.

**Comment by ethanwllms** [comment]
I'm wondering if I made a mistake in the first Github UI setup portion. Created the app like it said and noted the App ID and have provided that to the module as well as the private key, but no dice.

**Comment by npalm** [comment]
The module only supports the workflow_job event, in the app you can see which events are sent. I also think when you enable debug for the webhook all events are logged.

**Comment by Haagy** [comment]
Today I had the chance to update the module to the latest version `2.2.1`.
Updated the config a bit (thank your @npalm for the hint with `log_level` param) and made some steps forward.
`webhook` Lambda receives messages and forwards them to SQS `queued-builds.fifo `
```
2023-02-21 16:16:36.496  INFO  [webhook:11ac9ac1-f541-4718-94a3-6f5c210fb72b index.js:71920  handleWorkflowJob] Successfully queued job for WEPF/debug-scalable-actions to the queue https://sqs.eu-central-1.amazonaws.com/123456789/wcmp-test-queued-builds.fifo 
{
    "event": "workflow_job",
    "repository": "WEPF/debug-scalable-actions",
    "action": "queued",
    "name": "docs",
    "status": "queued",
    "workflowJobId": 1801244,
    "started_at": "2023-02-21T16:16:35Z",
    "completed_at": null,
    "conclusion": null
}
```
SQS to scalue-up Lambda I get an error message:
```
2023-02-21 16:16:42.553  INFO  [scale-up:9fbb9e86-fdc8-5455-994f-c2e80d5dc728 index.js:134848  scaleUp] Received workflow_job from WEPF/debug-scalable-actions 
{}
 
2023-02-21 16:16:42.554  INFO  [scale-up:9fbb9e86-fdc8-5455-994f-c2e80d5dc728 index.js:134881  scaleUp] Received event 
{
    "runnerType": "Org",
    "runnerOwner": "WEPF",
    "event": "workflow_job",
    "id": "1801244"
}
 
2023-02-21 16:16:42.822  DEBUG [gh-auth:9fbb9e86-fdc8-5455-994f-c2e80d5dc728 index.js:134266  createAuth] GHES API URL: https://atc-github.azure.cloud.bmw/api/v3 
{
    "runnerType": "Org",
    "runnerOwner": "WEPF",
    "event": "workflow_job",
    "id": "1801244"
}

2023-02-21 16:16:42.938  ERROR [scale-down:9fbb9e86-fdc8-5455-994f-c2e80d5dc728 node:internal/process/warning:60  writeOut] (node:8) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time

(Use `node --trace-warnings ...` to show where the warning was created) 

2023-02-21 16:16:43.153  WARN [scale-runners:9fbb9e86-fdc8-5455-994f-c2e80d5dc728 index.js:134309  Runtime.handler] Ignoring error: terminated 
{
    "runnerType": "Org",
    "runnerOwner": "WEPF",
    "event": "workflow_job",
    "id": "1801244"
}
```
My configuration is based mainly on https://github.com/philips-labs/terraform-aws-github-runner/blob/v2.2.1/examples/default/main.tf
```
  source     = "philips-labs/github-runner/aws"
  version    = "2.2.1"
  ghes_url   = var.github_url
  aws_region = var.region
  vpc_id     = var.vpc_ids[0]
  subnet_ids = var.subnet_ids
  prefix     = "${var.brand}-${var.env}"

  github_app = {
    key_base64     = filebase64("${path.module}/temp/private-key.pem")
    id             = var.github_app_id
    webhook_secret = var.github_app_webhook_secret
  }

  webhook_lambda_zip                = "temp/webhook.zip"
  runner_binaries_syncer_lambda_zip = "temp/runner-binaries-syncer.zip"
  runners_lambda_zip                = "temp/runners.zip"
  enable_organization_runners       = true
  runner_extra_labels               = "tbm-default"

  enable_ssm_on_runners = true
  #create_service_linked_role_spot = true

  log_level = "debug"

  instance_types = ["m5.large", "c5.large"]

  # override delay of events in seconds
  delay_webhook_event   = 5
  runners_maximum_count = 5

  # set up a fifo queue to remain order
  enable_fifo_build_queue = true

  # override scaling down
  scale_down_schedule_expression = "cron(*/5 * * * ? *)"
  # enable this flag to publish webhook events to workflow job queue
  #enable_workflow_job_events_queue  = true

  enable_user_data_debug_logging_runner = true
}
```

**Comment by Haagy** [comment]
@ethanwllms 
I experienced some issues with multiple workflows definitions. Even tho one definition had the required labels to trigger the `webhook` only the first created workflow was sending messages to Lambda.
Maybe that will helps you.
