### ISSUE TITLE
Option for EBS Optimized?

### ISSUE THREAD

**Issue by tedparagon** [philips-labs/terraform-aws-github-runner#2988]
I can't seem to find an option to enable EBS Optimized on the runner instance. Is this an oversight on my part or might there be a reason for not including this?

I believe this should just be a matter of setting `ebs_optimized` on the `aws_launch_template`.

Thanks!

**Comment by jpalomaki** [comment]
@tedparagon I cannot see why we'd not want to support this. Can you post a PR to add the flag? See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#ebs_optimized

**Comment by tedparagon** [comment]
@pbarnajc thanks for adding this. I see `ebs_optimized` on the runners and multi-runners modules but don't see a way of setting it from the root module. I also can't find any mention of it in the docs.

**Comment by AlexShemeshWix** [comment]
I can see the ebs_optimized on runners module. But how do i enable it on main module?

**Comment by AlexShemeshWix** [comment]
@pbarnajc?
