### ISSUE TITLE
runner wont registered to GitHub as a runner.

### ISSUE THREAD

**Issue by yardenasadosa** [philips-labs/terraform-aws-github-runner#2989]
issue:
====
the ec2 starts but after some time terminated without runner registration in GitHub.

details:
=====
based on ubuntu 20 image.
tried with version "2.1.1".
tried with local lambda zips (downloaded manually from version 2.1.1) and with lambda downloaded to s3 using the module.

/var/log/runner-startup.log (which is the log of "/var/lib/cloud/scripts/per-boot/start-runner.sh")
===================
An error occurred (AccessDeniedException) when calling the GetParametersByPath operation: User: arn:aws:sts::<aws account id>:assumed-role/playground-runner-role/i-04611d6e69c30cfa2 is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:us-west-2:<aws account id>:parameter/playground/runner because no identity-based policy allows the ssm:GetParametersByPath action

**Comment by yardenasadosa** [comment]
I gave admin access to try and workaround the permissions issue, then it fails on:

**Comment by npalm** [comment]
Then you see `the parameter not exists so cannot be deleted.` it most likely means that either the script is looking for the wrong parameter in SSM. Or the parameter with the registration token is not created at all (for example due to rate limits).

**Comment by yardenasadosa** [comment]
the issue was the user data script was not correct. It worked when using the newest example for self-hosted runners user data script. Thanks.
