### ISSUE TITLE
How to label the instances

### ISSUE THREAD

**Issue by 7adityaraj** [philips-labs/terraform-aws-github-runner#2998]
We have pools of instances that spin up with labels, so my question is if there is a way to label the instances as well so that we can spin up the instances that we would like to with labels. Or, if there are any other suggestions on this topic. Currently, the issue is we have a pool of spot instances and in most case, only top most instances that are in the list and available is spinning up so I am not sure how can I get instances up with labels. Any suggestions or pointers would be helpful. Thank you in advance.

```
variable "instance_types" {
  default = [
    "c5ad.large",
    "c5a.large",
    "c5d.large",
    "c5.large"
]
```

**Comment by wu-json** [comment]
Would like to reopen this. I think this would be a great feature if not available already.
