### ISSUE TITLE
Request: Change the github.com url for GitHub Enterprise Server

### ISSUE THREAD

**Issue by mm-matsuda** [philips-labs/terraform-aws-github-runner#303]
Hello!

Since we are using GitHub Enterprise Server, the github.com url is not available.
I want the download-lambda module to allow me to specify a url when I download a zip.

https://github.com/philips-labs/terraform-aws-github-runner/blob/5a045f555dc932459c5ed94239b3d345e9f916ba/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts#L96

Cheers

**Comment by npalm** [comment]
@mm-matsuda do you have time to look on the PR? I have not gh enterprise running so no option to test

**Comment by WilliamDuTrendMicro** [comment]
as the GitHub EE most inside a VPC , it also need lambda working inside the VPC to conenct the GitHub EE API .

**Comment by mcaulifn** [comment]
@npalm Is there a PR for this? I have GHES and can test

**Comment by npalm** [comment]
No PR yet, but looking for help. I made a start a few weeks ago in #303 but need to find a way the lambda's get access GHES via the API.

**Comment by mcaulifn** [comment]
#412 opened to address this

**Comment by npalm** [comment]
@mcaulifn thanks, will have a look later this week

**Comment by npalm** [comment]
PR #412 merges, closing the issue
