### ISSUE TITLE
AMI ID SSM parameter name is not respected when using pool

### ISSUE THREAD

**Issue by jpalomaki** [philips-labs/terraform-aws-github-runner#3038]
Hello,

@npalm We are testing ephemeral runners + pool + prebuilt AMIs (no userdata script), and it looks like the `ami_id_ssm_parameter_name` is not taken into account with pooled instances.

This means that instances are booted up with the default amazon linux AMI, which then of course does not work as it does not include the runner software, and hence the instance does not register itself to GitHub.

Looking at the code, the pool call to `createRunners` does in fact omit this parameter: https://github.com/philips-labs/terraform-aws-github-runner/blob/main/modules/runners/lambdas/runners/src/pool/pool.ts#L90

I can try to whip up a PR to fix this.

Cheers,
Jukka

**Comment by npalm** [comment]
The AMI is part of the launch template, so the pool istances should use the same launch template as normal runners. And the launch template should be set as env variable of the lamba

**Comment by jpalomaki** [comment]
Sure, but if we want to look up the AMI ID from SSM parameter, currently the pool does not do it. See https://github.com/philips-labs/terraform-aws-github-runner/pull/3040 for a fix

**Comment by npalm** [comment]
You right, that is missing.
