### ISSUE TITLE
Add ability to set Packer EC2 instance profile for prebuilt image

### ISSUE THREAD

**Issue by dmarkey** [philips-labs/terraform-aws-github-runner#3041]
Unless my eyes are failing me, I don't see an ability to set the EC2 instance profile when using packer for the pre-built images.

Part of the build process might be fetching a file from S3 etc, would be nice.

Thanks!

**Comment by jpalomaki** [comment]
@dmarkey Can you post a PR to add the support? See https://developer.hashicorp.com/packer/plugins/builders/amazon/ebs#iam_instance_profile

**Comment by npalm** [comment]
Feel free to raise a PR. The images are mostly as inspiration / example. But we welcome PR's to improve them further.

**Comment by mattgodbolt** [comment]
This is something we've had a long-standing need for (with a separate fork of the runner just for this); I'll look to see if it's a something we could PR back to the main repo here!
