### ISSUE TITLE
Drift on runner_binaries[0].aws_s3_bucket_server_side_encryption_configuration.action_dist[0]

### ISSUE THREAD

**Issue by ItaiCovver** [philips-labs/terraform-aws-github-runner#3066]
I get this same diff every time I build.

<img width="1121" alt="Screenshot 2023-03-13 at 6 49 17 PM" src="https://user-images.githubusercontent.com/96085044/224770067-489de46f-417b-4d7b-918b-e4459aa37196.png">

Terraform version: 1.3.9
hashicorp/aws version: 4.57.1

**Comment by npalm** [comment]
Should be solved in the latest release 2.6.0 by https://github.com/philips-labs/terraform-aws-github-runner/pull/3048
