### ISSUE TITLE
Docker install needs a -y

### ISSUE THREAD

**Issue by kernel-io** [philips-labs/terraform-aws-github-runner#307]
It seems like we need a -y on this line

https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/templates/user-data.sh#L9

My runners hang and don't even finish booting without it.

**Comment by npalm** [comment]
@kernel-io can you provide a PR with the change?

**Comment by kernel-io** [comment]
https://github.com/philips-labs/terraform-aws-github-runner/pull/325
