### ISSUE TITLE
Question: In a multi runner configuration, what happens if there is no spot capacity for the specified instance types?

### ISSUE THREAD

**Issue by dgokcin** [philips-labs/terraform-aws-github-runner#3091]
Hello and thank you for the module, it has helped us a lot to reduce the GitHub Actions costs and use our aws credits for long-running ci cd workflows. I would like to ask about the mechanism that decides which instance to use to run a workflow with ephemeral runners. What I expect from the below config is, if there is no spot capacity available for m5n.8xlarge, a m5ad.8xlarge instance is used. Is this correct? I tried examining the scale up lambda index.js but could not find the code that is responsible for the fallback mechanism if there is no spot capacity available. 

Could you please tell me how the module behaves when deciding on the instance type to use?

```hcl
    "linux-ubuntu" = {
      matcherConfig : {
        labelMatchers = [["self-hosted", "linux", "x64", "ubuntu-latest"], ["self-hosted", "linux", "x64", "ubuntu-2204"]]
        exactMatch    = true
      }
      fifo                = true
      delay_webhook_event = 0
      redrive_build_queue = {
        enabled         = false
        maxReceiveCount = null
      }
      runner_config = {
        runner_os                       = "linux"
        runner_architecture             = "x64"
        runner_extra_labels             = "ubuntu-latest,ubuntu-2204"
        runner_run_as                   = "ubuntu"
        enable_ssm_on_runners           = true
        instance_types                  = ["m5n.8xlarge", "m5ad.8xlarge", "m5a.8xlarge", "m5n.4xlarge", "m5ad.4xlarge", "m5a.4xlarge"]
        runners_maximum_count           = 3
        scale_down_schedule_expression  = "cron(* * * * ? *)"
        create_service_linked_role_spot = true
        userdata_template               = "./templates/user-data.sh"
        ami_owners                      = ["099720109477"] # Canonical's Amazon account ID

        ami_filter = {
          name = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
        }
        block_device_mappings = [{
          # Set the block device name for Ubuntu root device
          device_name           = "/dev/sda1"
          delete_on_termination = true
          volume_type           = "gp3"
          volume_size           = 30
          encrypted             = true
          iops                  = null
          throughput            = null
          kms_key_id            = null
          snapshot_id           = null
        }]
        runner_log_files = [
          {
            log_group_name   = "syslog"
            prefix_log_group = true
            file_path        = "/var/log/syslog"
            log_stream_name  = "{instance_id}"
          },
          {
            log_group_name   = "user_data"
            prefix_log_group = true
            file_path        = "/var/log/user-data.log"
            log_stream_name  = "{instance_id}/user_data"
          },
          {
            log_group_name   = "runner"
            prefix_log_group = true
            file_path        = "/opt/actions-runner/_diag/Runner_**.log",
            log_stream_name  = "{instance_id}/runner"
          }
        ]
      }
    },
```

**Comment by npalm** [comment]
Depends for ephemeral runners a eror goes back to the queue and retries will happen, for non ephemeral the errors are ignored. There is currently no mechanisme for a fallback, see #3035. We use typicalliy a list of images and Amazon will chose the best one for you based on the set strategy.

**Comment by npalm** [comment]
You can set different strategies, I think the default is the cheapest. I think the order is not important.

**Comment by dgokcin** [comment]
Thank you very much, `lowest-price` was used by default. I achieved what I wanted by using `instance_allocation_strategy    = "capacity-optimized-prioritized` in my multi runner configuration. Leaving some helpful links here if anyone else looks accross issues instead of the documentation like me 🙃 

[Spot Fleet Allocation Strategy](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-fleet-allocation-strategy.html)
https://github.com/philips-labs/terraform-aws-github-runner/blob/418c74b18e91fa56064fc01ec340698f40d4b668/variables.tf#L458

**Comment by npalm** [comment]
Thx for the feedback, can we close the issue?

**Comment by dgokcin** [comment]
yes, thanks for your help.
