### ISSUE TITLE
Lambda and SQS timeouts should be different

### ISSUE THREAD

**Issue by mcaulifn** [philips-labs/terraform-aws-github-runner#3109]
https://github.com/philips-labs/terraform-aws-github-runner/blob/cae13b4f8c350de677f318f0755ac65ff614c415/main.tf#L64

Per [AWS's recommendations](https://docs.aws.amazon.com/lambda/latest/dg/with-sqs.html#events-sqs-queueconfig), the SQS timeout should be six times the timeout of the lambda.

**Comment by npalm** [comment]
Thx for reporting.  Six times seems to be a lot. But agree seems logical to set it at least higher. Do you have issues? Are messages sourced to lambda multiple times?

**Comment by mcaulifn** [comment]
No issues directly. AWS support noticed the matching 30 second timeouts and indicated it might be an issue if the lambda is not able to process.

Maybe a second variable that defaults to null and a local that sets it to 6x the lambda timeout?

**Comment by npalm** [comment]
Have to check because it could have some impact for retries when the max is reached. Looking on our prod load I see rarely lambda executions over 15 secs. 

Graph below is the duration of the scale up in our case
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/11609620/228744312-b568b99d-56db-400e-8eb7-29ef5ffa968a.png">

The second graph shows the number of invocations per hour
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/11609620/228744442-a794c606-1844-4c68-ae48-b849e179e385.png">

**Comment by mcaulifn** [comment]
I think at least a second variable that defaults to the first default should be good enough.

**Comment by mcaulifn** [comment]
I think at least a second variable that defaults to the first default should be good enough.

**Comment by dgokcin** [comment]
@npalm I also have a case where I need to have different limits for the visibility timeout and the lambda timeout. 

We were using knapsack pro + cypress on GitHub hosted runners to run e2e tests in 10+ nodes  and I am working on replacing those instances with spot instances to reduce our GitHub bill.

Basically, my goal is to to spin up 15 instances at around the same time. I think 10 second interval between the running state of the first runner and the last runner should be sufficient. And I want exactly 15 instances. 

Knapsack needs the runners to be available as soon as possible to properly parallelize jobs. If the runner instances are not available at around the same time, the nodes that come online the latest is not utilized. To support this, I tried several things such as

### Default visibility timeout: 60, default  reserved concurrency for scale up: 1

- No errors in the logs, the desired number of runners are eventually created but with a minute between the running state of the first instance and the 15th instance.

### visibility timeout: 6 seconds, reserved concurrency: 10

- Runners start around the same time, knapsack jobs execute successfully.
- Some invocations are timed out at 6 seconds
- More than desired number of runners are created, curiois about why. 

I know I can find the configuration that works by trial and error, but I am going to have to do the same experiments to find the new combination that works as the number of self hosted runners/repos/developers change. It would be nice to control these independently.

## References

- https://knapsackpro.com/faq/question/if-one-of-the-parallel-ci-nodes-starts-work-very-late-after-other-parallel-ci-nodes-already-finished-work-then-tests-are-executed-twice-on-late-ci-node-in-knapsack-pro-queue-mode
