### ISSUE TITLE
Random error trying to remove a runner

### ISSUE THREAD

**Issue by jgutierrezglez** [philips-labs/terraform-aws-github-runner#3162]
Hello team,

I hope you're doing well. From time to time, we're getting the following error in the scale-down lambda:

`ERROR [scale-down index.js:134676  removeRunner] Runner 'i-07825f3ce86858d58' cannot be de-registered. Error: HttpError: Not Found`

We're using the version v2.1.1 of the lambdas - and our runners are configured as ephemeral (in case it's relevant). 

I took a look to the source code, and the error is generated [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/main/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts#L139) and I imagine the reason of this error is an exception that hasn't been managed properly captured - but I couldn't identify which one and where it's triggered. This issue isn't critical, but since it appears from time to time, it triggers some of the alerting that we have in place in the Cloud watch of this scale-down lambda.

Cheers,

Javier G.

**Comment by GuptaNavdeep1983** [comment]
Good find. We did observe this error in our deployment as well.

@jgutierrezglez, As far as I understand this error is a result of race condition between runner finishing his job and scale down lambda trying to remove the runner from github registration!

If the first even occurs faster than the other, its very much possible that the scale down lambda is trying to remove something which is not running but is offline.

But the interesting aspect of this condition is the absence of the runner from the GH list of registered runners even though offline! In case the runner would be offline within GitHub, it would not error out but rather accept the request and remove the runner accordingly!
