### ISSUE TITLE
Multi-Runner config should support additional security groups for each config

### ISSUE THREAD

**Issue by darklab-sh** [philips-labs/terraform-aws-github-runner#3183]
We are currently using the multi-runner module but when specifying the runner_additional_security_group_ids input within the multi_runner_config block, it is ignored. It has to be specified outside the multi_runner_config block, which means all runner configs will receive the same additional security groups.

In our use-case, we need to specify different security groups for each config. Should this not be the expected behavior?

**Comment by npalm** [comment]
Feel free to propose a PR, please take some care to keep the PR backwards compatible

**Comment by darklab-sh** [comment]
PR submitted: https://github.com/philips-labs/terraform-aws-github-runner/pull/3221
Feedback welcome!
