### ISSUE TITLE
Unable to apply the runner-binaries-syncer module due to an `AccessControlListNotSupported` error

### ISSUE THREAD

**Issue by korosuke613** [philips-labs/terraform-aws-github-runner#3202]
Hi, when I apply a new multi-runner module, I get the following error. I recently started getting this error.

```hcl
Error: error creating S3 bucket ACL for xxxx-linux-x64-dist-xxxxxxxx: AccessControlListNotSupported: The bucket does not allow ACLs
│  status code: 400, request id: XXXXXXXXXXXXX, host id: XXXXXXXXXXXXX=
│
│   with module.XXXX.module.YYYY.module.runner_binaries["linux_x64"].aws_s3_bucket_acl.action_dist_acl,
│   on .terraform/modules/XXXX.YYYY/modules/runner-binaries-syncer/main.tf line 11, in resource "aws_s3_bucket_acl" "action_dist_acl":
│   11: resource "aws_s3_bucket_acl" "action_dist_acl" {
```

According to https://github.com/hashicorp/terraform-provider-aws/issues/28353 , this is due to a change in specifications on the AWS side. As stated in "Standalone aws_s3_bucket_acl resource with default security settings" of the above Issue, the following could be written to solve the problem.

```hcl
resource "aws_s3_bucket" "example" {
  bucket = "my-tf-test-bucket"
}

resource "aws_s3_bucket_public_access_block" "example" {
  bucket = aws_s3_bucket.example.id

  block_public_acls       = false
  block_public_policy     = false
  ignore_public_acls      = false
  restrict_public_buckets = false
}

resource "aws_s3_bucket_ownership_controls" "example" {
  bucket = aws_s3_bucket.example.id
  rule {
    object_ownership = "BucketOwnerPreferred"
  }
}

resource "aws_s3_bucket_acl" "example" {
  depends_on = [
	aws_s3_bucket_public_access_block.example,
	aws_s3_bucket_ownership_controls.example,
  ]

  bucket = aws_s3_bucket.example.id
  acl    = "public-read"
}
```

## Notes
- version
  - philips-labs/github-runner/aws//modules/multi-runner: 2.6.1
  - Terraform: 1.4.5
  - AWS Provider: 4.64.0

**Comment by Rudya93** [comment]
Hello, got the same error

**Comment by Grinch321** [comment]
+1

**Comment by AlexShemeshWix** [comment]
+1 can devs fix it ?

**Comment by AlexShemeshWix** [comment]
or whats the workaround

**Comment by korosuke613** [comment]
@AlexShemeshWix 
No, I have not started the fix yet. (because today's working hours (JST) are over.)

You may be able to work around this issue by configuring the appropriate `aws_s3_bucket_ownership_controls` settings for the target S3 bucket in the AWS Management Console (Unconfirmed).

**Comment by korosuke613** [comment]
@AlexShemeshWix 
I'm not sure if I will be busy tomorrow to work on it, so if you could fix it for me, I would appreciate it.

**Comment by korosuke613** [comment]
> You may be able to work around this issue by configuring the appropriate aws_s3_bucket_ownership_controls settings for the target S3 bucket in the AWS Management Console (Unconfirmed).
https://github.com/philips-labs/terraform-aws-github-runner/issues/3202#issuecomment-1520297529

In our environment, we confirmed that the above method can work around the problem.

**Comment by AlexShemeshWix** [comment]
Confirmed.
setting  object_ownership = "BucketOwnerPreferred" in aws console did solve the problem.

**Comment by Rudya93** [comment]
> Confirmed. setting object_ownership = "BucketOwnerPreferred" in aws console did solve the problem.

After changing  bucket ownership to BucketOwnerPreferred
still get the same issue:

{
    "errorType": "Error",
    "errorMessage": "Cannot find GitHub release asset.",
    "stack": [
        "Error: Cannot find GitHub release asset.",
        "    at /var/task/index.js:654:15",
        "    at Generator.next (<anonymous>)",
        "    at fulfilled (/var/task/index.js:550:58)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
    ]
}
