### ISSUE TITLE
enable_organization_runners setting

### ISSUE THREAD

**Issue by sdarwin** [philips-labs/terraform-aws-github-runner#3237]
Hi,

Testing out terraform-aws-github-runner. Using the terraform-aws-github-runner/examples/default/ example with relatively few changes.

Instances launch in AWS, and they register successfully as organization runners in https://github.com/organizations/_my_organization_/settings/actions/runners . Then there are a list of runners that say "Idle". 
In a repository, the Github Actions jobs are all waiting. "Waiting for a runner to pick up this job... "  Nothing happens.

After experimenting with various things, such as simultaneously running jobs in multiple repositories (if that matters), I finally found a "solution".

Change

```
enable_organization_runners = true
```

to 

```
enable_organization_runners = false
```

with this small modification and nothing else, it is fixed.  The runners are launched at the repo level instead of the organization level.  The jobs are picked up, and the Actions run.

Probably I have failed to configure something.

Is there a setting that you have to adjust in Github such as "Enable using organizational runners"?  Are organization runners supposed to pick up repository jobs automatically?   What could explain the fact that only changing "enable_organization_runners" fixed it? Runner version: 2.304.0

Thanks.

**Comment by npalm** [comment]
Nothing changed recently in this part. When using org level runners ensure the app has access to the org and to the repo. Repo level runners only need to have access to the repo. Check the reamde for more deatils

**Comment by GuptaNavdeep1983** [comment]
There is a setting which is about installing the org level github app to the repo and also adding all repos to the runner group (default group name is "default").

You should also check if you would see the runners listed under the repository or not, if not, then the above two checks should be enough to get your runners accessible to the repo.

**Comment by sdarwin** [comment]
> adding all repos 

I think what I tried was specific repos not _all repos._     I'm doing a lot of things but will get back to this very soon and will report if it is fixed.  Could be something at the github.com end, not terraform-aws.

**Comment by sdarwin** [comment]
To repeat the question, and then answer it.

Set `enable_organization_runners = true`

Organization runners are enabled.  Runners will launch and at the organizational level they will appear on the runners page  https://github.com/organizations/_my_organization_/settings/actions/runners however they never pick up any jobs and the Actions will not complete successfully. Why?

Answer:

There is another page you might not think to visit, below Runners, called Runner Groups.  The Default runner group has a description "All repositories, excluding public repositories".    Click on the Default group, and it goes to a page of settings where you may check the box "Allow public repositories". 

Otherwise public repositories are excluded.  Meaning self-hosted runners will not process jobs from those repositories.
