### ISSUE TITLE
Trouble with multi-runner outputs

### ISSUE THREAD

**Issue by christophersavory** [philips-labs/terraform-aws-github-runner#3247]
I'm trying to switch from using the standard runners to a multi-runner configuration. 

I have some resources defined that uses some of the embedded runners module resources and they are no longer working correctly.  Do you have an example of how to reference these with the mult-runner? 

```
resource "aws_iam_role_policy_attachment" "attach-custom-policy-to-github-runner-role" {
  role       = module.github_runner.runners.role_runner.name
  policy_arn = aws_iam_policy.custom-policy.arn
}
```
> │ Error: Unsupported attribute
│ 
│   on main.tf line 421, in resource "aws_iam_role_policy_attachment" "attach-custom-policy-to-github-runner-role":
│  421:   role       = module.github_runner.runners.role_runner.name
│     ├────────────────
│     │ module.github_runner.runners is tuple with 2 elements
│ 
│ This value does not have any attributes.

```
resource "aws_s3_bucket_versioning" "versioning" {
  bucket = module.github_runner.binaries_syncer.bucket.id
  versioning_configuration {
    status = "Enabled"
  }
}
```
> │ Error: Unsupported attribute
│ 
│   on main.tf line 455, in resource "aws_s3_bucket_versioning" "versioning":
│  455:   bucket = module.github_runner.binaries_syncer.bucket.id
│     ├────────────────
│     │ module.github_runner.binaries_syncer is tuple with 1 element
│ 
│ This value does not have any attributes.

**Comment by npalm** [comment]
Maybe the property is not passed into the multi-runner module. Would you have time to check and create a PR?

**Comment by GuptaNavdeep1983** [comment]
@christophersavory, the error is very clear, the property module.github_runner.runners is a map and for each type of multi runners that you created, this object has equivalent of those keys.

For example: if you created multi runners with two configurations namely x1 and x2, this object will have module.github_runner.runners[x1].role_runner.name and module.github_runner.runners[x2].role_runner.name as each multi runner configuration creates its own role for runners.

```
resource "aws_iam_role_policy_attachment" "attach-custom-policy-to-github-runner-role" {
  for_each = module.module.github_runner.runners
  role       = each.value.role_runner.name
  policy_arn = aws_iam_policy.custom-policy.arn
}

resource "aws_s3_bucket_versioning" "versioning" {
  for_each = module.github_runner.binaries_syncer # for each unique combination of runner types supported(linux-x64,windows-x32,mac-arm64) the syncer creates a different bucket. 
  bucket = each.value.bucket.id
  versioning_configuration {
    status = "Enabled"
  }
}

You can create a PR for supporting versioning on the runner binary syncer module if you would like.
Let me know if this resolved your issue!

**Comment by GuptaNavdeep1983** [comment]
The bucket versioning has been provided as per this PR, https://github.com/philips-labs/terraform-aws-github-runner/pull/3108
