### ISSUE TITLE
Will terraform-aws-github-runner takes care of cleanup and resource tagging ??

### ISSUE THREAD

**Issue by swathida-byte** [philips-labs/terraform-aws-github-runner#3249]
Please provide more details on how cleanup and resource tagging are done , else can the plugin be installed into this which takes care of cleanup and resource tagging

**Comment by npalm** [comment]
We suggest to tag resources via the provider. Resources created by the lambda are tagged. Tags are used to enforce cleanup of ec2 instances.

**Comment by swathida-byte** [comment]
how to tag the resources
