### ISSUE TITLE
Amazon Linux 2023 runners are not registering with GitHub

### ISSUE THREAD

**Issue by ay0o** [philips-labs/terraform-aws-github-runner#3263]
```
 ami_filter = {
    name = ["al2023-ami-2023.*.*.*-kernel-*.*-x86_64"]
  }
```

Runners created with this AMI filter are not registered with GitHub. The event is triggered and the Lambda created the EC2, but then the runner is not registered in GitHub.

Had to downgrade to the default Amazon Linux 2.

**Comment by ay0o** [comment]
The issue is because the tool is relying on tools that no longer exist in this AMI.

```
/var/lib/cloud/instance/scripts/part-001: line 19: amazon-linux-extras: command not found
```

**Comment by ay0o** [comment]
Modifying the user-data template to install docker using `yum install -y docker` works, however, the runner installation fails in a later stage, now because it's not properly identifying the OS as linux, even if `runner_os` and `runner_architecture` are set to `linux` and `x64`.

```
Libicu's dependencies is missing for Dotnet Core 6.0
Execute sudo ./bin/installdependencies.sh to install any missing Dotnet Core 6.0 dependencies.
```

https://github.com/philips-labs/terraform-aws-github-runner/blob/main/modules/runners/templates/install-runner.sh#L48

**Comment by visuman** [comment]
Facing the same issue trying to use an ubuntu image
```
        ami_filter      = { name = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230516"] }
        ami_owners      = ["099720109477"]
```

**Comment by logalize** [comment]
> Facing the same issue trying to use an ubuntu image
> 
> ```
>         ami_filter      = { name = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230516"] }
>         ami_owners      = ["099720109477"]
> ```

The same for me =(

**Comment by empeekdev** [comment]
Any updates on this issue?

**Comment by ay0o** [comment]
this seems to be working now, but still no reply from any of the maintainers...

**Comment by ay0o** [comment]
it seems they are working on this on https://github.com/philips-labs/terraform-aws-github-runner/pull/3437. Don't know why this issue was never updated.
