### ISSUE TITLE
Scale down function should ignore runners part of the pool

### ISSUE THREAD

**Issue by sgametrio** [philips-labs/terraform-aws-github-runner#3265]
As it happens already with the `idle_config`, scale down Lambda function doesn't terminate runners that are meant to stay idle. This is fine when using "persistent" runner configuration, and it's the expected behaviour.

When using "ephemeral" runners, the suggestion is to keep a pool of runners, ready to pick up jobs if something wrong happens at the scale-up time or to speed up the job execution. The issue is that scale down function terminates the runners in the pool because they are detected as `idle`. 

Shouldn't be the same behaviour between idle and pool runners?

**Comment by GuptaNavdeep1983** [comment]
@sgametrio Thanks for creating this issue. 

This behavior is maintained to ensure that the runners stay ephemeral. If we avoid deleting the runners, the jobs would get a runner which is previously used by another job and would not be ephemeral anymore!

**Comment by sgametrio** [comment]
@GuptaNavdeep1983 thanks for your answer. I don't fully understand though. The ephemeral runners are "destroyed" (won't listen for another job) after they run their first one. 

So it will never happen that they run 2 jobs on the same machine. Because once they are the chosen one, they will get unregistered and terminated no?

**Comment by GuptaNavdeep1983** [comment]
@sgametrio I agree the problem exists and probably we should use pool config in scale down to not kill them. As a workaround idle_config can be used with ephemeral runners which is matched to pool_config resulting in keeping those runners from being terminated.

**Comment by sgametrio** [comment]
@GuptaNavdeep1983 Oh! Now I get it.

I thought `idle_config` and `pool_config` where kind of alternative solutions to the same problem. I agree that by default it would be nice that the `pool_config` is respected by the scale_down function.

To summarize: workaround that has been tested is to set `idle_config` to have same number of replicas of the `pool_config`.

I will let @GuptaNavdeep1983 decide if the current setup is fine or if the (as suggested by the title of the issue) scale down function should ignore runners part of the pool. And therefore feel free to close in case you think so.

**Comment by GuptaNavdeep1983** [comment]
@npalm Do you think this issue can be closed with this summary above?

**Comment by npalm** [comment]
Maybe we should explain it all a bit better in the readme.

- idle_config: is for non ephemeral runners. This to avoid runner instances are terminated to keep some runners active to process job. This is a kind of legacy before ephemeral runners were available.
- pool: the pool keep a set of runners available based (org only). This function was added to ensure missed events got processed for ephemeral runners. The pool is not limitted to ephemeral runners, can be used with non-ephemeral as well (not tested).
