### ISSUE TITLE
Require SSL Interaction with S3 Bucket

### ISSUE THREAD

**Issue by sgtoj** [philips-labs/terraform-aws-github-runner#3277]
Can the S3 bucket policy be updated to restrict access to the bucket to be via SSL only? A sample of the policy is below. I can submit PR.

```tf
data "aws_iam_policy_document" "bucket_policy" {
  sid       = "ForceSSLOnlyAccess"
  effect    = "Deny"
  actions   = ["s3:*"]
  resources = [local.bucket_arn, "${local.bucket_arn}/*"]

  principals {
    identifiers = ["*"]
    type        = "*"
  }

  condition {
    test     = "Bool"
    values   = ["false"]
    variable = "aws:SecureTransport"
  }
}
```

**Comment by GuptaNavdeep1983** [comment]
@sgtoj, Thanks for reporting this issue. 

Can you please create a PR?

**Comment by sgtoj** [comment]
PR created: https://github.com/philips-labs/terraform-aws-github-runner/pull/3342

**Comment by ryanoolala** [comment]
thanks i'm looking for this!

**Comment by sgtoj** [comment]
I am closing because #3342 was merged.
