### ISSUE TITLE
SSM Permissions in scale up policy

### ISSUE THREAD

**Issue by harsha-chamarthi** [philips-labs/terraform-aws-github-runner#3294]
Why does it need permissions to all of ssm to https://github.com/philips-labs/terraform-aws-github-runner/blob/main/modules/runners/policies/lambda-scale-up.json#LL27C28-L27C28 ?

**Comment by GuptaNavdeep1983** [comment]
@harsha-chamarthi, Thanks for raising an issue.
Would you be able to create a PR to restrict the permissions to appropriate prefix in the ssm path?
