### ISSUE TITLE
Upgrade aws provider to V5

### ISSUE THREAD

**Issue by rsavage-nozominetworks** [philips-labs/terraform-aws-github-runner#3322]
Please upgrade your aws provider to V5 to stay current with the community.

**Comment by GuptaNavdeep1983** [comment]
@rsavage-nozominetworks Thanks for creating this issue. A PR has already been submitted:
https://github.com/philips-labs/terraform-aws-github-runner/pull/3315/files

**Comment by darren-recentive** [comment]
Hi @GuptaNavdeep1983, thanks for the hard work :)
Any chance this could get merged/release this week? 🙏 
https://github.com/philips-labs/terraform-aws-github-runner/pull/3324

**Comment by npalm** [comment]
PR is merged, so closing the issue
