### ISSUE TITLE
Multi-runner example exception - "Resource not accessible by integration"

### ISSUE THREAD

**Issue by MyroTk** [philips-labs/terraform-aws-github-runner#3332]
I'm trying to use the multi-runner example and ran into an issue where an instance is not being created and the scale-up lambda logs show:
```
    "level": "WARN",
    "message": "Ignoring error: Resource not accessible by integration",
    "service": "runners-scale-up",
```

I have successfully gotten default and arm examples to run, but the multi-runner lambdas are throwing this exception. I'm using the same AWS credentials and GitHub WebApp as for the other examples.

I tried changing the permissions of the IAM user, but no success.

**Comment by BGarber42** [comment]
This is a GitHub permissions issue not an AWS IAM Issue. 

I was running into this but found that I wasn't specifying `enable_organization_runners` properly for the runners so when it was trying to create the runner tokens it was scoping them to the wrong project.

**Comment by MyroTk** [comment]
> This is a GitHub permissions issue not an AWS IAM Issue.
> 
> I was running into this but found that I wasn't specifying `enable_organization_runners` properly for the runners so when it was trying to create the runner tokens it was scoping them to the wrong project.

This was solved my problem, thank you so much :D
