### ISSUE TITLE
Issue building ubuntu-jammy image via packer

### ISSUE THREAD

**Issue by JohnShortland-Catapult** [philips-labs/terraform-aws-github-runner#3353]
When I try build the image using packer I get the following error:

` 
githubactions-runner.amazon-ebs.githubrunner: You can now run: /usr/local/bin/aws --version
==> githubactions-runner.amazon-ebs.githubrunner: Uploading /var/folders/jl/3t8fpwpn2jx_qr978bdbbg_w0000gp/T/pkr-file-content2694978411 => /tmp/install-runner.sh
    githubactions-runner.amazon-ebs.githubrunner: pkr-file-content2694978411 2.31 KiB / 2.31 KiB [===========================================================================================================================================================================================================================================================================] 100.00% 0s
==> githubactions-runner.amazon-ebs.githubrunner: Provisioning with shell script: /var/folders/jl/3t8fpwpn2jx_qr978bdbbg_w0000gp/T/packer-shell609200073
    githubactions-runner.amazon-ebs.githubrunner: ubuntu
==> githubactions-runner.amazon-ebs.githubrunner: : invalid option
==> githubactions-runner.amazon-ebs.githubrunner: Provisioning step had errors: Running the cleanup provisioner, if present...
`

The only change I made was I set the default value for the runner version to 2.306.0 which is the latest. Anyone have any ideas? If I switch the default value for the runner version back to null, I get an error about the version not being set at the same stage.

**Comment by sdarwin** [comment]
You say that you're changing the runner version.   I believe this isn't necessary. Notice the description message "The latest release will be fetched from GitHub if not provided."

```
variable "runner_version" {
  description = "The version (no v prefix) of the runner software to install https://github.com/actions/runner/releases. The latest release will be fetched from GitHub if not provided."
  default     = null
}
```

   
Install the latest version of packer.

Then, what happens if you try the following, from scratch, in a new directory?

```
git clone https://github.com/philips-labs/terraform-aws-github-runner
cd terraform-aws-github-runner/images/ubuntu-jammy
packer init
packer build .
```

**Comment by JohnShortland-Catapult** [comment]
Thanks for the response, so I did the steps above after deleting the previous folder and have the same error:

`    githubactions-runner.amazon-ebs.githubrunner: You can now run: /usr/local/bin/aws --version
==> githubactions-runner.amazon-ebs.githubrunner: Uploading /var/folders/jl/3t8fpwpn2jx_qr978bdbbg_w0000gp/T/pkr-file-content1370279094 => /tmp/install-runner.sh
    githubactions-runner.amazon-ebs.githubrunner: pkr-file-content1370279094 2.31 KiB / 2.31 KiB [===========================================================================================================================================================================================================================================================================] 100.00% 0s
==> githubactions-runner.amazon-ebs.githubrunner: Provisioning with shell script: /var/folders/jl/3t8fpwpn2jx_qr978bdbbg_w0000gp/T/packer-shell2630984685
    githubactions-runner.amazon-ebs.githubrunner: ubuntu
==> githubactions-runner.amazon-ebs.githubrunner: : invalid option
==> githubactions-runner.amazon-ebs.githubrunner: Provisioning step had errors: Running the cleanup provisioner, if present...
==> githubactions-runner.amazon-ebs.githubrunner: Terminating the source AWS instance...`

I am on macOS (x64), packer version is 1.9.1 installed via brew.

**Comment by JohnShortland-Catapult** [comment]
Seems to be an issue with macOS, ran it in a Bash shell in macOS and had the same problem, ran it in a linux VM, has gotten past the step it was failing on, so fingers crossed.

**Comment by JohnShortland-Catapult** [comment]
While this is a workaround, I will continue to dig in over the weekend as I would like to fix this so it works on macOS.
