### ISSUE TITLE
Lambda Function (scale_up) issue, upgrading to v3.5.0 from 3.4.0

### ISSUE THREAD

**Issue by razor54** [philips-labs/terraform-aws-github-runner#3358]
Hi, 
I had the following issue when upgrading from v3.4.0 to v3.5.0. The lambda function upload to s3 failed due to Missing security header for some reason.

```
module.runners.module.runners.aws_lambda_function.scale_up: Modifications complete after 24s [id=***-github-runner-scale-up]
╷
│ Error: putting S3 object ACL: MissingSecurityHeader: Your request was missing a required header
│ 	status code: 400, request id: 6FAZ1RKQHQ4XD3QT, host id: FzemznfMyl8OyXwKONVlG5XbSXJXs6gVxIMArTA/1T2hSI43w6owMJofMWxGDOmPuYvp5Uaa6NY=
│
│   with module.runners.module.runner_binaries[0].aws_s3_object.trigger,
│   on .terraform/modules/runners/modules/runner-binaries-syncer/runner-binaries-syncer.tf line 150, in resource "aws_s3_object" "trigger":
│  150: resource "aws_s3_object" "trigger" {
│
╵
```

after running the terraform apply again, there was no state change so nothing happened. Is this an issue?

**Comment by GuptaNavdeep1983** [comment]
@razor54, Thank for you reporting this issue. More details about the similar issue reported by community [here](https://github.com/hashicorp/terraform-provider-aws/issues/31633).

**Comment by GuptaNavdeep1983** [comment]
@razor54 Do you want to keep this issue open. Did you end up changing something to circumvent this warning?

**Comment by razor54** [comment]
you can close the issue. it is not on this project's side either way.
