### ISSUE TITLE
Support public SSM Parameters for the AMI

### ISSUE THREAD

**Issue by sblack4** [philips-labs/terraform-aws-github-runner#3363]
HI :D 

I'm using `v2.6.1` of the module 

I was trying to use a public SSM param: `/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id` mentioned [on the ubuntu docs](https://ubuntu.com/server/docs/cloud-images/amazon-ec2)

The IAM role for the github-scale-up lambda gets permissions for the SSM param assuming it's in the present account (not my real account ID), `arn:aws:ssm:us-east-1:1234567890:parameter/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id`

But in fact the ARN doesn't show an account:
```
aws ssm get-parameters --names \                                                           
     /aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id
{
    "Parameters": [
        {
            "Name": "/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id",
            "Type": "String",
            "Value": "ami-01e076d5c9e040974",
            "Version": 276,
            "LastModifiedDate": "2023-06-30T22:58:34.249000-04:00",
            "ARN": "arn:aws:ssm:us-east-1::parameter/aws/service/canonical/ubuntu/server/20.04/stable/current/amd64/hvm/ebs-gp2/ami-id",
            "DataType": "aws:ec2:image"
        }
    ],
    "InvalidParameters": []
}
```

Could we modify the `github-actions-ami-id-ssm-parameter-read` policy to account for this? Maybe we could use the [terraform SSM parameter data source](https://registry.terraform.io/providers/hashicorp/aws/5.8.0/docs/data-sources/ssm_parameter) to make sure we've got the correct ARN?  

Thank you!

**Comment by sblack4** [comment]
Right now my work-around is to attach another policy with the requisite access to the scale-up role:

```
resource "aws_iam_role_policy_attachment" "role_scale_up_ssm" {
  role       = module.runners.runners.role_scale_up.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess"
}
```

**Comment by GuptaNavdeep1983** [comment]
@sblack4 Thanks for creating an issue for the repository. Can you create a PR for this proposed change?
