### ISSUE TITLE
Add instance id to labels

### ISSUE THREAD

**Issue by maschwenk** [philips-labs/terraform-aws-github-runner#3376]
Sometimes to test things like caching behavior, it's helpful to be able to directly target a Runner among a pool of Runner. It'd be cool if one of the auto-applied labels was the EC2 instance id.

Even a `uuid` label attached to each instance would be fine. I'm happy to add a PR to add this functionality, just unsure if there's an existing way to do this.

One thing I tried was just adding a `uuid` to the `runner_extra_labels` but that doesn't work because it's obviously static. Obviously a simple solution here is just to create a Runner group that only one instance gets assigned to, but it's nice to be able to do this targeting at any time.

**Comment by npalm** [comment]
Do I understand you correctly, do you want to add a dynamic label to a runner. And next update your workflow with the dyanmic label? This only will work for non-ephemeral runners, as logn they are running. Each new runner wil have a new unqique label. Which requires you to continuously update your worklow.

**Comment by maschwenk** [comment]
Yep use-case is for non-ephermal runners. Basically a scenario like:

1. Test runs on instance X
2. Test fails on instance X, in a strange way that seems specific to that instance
3. I want to see if the test will fail in the same way on instance X if it runs again
4. I add the instanceid (or other sticky identifier) to the `runs-on`
5. Guaranteed to run on that machine again if I trigger it (obviously provided the instance is still up)

**Comment by npalm** [comment]
In general this is already possible. You have the following options

- Inject your own userdata to the module, you can 100% control the labels that got created.
- Build your own AMI, and use your own userdata script

**Comment by maschwenk** [comment]
@npalm 👍🏼 sounds good, that's what I figured was just making sure there wasn't another entrypoint that would be configurable in IaC. Closing.
