### ISSUE TITLE
Instances are not getting created

### ISSUE THREAD

**Issue by papunsenapati07** [philips-labs/terraform-aws-github-runner#3405]
Hey Team, no instances are getting created after the modules are deployed. I am using latest version. The logs from lambda scale up are below.
{
    "level": "WARN",
    "message": "Ignoring error: secretOrPrivateKey must be an asymmetric key when using RS256",
    "service": "runners-scale-up",
    "timestamp": "2023-08-02T09:43:02.223Z",
    "xray_trace_id": "1-64ca2524-c5f4697a38bfba5f47e8543d",
    "region": "ap-southeast-2",
    "environment": "multi-runner-linux-x64-ubuntu",
    "aws-request-id": "23d7cf0e-0911-5f0b-8d36-924a2e4500cd",
    "function-name": "multi-runner-linux-x64-ubuntu-scale-up",
    "module": "lambda.ts"
}

Below is the tags used in the job, the webhook gets triggered successfully.
![image](https://github.com/philips-labs/terraform-aws-github-runner/assets/36064005/a1b03ea8-6aa3-4d46-9755-c7745b6e26db)

Nothing after this, any help is appreciated.

**Comment by utahcon** [comment]
Hey mate, running into this same issue. Can you help me understand how you got passed it?
