### ISSUE TITLE
Instances getting killed instantly

### ISSUE THREAD

**Issue by Haagy** [philips-labs/terraform-aws-github-runner#3422]
Hi Team,
I'm currently encountering challenges that I'm unable to resolve on my own.

The module is set up with parameters related to Amazon Machine Image (AMI). It appears that the webhooks and Lambdas are functioning as anticipated, as indicated by the initiation of instances.
```
{
   "level":"INFO",
   "message":"Created instance(s): i-0093b5e100993fc49",
   "service":"runners-scale-up",
   "timestamp":"2023-08-14T09:12:14.083Z",
   "xray_trace_id":"1-64d9efec-0883e8be18fa487709d9660b",
   "module":"runners",
   "region":"eu-central-1",
   "environment":"github-action-runners",
   "aws-request-id":"6590e40b-f287-5862-9fcf-b95800a30f60",
   "function-name":"github-action-runners-scale-up",
   "runner":{
      "type":"Org",
      "owner":"TEST"
   },
   "github":{
      "event":"workflow_job",
      "workflow_job_id":"4593500"
   }
}
```
The runner within the AMI is initiated using a systemd service. This service triggers the execution of a script inspired by the content found at https://github.com/philips-labs/terraform-aws-github-runner/blob/main/modules/runners/templates/start-runner.sh.

However, the instances are instantly terminated. Upon investigation, there are no apparent errors observed in CloudWatch logs related to scale-up activities, and the LogGroups dedicated to runners appear to be empty.

As a troubleshooting step, a test was conducted by manually launching an instance from a launch template. This test yielded successful outcomes, with the instance remaining operational and the runner successfully registered within the GitHub Enterprise Server (GHES) environment.

Any help is very welcome.

Best regards
Alex

**Comment by tlanghals-uturn** [comment]
We are seeing this exact same issue with the latest 4.1.0 version.  The instance launched and immediately terminates with the transition reason of "Client.InternalError: Client error on launch".  This error is referenced as a [KMS permissions error](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-launch.html) but occurs even when setting volume properties to non-encrypted.

**Comment by Haagy** [comment]
Hi @tlanghals-uturn,
I hadn't initially recognized the reason for the transition, but I can now confirm that this was indeed the same behavior. We are also using `4.1.0`. I appreciate your attention to this detail and pointing it out. It helped me a lot!

Regarding our project, we use KMS key for image encryption.

What solved the issue for me was the inclusion of the following configuration within the module:
```
...
  block_device_mappings           = [{
    "kms_key_id": "arn:of:privary:key"
  }]

  ami_kms_key_arn = "arn:of:privary:key"
...
```
I'd like to highlight that I also attempted to use `aws_kms_alias.me_kms.arn` at this point, although it didn't yield the desired outcome.

**Comment by npalm** [comment]
Can you reproduce the issue with one of the module examples. We have seens similar issues in the past when we not grant access to the KMS key for EBS encryption to the lambda. Our EBS encryption is not part of the moudle.

**Comment by tlanghals-uturn** [comment]
We were able to resolve this after investigating the KMS CloudTrail events.  I had not realized we had EBS default encryption enabled on this account so it was indeed trying to encrypt the volume even with encrypted set to false on the **block_device mappings**.

Even after realizing this default EBS configuration, the **ami_kms_key_arn** parameter does not enable enough privileges on the scale_up lambda to successfully launch an instance with a customer managed key and EBS default encryption.  To fix this we added the **kms:GenerateDataKeyWithoutPlaintext** to the scale_up role.

```terraform
# Add additional policy to decrypt EBS volumes
# This fixes the lack of kms:GenerateDataKeyWithoutPlaintext permissions
data "aws_iam_policy_document" "scale_up_additional_policies" {
  statement {
    actions   = ["kms:GenerateDataKeyWithoutPlaintext"]
    resources = [data.terraform_remote_state.core.outputs.kms_key_arns["ebs"]]
  }
}

resource "aws_iam_policy" "ScaleUpEBSKMSPolicy" {
  name        = "ScaleUpEBSKMSPolicy"
  description = "Allow access to EBS KMS key"
  policy      = data.aws_iam_policy_document.scale_up_additional_policies.json
}

resource "aws_iam_role_policy_attachment" "ScaleUpEBSKMSPolicy" {
  role       = module.runners.runners.role_scale_up.name
  policy_arn = aws_iam_policy.ScaleUpEBSKMSPolicy.arn
}
```

**Comment by Haagy** [comment]
Since both problems are solved I am closing this issue.

Thank you for your help @tlanghals-uturn and @npalm
