### ISSUE TITLE
Issues with roles upgrading from 1.18.2 to 4.*

### ISSUE THREAD

**Issue by mattgodbolt** [philips-labs/terraform-aws-github-runner#3454]
I just updated to 4.1.2, and then 4.2.0 from 1.18.2, and unfortunately my (freshly rebuilt) image is failing at startup with (after logging in to my Ec2 instance quickly):

```
user-data[1568]: An error occurred (AccessDeniedException) when calling the GetParametersByPath operation: User: arn:aws:sts::REDACTED:assumed-role/ce-ci-runner-role/i-REDACTED is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:us-east-1:052730242331:parameter/ce-ci/runner because no identity    -based policy allows the ssm:GetParametersByPath action
```

As best I can tell the instnace has the correct permissions:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ssm:DeleteParameter",
                "ssm:GetParameters",
                "ssm:GetParameter"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:ssm:us-east-1:REDACTED:parameter/github-action-runners/ce-ci/runners/tokens*"
        },
        {
            "Action": [
                "ssm:GetParameter",
                "ssm:GetParameters",
                "ssm:GetParametersByPath"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ssm:us-east-1:REDACTED:parameter/github-action-runners/ce-ci/runners/config",
                "arn:aws:ssm:us-east-1:REDACTED:parameter/github-action-runners/ce-ci/runners/config/*"
            ]
        }
    ]
}
```

which looks right: I checked the instance has this role applied too (as best I can understand).

I saw #3289 and #2989 which both have the same symptoms but I can't see that I'm doing the same things wrong.

I'm running our own AMI built from a contemporary 4.2.0 "Ubuntu focal" example with just a little extra installation in the custom script. Happy to share.

Ideas welcomed on how to debug! Thanks in advance!

**Comment by GuptaNavdeep1983** [comment]
@mattgodbolt, there is a difference between the permissions and the error in terms of ssm path mentioned. 

Permissions suggest that access is given to arn:aws:ssm:us-east-1:REDACTED:parameter/**github-action-runners**/ce-ci/runners/tokens* which includes a prefix of github-action-runners in the path, whereas the error says that the parameter path doesnt include that prefix.

**Comment by mattgodbolt** [comment]
Thanks for spotting that @GuptaNavdeep1983 -- I wonder where these path names are coming from and why they don't agree!

**Comment by mattgodbolt** [comment]
Interestingly the text `github-action-runners` does not appear anywhere in my repo, nor in the `terraform-aws-github-runner` repo. I wonder where it's coming from...

**Comment by mattgodbolt** [comment]
So it looks like this changed in 922ef99be52f8d780ec711f33e1f6c447dbedffd and c6badbf9e1cf6bbcdd6a9841b1f342ef5fbd1ed3 and now perhaps in order to reclaim the old behaviour I need to set `instance_profile_path`. not 100% on this but workign on it. I'd still imagine the terraform would make an internally consistent configuration.

**Comment by mattgodbolt** [comment]
I dug more and found:
```
variable "prefix" {
  description = "The prefix used for naming resources"
  type        = string
  default     = "github-actions"
}
```
which makes (some) sense... but that's not _quite_ the same `github-action-runners` ("action" singular).

**Comment by mattgodbolt** [comment]
So in the `start-runner.sh` in the repo:

```
parameters=$(aws ssm get-parameters-by-path --path "/$environment/runner" --region "$region" --query "Parameters[*].{Name:Name,Value:Value}")
```

this (to me) is pretty clear that the path should be just `/ce-ci/runner`. So now: perhaps I need to taint a bunch of things in the terraofrm to make it "regenerate" the ssm stuff with the (correct?) path. It seems to have cached some old vesitial `github-action-runners` that isn't present any more in anything.

**Comment by mattgodbolt** [comment]
Ok! It seems likely that my self-built docker image is out of date: I was on the `develop` branch. But; on `main` there's some differences in the packer stuff. So...I'll dig more there :)

**Comment by mattgodbolt** [comment]
Fixed!

My version of the packer image was out of step/sync with the code elsewhere! Once I had updated it to be based off the v4.2.0 (plus a small patch I have to set a Iam profile on the packer instance)...everything started working!

Sorry for the noise; thanks again @GuptaNavdeep1983 for giving me the tools to find the issue myself.
