### ISSUE TITLE
Support for Windows runners

### ISSUE THREAD

**Issue by jamtur01** [philips-labs/terraform-aws-github-runner#347]
I've had a poke at the module and I am presuming this currently only supports Linux-based runners? Any plans to add Windows runner support?

**Comment by sjagoe** [comment]
There are a couple sides to this:
- Caching the runner binary (the `runner-binaries-syncer` lambda in this project). That only supports linux right now (https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runner-binaries-syncer/lambdas/runner-binaries-syncer/src/syncer/handler.ts#L59).
- Provisioning the runner on Windows. I don't know anything about provisioning Windows on AWS, but #142 may just provide enough to set up Windows using a user-data script: https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2-windows-user-data.html

I think the main work here would be making the runner-binaries-syncer grab the windows runner, then on the user side, you would need to work on a user-data script that would provision enough on the worker to install the runner.

**Comment by npalm** [comment]
@sjagoe agree to your notes. I think creating a install script for windws, and starting the runner is the biggest chuck. PR's are welcome  :)

**Comment by maths22** [comment]
I think with #1476 merged this can be closed

**Comment by npalm** [comment]
Windows runners are supported, so closing the issue.
