### ISSUE TITLE
Support block_duration_minutes for spot instances

### ISSUE THREAD

**Issue by tedparagon** [philips-labs/terraform-aws-github-runner#3470]
We had to stop using spot instances because we were getting too many evictions (dozens per day) and the developer overhead of dealing with failed workflows wasn't worth the savings. Switching to ephemeral runners wouldn't help since our jobs might run for an hour or more and many times the spot instance was up for less than 10 minutes. However since the spot savings are significant and the duration of the jobs are fairly well defined the use of [EC2 Spot Blocks](https://aws.amazon.com/blogs/aws/new-ec2-spot-blocks-for-defined-duration-workloads/) could solve our eviction problem.

The Terraform `aws_launch_template` supports `block_duration_minutes` on the [`instance_market_options`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#market-options). Being able to set this would ensure the spot instance was running long enough to process the job.

Looking at the code though it is unclear how/where this should be implemented. It looks like a lot of the launch template configuration is actually handled in the scale-up lambda and not in the template definition.

This is a great project and I love the configurability. We're just trying to reign in some of the costs.

**Comment by npalm** [comment]
You observation about the launch template is right. The launch templates contain some basic, but more detailed or fine-grainded options are handled by the scale-up lambda. Everything that more dynamic is taken care by the lambda, the static settings. The onces know when terraform is executedaed are part of the launch template.

In this case I think it could be a static value, as long no default is required. Feel free to raise a PR

**Comment by tedparagon** [comment]
I missed the update at the top of the page I linked to. This is no longer supported by AWS. 😢

> Update July 2021 – Spot Instances with a defined duration (also known as Spot blocks) are no longer available to new customers as of July 1, 2021. For customers that have previously used the feature, we will continue to support Spot Instances with a defined duration until December 31, 2022. If your workload is interruption tolerant, we recommend that you use Spot Instances without setting a defined duration. If your workload is not interruption tolerant we recommend that you use On-Demand instances for the required duration of your workload.
