### ISSUE TITLE
lambda scale-up policy should use aws_partition for ssm_config_path template variable

### ISSUE THREAD

**Issue by JaredZieche** [philips-labs/terraform-aws-github-runner#3476]
The lambda scale-up policy contains a template variable value that hard-codes the aws partition for the `ssm_config_path` arn.
https://github.com/philips-labs/terraform-aws-github-runner/blame/3f2131f3e8bd989894f1cc58f86ec1473a27ba66/modules/runners/scale-up.tf#L102

This will result in a MalformedPolicyDocument error in other AWS partitions. Would expect this to use the `aws_partition` variable.

**Comment by carloscao0928** [comment]
Yes, I also find this problem when I rollout my code to region cn-north-1.

**Comment by carloscao0928** [comment]
Error: putting IAM role policy xxx-github-ci-al2023-lambda-scale-up-policy: MalformedPolicyDocument: Partition "aws" is not valid for resource "arn:aws:ssm:cn-north-1:xxx:parameter/github-action-runners/xxx-github-ci/al2023/runners/config/*".

**Comment by npalm** [comment]
@carloscao0928 feel free to raise a PR

**Comment by carloscao0928** [comment]
> @carloscao0928 feel free to raise a PR

ERROR: Permission to philips-labs/terraform-aws-github-runner.git denied to carloscao0928

**Comment by carloscao0928** [comment]
Already fixed, can close this issues. @JaredZieche
