### ISSUE TITLE
Jobs remain in queued status and never get processed

### ISSUE THREAD

**Issue by strophy** [philips-labs/terraform-aws-github-runner#3493]
We have a repo configured to use ephemeral runners using multi-runner config. When a run is triggered, around ~20-30 workflow jobs are pushed, but our runner limit is 15. I expect the runner count to remain at maximum until all workflow jobs in the FIFO queue are processed in sequence.

Instead, 15 runners start and a number of jobs are processed, but many jobs remain in the queued state in GitHub and never get processed. The SQS queue shows 0 messages in flight. As a result, after all runners have finished their work and zero runners are up, my PR still looks like this:
![image](https://github.com/philips-labs/terraform-aws-github-runner/assets/32928115/09e528c4-3d84-48af-b9e0-7c286bbb873e)

If I cancel one of the queued jobs and restart it, then new runners will be created, but they will process one of the other unprocessed jobs, and not the one that I restarted. This makes it nearly impossible to successfully complete CI without manually playing cat-and-mouse by cancelling and restarting jobs several times until eventually all checks have run and returned a green/red result. I suspect the error is between the GitHub App sending requests to the Webhook lambda, and the lambda creating messages in the queue. How can we debug this?

**Comment by npalm** [comment]
Some questions
- are you using repo or org level runenrs
- are you using unqique labels. With multi runners the label is used to sent a message to the que for which finally a runner is crated

**Comment by ktechmidas** [comment]
Hi @npalm 

I'm @strophy's colleague and we're trying to debug this, to answer your questions:

1) We're using org level runners
2) It's a monorepo, so as far as unique labels it does have "ubuntu-*project*" but inside it is a very large project, so it should be running 10-15 different runners for a single push at times

Some observations:

* The SQS queue is clear, there's nothing in it when we're in a "stuck" state. I also tried a Dead-letter queue, nothing flows into it
* If I add one item to the SQS queue manually, it will suddenly realize there's stuff from GH it's supposed to run (as expected)
* If we run a small job with 1-3 items, it will run them perfectly fine (as long as there's no GH queue from a previous large run)
* When a large push/PR is done, it will start 3-4 runners. The other jobs will get stuck in the described state. Here is a snippet from one of our "stuck" jobs:

```
Requested labels: self-hosted, linux, x64, ubuntu-platform
Job defined at: dashpay/platform/.github/workflows/js-checks.yml@refs/pull/1406/merge
Reusable workflow chain:
dashpay/platform/.github/workflows/dashmate.yml@refs/pull/1406/merge (1bb4885b696213bcb044e036cfc912e703b0e75d)
-> dashpay/platform/.github/workflows/js-checks.yml@refs/pull/1406/merge (1bb4885b696213bcb044e036cfc912e703b0e75d)
Waiting for a runner to pick up this job...
```

**Comment by ktechmidas** [comment]
Correction sorry, we're running repo based runners

**Comment by strophy** [comment]
I can confirm that we are using repo-level runners, and the runs are requested using unique labels as shown in the snippet above. All runners use the same labels, so there is no reason they shouldn't all result in an identical runner being created. Our multi-runner configuration can be viewed here:
- [Multi-runner configuration](https://github.com/dcginfra/tf-aws-gh-runner/blob/main/examples/multi-runner/main.tf) (based on the upstream example)
- [Runner configuration template](https://github.com/dcginfra/tf-aws-gh-runner/blob/main/examples/multi-runner/templates/runner-configs/linux-x64-platform.yaml)
- [PR showing our current attempted changes](https://github.com/dcginfra/tf-aws-gh-runner/pull/14)

My current approach to debugging this is to set the `runners_maximum_count` to 5, lower than what we intend to use in production, and then trigger a job that starts >5 runners. I then monitor SQS and CloudWatch to try and figure out when new runners are created. After some time, the SQS queue is empty, all runners complete their work, but on the GitHub side there are still jobs waiting for runners. The main thing I notice when tracking jobs through the pipeline by their GitHub Actions `workflowJobId` is that the runner created by the scale-up lambda doesn't necessarily end up running the same action that triggered its creation. But regardless, the total count of runners created should match the number of pending jobs in the end, right?

I'm also a bit confused why the ephemeral runner [docs](https://github.com/philips-labs/terraform-aws-github-runner#ephemeral-runners) recommend setting `fifo: false` but the multi-runner [example templates](https://github.com/philips-labs/terraform-aws-github-runner/blob/main/examples/multi-runner/templates/runner-configs/linux-x64-ubuntu.yaml#L6) show `fifo: true` and the `enable_fifo_build_queue` setting is recommended to be set `true` for repo-level runners. How do the runner-level `fifo` and stack-level `enable_fifo_build_queue` settings interact?

My current questions:
- How should FIFO be configured in multi-runner ephemeral configurations?
- If we enable redrive and DLQ, what is the behavior around redriving messages back to the source queue? Should this be done manually or does a lambda handle it?

**Comment by strophy** [comment]
I believe I found the source of this error. SQS was in fact performing normally. 

The cause was runners that failed to come up and register with GitHub due to an intermittent failure while running `user-data.sh` on around 20% of the runners. This would cause the runner to come up and idle until the scale down lambda killed it, and the runner never registered itself with GitHub Actions. This was causing the observed behaviour of a mismatch between the number of runners requested and the number that actually came up properly and registered themselves as ready to run a job, resulting in unfinished jobs sitting in the queue.

Thanks for letting me think this issue through here, hope it helps someone else!

**Comment by lukevalenty** [comment]
Hey @strophy, what did you do to resolve the issue? We have been seeing the same issue as you described.

**Comment by ktechmidas** [comment]
@lukevalenty I figured out we were mounting ephemeral storage in the start-runner.sh script on AWS. Our issue will only be valid for you if you're doing the same thing... :)

We hardcoded the device like this: `sudo mkfs -t xfs /dev/nvme1n1`

Had to do something like this instead:

`EPHEMERAL_DISK=$(sudo nvme list | grep 'Amazon EC2 NVMe Instance Storage' | awk '{ print $1 }')
sudo mkfs -t xfs $EPHEMERAL_DISK
sudo mount $EPHEMERAL_DISK /mnt/instance-store`

**Comment by sjelisonI** [comment]
I am seeing this issue while using the ephemeral setup (like the ephemeral example code).  In that case, I see that the scale up lambda is invoked, but the code in the scale up lambda looks like this
```
        if (currentRunners.length < maximumRunners) {
            ...
        }
        else {
            logger.info('No runner will be created, maximum number of runners reached.');
            if (ephemeral) {
                throw new ScaleError_1.default('No runners create: maximum of runners reached.');
            }
        }
```

I don’t see anything catching that ScaleError that is thrown in the ephemeral scenario (and using exceptions for expected program flow would not be the best way to code things), so to me it looks like in this scenario, when it hits the limit it simply fails. Instead of throwing an error, it seems there ought to be code called to _queue_ the request and scale when the number of runners falls below the configured maximum, but I don’t see any such code.

**Comment by strophy** [comment]
@sjelisonI I think the Lambda function can safely exit after throwing the ScaleError. The request for a runner will simply reappear in the SQS queue after the visibility timeout expires without the Lambda having deleted the message. You should be able to see this "No runner will be created ..." error in Cloudwatch Logs for the Scale Up Lambda repeating every minute (assuming you haven't changed the default visibility timeout in SQS).

**Comment by sjelisonI** [comment]
@strophy Ah, thanks, makes sense.  I see that happening.  I didn't realize the original SQS item remained in the queue in this case, and an unrelated issue made it appear like things were never processed.
