### ISSUE TITLE
Github action runners can't execute jobs

### ISSUE THREAD

**Issue by lassesteffen** [philips-labs/terraform-aws-github-runner#3534]
```
<13>Oct 10 07:10:47 user-data: Starting the runner in persistent mode
<13>Oct 10 07:10:47 user-data: 
<13>Oct 10 07:10:47 user-data: /etc/systemd/system/actions.runner.koppla-tech.i-0cf765eb2e15abb85.service
<13>Oct 10 07:10:47 user-data: â actions.runner.koppla-tech.i-0cf765eb2e15abb85.service - GitHub Actions Runner (koppla-tech.i-0cf765eb2e15abb85)
[  124.159146] cloud-init[2997]: ci-info: no authorized ssh keys fingerprints found for user ec2-user.
ci-info: no authorized ssh keys fingerprints found for user ec2-user.
<13>Oct 10 07:10:47 user-data:    Loaded: loaded (/etc/systemd/system/actions.runner.koppla-tech.i-0cf765eb2e15abb85.service; enabled; vendor preset: disabled)
<13>Oct 10 07:10:47 user-data:    Active: failed (Result: exit-code) since Tue 2023-10-10 07:10:47 UTC; 3ms ago
<13>Oct 10 07:10:47 user-data:   Process: 10158 ExecStart=/opt/actions-runner/runsvc.sh (code=exited, status=1/FAILURE)
```

I assume it's the latest github action runner from yesterday, but roughly since then, the runners fail. They start, register but then don't work correctly and don't execute any queued jobs. Do you have any idea how to fix this?

**Comment by PatrickWolleb** [comment]
Executing runsvc.sh hints at missing GLIBC_2.27/8 required by node20
```/opt/actions-runner/runsvc.sh
.path=/sbin:/bin:/usr/sbin:/usr/bin
./externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by ./externals/node20/bin/node)
./externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./externals/node20/bin/node)```

**Comment by charlesdg** [comment]
See 

- https://github.com/philips-labs/terraform-aws-github-runner/issues/3497 
- https://github.com/actions/runner/pull/2844

**Comment by safinsaf** [comment]
![image](https://github.com/philips-labs/terraform-aws-github-runner/assets/45899673/e873685c-bdde-4fc8-8052-13f215e5c2c5)

**Comment by Mogost** [comment]
Confirming this issue

**Comment by SwadhinZomentum** [comment]
This is happening for us as well :(

**Comment by aktur** [comment]
We encountered this issue when the checkout action was updated to v4. You must either upgrade the runners to use Linux 2023 or downgrade the checkout action to v3.

**Comment by Abdelrahman1993** [comment]
I am using Amazon Linux 2 and set `GITHUB_ACTIONS_RUNNER_FORCED_NODE_VERSION=node16` in _bash_profile but I am still facing this issue

**Comment by SwadhinZomentum** [comment]
I just used #3437 and it works!

**Comment by kepalas** [comment]
I'm using the default image and was able to workaround the issue using the following configuration:
```
  userdata_post_install = <<EOF
    sed -i '/\[Service\]/a Environment="GITHUB_ACTIONS_RUNNER_FORCED_NODE_VERSION=node16"' /opt/actions-runner/bin/actions.runner.service.template
EOF
```
[This comment](https://github.com/philips-labs/terraform-aws-github-runner/issues/3497#issuecomment-1754768630) helped me to figure out what I needed to do in my setup

**Comment by PatrickMilroy** [comment]
I've used the above to start the service and that seems to have resolved my issue, however I have a particular workflow that is utilizing `actions/cache@v3` and am running into a similar issue with the node runtime as detailed here  https://github.com/actions/cache/issues/1258 where the `hashFile` function still appears to use `node20`. 

Does anyone have any suggestions on how to work around this?

**Comment by ashwin-jacob** [comment]
According to GitHub Runner's latest release, they reverted the change for "Default Version of Node 20". It should go back to Node 16 now

Source: https://github.com/actions/runner/releases/tag/v2.310.1

**Comment by lassesteffen** [comment]
Solved by latest release
