### ISSUE TITLE
Add `MAX_RUNNING_TIME_IN_MINUTES`

### ISSUE THREAD

**Issue by maschwenk** [philips-labs/terraform-aws-github-runner#3574]
Problem:

We need to take runners out of rotation for a couple reasons:

1. To make sure they are replaced with new AMIs that have security patches applied
2. So we don't need to micro-manage storage/filesystem rot that could happen over many hours of running

However, because we have an Idle config that spans the whole day, there is a chance that certain runners simply do not get rotated out at all. One easy way to solve this would be to add a `MAX_RUNNING_TIME_IN_MINUTES` configuration, and just dictate that no Runner can run for longer than 24 hours (for example). Would you consider a PR for this?

**Comment by npalm** [comment]
Yes PR's are welcome. Tricky part could be to not terminate a job. We use ephemeral runners to avoid those problems.

**Comment by maschwenk** [comment]
To be clear, I'm basically just talking about a counterpart to:

https://github.com/philips-labs/terraform-aws-github-runner/blob/23fdd8b207e79ba36d3543c7fb0cf63dced7e0c8/lambdas/functions/control-plane/src/scale-runners/scale-down.ts#L96

If there is indeed tricky-ness around `not terminate a job`, wouldn't that apply to that logic as well?

**Comment by npalm** [comment]
The scale down should first de-register the runner. Which only works if no job is running. Next turn it down.

**Comment by maschwenk** [comment]
Isn't this code exactly that logic?

https://github.com/philips-labs/terraform-aws-github-runner/blob/23fdd8b207e79ba36d3543c7fb0cf63dced7e0c8/lambdas/functions/control-plane/src/scale-runners/scale-down.ts#L165-L176

It looks like `removeRunner` already handles the case of the Runner being busy and just skips over it. I think that'd be fine for this case.
