### ISSUE TITLE
slack sign up link broken

### ISSUE THREAD

**Issue by floh96** [philips-labs/terraform-aws-github-runner#3576]
The slack sign up link in https://github.com/philips-labs/terraform-aws-github-runner/blob/main/CONTRIBUTING.md is  broken.
https://philips-software-slackin.now.sh/ -> 404

**Comment by npalm** [comment]
@Brend-Smits did you created the link back in the days?

**Comment by Brend-Smits** [comment]
> @Brend-Smits did you created the link back in the days?

No, maybe @JeroenKnoops?

**Comment by npalm** [comment]
@Brend-Smits confused with this one: https://github.com/philips-labs/terraform-aws-github-runner/pull/1284
