### ISSUE TITLE
Verbose resource naming leading to AWS resource name character limit errors

### ISSUE THREAD

**Issue by lukevo247** [philips-labs/terraform-aws-github-runner#3586]
Recent change to add SSM housekeeper lambda resources are very verbose. Take for example the suffix `action-ssm-housekeeper-lambda-role` which is 35 characters alone. 

This accounts for more than half of the 64 character limit that is allowed in most AWS resources. As a result, users may find themselves in a predicament where due to company naming conventions, they are unable to update the their aws-github-runner module to the latest version. 

Please shorten the resource names so that individuals are able to use this module without having to redeploy the whole stack. This may not seem like a huge deal, however it would be fairly inconvenient to redeploy the entire stack and rebuild ami's pointing at the correct S3 bucket for the github runner binary or reconfigure the GitHub app to point at the recreated API Gateway to get around a naming problem.

Links:
https://github.com/philips-labs/terraform-aws-github-runner/pull/3577

https://github.com/philips-labs/terraform-aws-github-runner/pull/3577/files#diff-f18c7727bcfbfe0dff19344ed6b382dcf495c56fa802e85aba84436c62070cdaR82

**Comment by npalm** [comment]
Made a quick fix in #3587. But we should find a better solution for naming.
