### ISSUE TITLE
Scale down Github API responses inconsistency

### ISSUE THREAD

**Issue by maschwenk** [philips-labs/terraform-aws-github-runner#3589]
https://github.com/philips-labs/terraform-aws-github-runner/issues/1151#issuecomment-1787897208

Following up from my comment here. I can close this issue and keep it in that existing issue if that's better. TL;DR we are confident that the code that paginates through the runners from Github is working as advertised, we just think there might be a chance that Github is occasionally leaving out certain runners. We have logging around rate limiting so we've ruled that out but our logs seem to indicate that Runners are being terminated while they are healthily busy, not with memory pressure, without any clear errors in the Agent logs.

I'm wondering if you'd consider a patch to:

https://github.com/philips-labs/terraform-aws-github-runner/blob/f7e4935a03f91f06a1f542ea0accbbf49d2fe11a/lambdas/functions/control-plane/src/scale-runners/scale-down.ts#L178-L183

That would basically "double-validate" before termination. We'd re-query the API to make sure it's still missing, and *then* do the "hard" termination.

Also just curious if other folks have run into this.

**Comment by aakilin** [comment]
We have the same issue on our side. The runners shut down during the working. I can't figure out why the Lambda decides that the worker isn't busy
![image](https://github.com/philips-labs/terraform-aws-github-runner/assets/108949327/315e23d3-b68e-4a8e-9669-fb0b4035259a)

**Comment by maschwenk** [comment]
@mcaulifn also seemed to have this issue in the aforementioned issue

- https://github.com/philips-labs/terraform-aws-github-runner/issues/1151
