### ISSUE TITLE
Input Tags never apply to EC2 instance

### ISSUE THREAD

**Issue by rlove** [philips-labs/terraform-aws-github-runner#360]
We have [Service Control Policies (SCP)](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html)  that prevent EC2 instances without required internal billing tags.    

Request allow source input tags to be passed to EC2 instance.
Source Input in [/variables.tf](https://github.com/philips-labs/terraform-aws-github-runner/blob/c8076d775b5f4a74a9afd9bf208d5b99a4e74000/variables.tf#L16)
Where needed in modules [/runners/lambdas/runners/src/scale-runners/runners.ts](https://github.com/philips-labs/terraform-aws-github-runner/blob/c8076d775b5f4a74a9afd9bf208d5b99a4e74000/modules/runners/lambdas/runners/src/scale-runners/runners.ts#L86)

I am open to trying to work on this if something like this would be accepted in a PR.

**Comment by npalm** [comment]
We have the same requirement, we use the variable `tags` to pass a map of tags. The tags are used for tagging all resources there where possible. I hav also doubled checked our depoyments and our ec2 instances are tagged with the right billing tags in our case.

**Comment by npalm** [comment]
@rlove can we close the issue?

**Comment by rlove** [comment]
I must have I something else wrong.  I am going through cloud trail trying to find cause.    Go ahead and close this. I will reply on closed issue if I find a solution.   I suspect I missed a permission someplace.
