### ISSUE TITLE
Scaling up multiple instances

### ISSUE THREAD

**Issue by mogopz** [philips-labs/terraform-aws-github-runner#3606]
Hello,
I've been looking through the configuration options and couldn't see anything but is it possible to scale-up multiple instances at once?

I have a couple of builds that use matrixes/dependant steps and because the number of jobs grows as the build progresses it can take a while as it needs to wait for new instances to be provisioned.

An example of what I'm talking about is [ScaleOutFactor](https://github.com/buildkite/elastic-ci-stack-for-aws/blob/main/templates/aws-stack.yml#L337C2-L340) in Buildkite's CloudFormation template.

**Comment by npalm** [comment]
Scaling is done be default by creating runnrs for each event till a max. For org runners a pool can be defined to maintain a base capacity
