### ISSUE TITLE
How to debug issue when scale up encounters Github API error 403

### ISSUE THREAD

**Issue by bobby-lin-cdc** [philips-labs/terraform-aws-github-runner#3634]
# Background

I wonder if anyone encounters Github API error 403 when generating the Github App access token. 

![image](https://github.com/philips-labs/terraform-aws-github-runner/assets/82359686/adc067cd-955b-4f1c-a0ba-3f80617d6f5b)

It looks like the Github App permission issue but I have double checked that the permission is correct. I was able to use the private key to sign a JWT for generating the access token.

<img width="424" alt="image" src="https://github.com/philips-labs/terraform-aws-github-runner/assets/82359686/49cd9d09-3ab0-4f9b-8469-6147b4ecf3cd">

# Details

Information about the module:
- Version: `v5.4.1`

```
module "github-runner" {
  source  = "philips-labs/github-runner/aws"
  version = "5.4.1"

  vpc_id      = module.vpc.vpc_id
  subnet_ids  = module.vpc.private_subnets

  prefix = "gh-ci"

  github_app = {
    key_base64     = base64encode(file("appkey.pem"))
    id             = <<MY_APP_ID>>
    webhook_secret = random_password.random.result
  }

  webhook_lambda_zip                = "lambdas-download/webhook.zip"
  runner_binaries_syncer_lambda_zip = "lambdas-download/runner-binaries-syncer.zip"
  runners_lambda_zip                = "lambdas-download/runners.zip"

  enable_organization_runners = true
  runners_maximum_count = 20
  log_level = "debug"
  tracing_config = {
    mode = "Active",
    capture_http_requests = true,
    capture_error = true
  }
}
```

**Comment by GuptaNavdeep1983** [comment]
Please check if you are trying to create an org level runner vs repo level runner which is generally the reason for this error if everything else is configured correctly!

**Comment by FelipeLopes-systematica** [comment]
Hey @bobby-lin-cdc would you mind telling how did you solve this issue please? Thank you!
