### ISSUE TITLE
delay_webhook_event variable

### ISSUE THREAD

**Issue by sdarwin** [philips-labs/terraform-aws-github-runner#3641]
Hi,

Just discovered the variable `delay_webhook_event` isn't working as expected.

- All examples in examples/multi-runner/templates/runner-configs/ consider `delay_webhook_event` a top level variable.

- modules/multi-runner/queues.tf thinks it's a sub-component of runner_config:

```
delay_seconds               = each.value.runner_config.delay_webhook_event
```

- modules/multi-runner/README.md has an example with `delay_webhook_event` as a top level variable.  

- Later in the README it's a sub-component within runner_config again.

**Comment by GuptaNavdeep1983** [comment]
@sdarwin, thanks for reporting this issue. can you please create a PR?

**Comment by npalm** [comment]
The delay webhook event is meant to let a message wait for x seconds on a queue before picking up for example for a non-ephemeral runner to give an existing runner the chance to pick the job b before an instances is created. 

I have quickly checked the implemenation, managing the `delay_webhook_event` on runner elvel is right, it should not be top-level. This means that in my opinion the exmaples are wrong and the delay is in that cases just ignored.
