### ISSUE TITLE
Add support for API Gateway v1 for enhanced security

### ISSUE THREAD

**Issue by chrissng** [philips-labs/terraform-aws-github-runner#3667]
Currently, the API Gateway serves as the entry point to invoke the webhook Lambda function. This solution seamlessly integrates with GitHub.com; however, in certain enterprise scenarios, concerns may be raised regarding the API Gateway's potential as an attack vector. Organizations are keen on enhancing the security of the API Gateway, particularly when using GitHub Enterprise Server (GHES).

### Challenges with API Gateway V2
API Gateway V2 is used to provide a HTTP API. Due to AWS limitations, it does not support two things:
1. Making the API Gateway completely private
2. Attaching a WAF

#### Making the API Gateway completely private

In the context of a self-hosted GitHub Enterprise Server (GHES) instance, there is a requirement to deploy the entire setup (GHES + Runners) as a fully private environment. The current limitation is that API Gateway V2 lacks native support for being deployed as a private REST endpoint. This hinders the ability to create a comprehensive private deployment in organizations where the utmost privacy and security are paramount.

#### Attaching a WAF

The use of a firewall to secure entry points is a common requirement in many organizations. Unfortunately, API Gateway V2 does not directly support attaching a Web Application Firewall. As a workaround, organizations are resorting to the use of a CloudFront distribution. While this approach is viable, there remains a challenge in restricting access solely to the API via the associated CloudFront Distribution ([reference](https://aws.amazon.com/blogs/networking-and-content-delivery/restricting-access-http-api-gateway-lambda-authorizer/)).

### Proposed solution

To address the identified security concerns and limitations, we propose added support for API Gateway V1. This will empower organizationsto implement the following crucial security measures:
1. With API Gateway V1, it becomes feasible to deploy the API Gateway as a private REST endpoint. This enhancement aligns with the requirements of organizations, especially those opting for GitHub Enterprise Server (GHES), allowing them to deploy the entire GHES + Runners setup in a fully private manner via VPC Private Link.
2. API Gateway V1 provides native support for WAF, eliminating the need for a workaround involving CloudFront. This streamlines the security architecture, offering a more straightforward approach to attach WAF to the API Gateway.

Supporting API Gateway V1 addresses security aspects observed in certain enterprise scenarios. This enhancement enables organizations to deploy a more robust, private, and secure solution while utilizing GitHub (or GHES) and AWS services. By incorporating API Gateway V1, we ensure that security remains at the forefront of our solution, meeting the diverse needs of enterprise customers.

This proposal aims to initiate discussions and gather feedback on the feasibility and urgency of implementing support for API Gateway V1. Additionally, we are considering to further contribute to this proposal with an implementation by submitting a pull request.

**Comment by PavelsJarkovojs** [comment]
I'd like to bring attention to another issue with AWS API Gateway V1, particularly its regional availability. 
In certain regions (I guess new regions), like Zurich (eu-central-2), AWS supports only the REST API version (API Gateway V1) and not the HTTP API (API Gateway V2).

**Comment by npalm** [comment]
@chrissng thank you for opening the discussion. We aware of the limitation. The API GW v2 was chooosen with the expectation that it will support the same features as v1. But after 3 years this seems not the case. The other reason was costs. V2 is cheaper.

## Future approach
I started a few weeks ago refatoring the webhook. To make it easier to split different part the webhook. My thought was to put the events on an event-bus before dropping them in the the runner dependec lambda code. This to allow to use the events for other logic as wel. The second goal with this approach was to be more flexible on the way how to connect to the internet.

The thought is to suppor two options, with option 1 as the default. Option 2 to allow to tailor or a basic setup.

### Option 1
1. API gw V1, to support WAF.
2. Webhook to accept event (check signature)
3. Accepted events submit to event bus (eventbridge)
4. Target on the bus to lambda webhook (function dispatch). To drop message to relevant runner queue.


### Option 2
In this option only a webhook lambda will be created, Depending on configuration attribute a webhook endpoint is created or not. When not created, the user can hook the webhook as target to an own API GW, Eventbus e.g.
1. Webhook receives and check event 
2. Webhook dispatch event to runner queue.

The webhook lambda code will remain one distribution, but with different handlers we can support the 2 configurations above. 

By enabling the eventbride we allow more tailored integration. And with the basic option webhook without endpoint we allow any custom integration.

**Comment by jffz** [comment]
Hi, is there any news on this topic ?
