### ISSUE TITLE
Lambda Trigger Issue---Spot Instance Creation Problem---Workflow Execution and Runner Installation

### ISSUE THREAD

**Issue by rohanlucifer** [philips-labs/terraform-aws-github-runner#3679]
I have been working with this module that creates all the necessary resources, like there were 78 resources that has been created in AWS, after resource creation when I use the Lambda invoke command, the response I am receiving is 200 However, I am facing issues with the Lambda trigger, as it does not seem to be working. Additionally, the spot instances are not being created. I have referred to this documentation 
"https://medium.com/philips-technology-blog/scaling-github-action-runners-a4a45f7c67a6" 
but I am unsure about where to install the runner to execute the workflow. Could someone please provide clarification on these problems?

**Comment by rohanlucifer** [comment]
@imphil please can you help on this

**Comment by imphil** [comment]
Unfortunately not.
