### ISSUE TITLE
Feature Request: Adding job runtimes to webhook logs

### ISSUE THREAD

**Issue by winwinashwin** [philips-labs/terraform-aws-github-runner#3687]
### Discussed in https://github.com/philips-labs/terraform-aws-github-runner/discussions/3686

<div type='discussions-op-text'>

<sup>Originally posted by **winwinashwin** December 23, 2023</sup>

Motivation
---
I would like to monitor our CI runtimes at job-level across our organization. A simple way to go about this would be to craft a cloudwatch query to filter the job logs from the webhook lambda and graph the runtimes. The `completed` event logs have the `started_at` and `completed_at` datetime fields but cloudwatch query syntax does not support parsing human readable timestamps as of today (according to official docs). 

Computing the runtime within the lambda and adding this field to the logs will allow monitoring CI runtimes in cloudwatch natively without any hassle.

---

If approved I would love to open a PR for this feature. I believe this should be straightforward addition right about [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/9a2ed66aa5004b5ad41106908af48665e49d32f6/lambdas/functions/webhook/src/webhook/index.ts#L137)
</div>

**Comment by winwinashwin** [comment]
@npalm Any thoughts on this?

**Comment by npalm** [comment]
In general the thought is to let the runner part only take care of running jobs. This to ensure all the capacity is used for scaling and ensuring runners become available. HOwever we also have the need for monitor the behavior. For that we have introduced the option to deliver the events to a secondary queue. Which can be used for analatics. This feature is marked as experimental.

The longer termm goal is
- to move to the event bridge, to allow routing of events for different purpose
- provide analatyics option as part / along this module as well

**Comment by winwinashwin** [comment]
So if I need to monitor my CI infra you recommended I enable the experimental secondary queue, consume and log computed metrics from there?

**Comment by npalm** [comment]
@winwinashwin that is the only option we offer today However I would hope we find some time to refactor and move to the event bridge.
