### ISSUE TITLE
Issue in functionality of enable_workflow_job_events_queue 

### ISSUE THREAD

**Issue by GuptaNavdeep1983** [philips-labs/terraform-aws-github-runner#3711]
# Problem: 

Webhook is not sending events to secondary queue configured using the variable `enable_workflow_job_events_queue` probably bcoz of this line https://github.com/philips-labs/terraform-aws-github-runner/commit/f2112ea466af0293f237fd54b38b400c10611b2f#diff-8f22d062f172dea236ef4dde7fae8af38e352b7147ac36f9c5e4af3959e7e8dfR13 in the version 5.4.2

**Comment by npalm** [comment]
Fixed in release https://github.com/philips-labs/terraform-aws-github-runner/releases/tag/v5.6.1
