### ISSUE TITLE
v5.6.3 didn't get uploaded to TF registry

### ISSUE THREAD

**Issue by imphil** [philips-labs/terraform-aws-github-runner#3729]
https://registry.terraform.io/modules/philips-labs/github-runner/aws/latest has only 5.6.2, and "terraform init" complains: 
| There is no available version of module
│ "registry.terraform.io/philips-labs/github-runner/aws" (aws_gh_runner_linux.tf:33) which
│ matches the given version constraint. The newest available version is 5.6.2.

**Comment by npalm** [comment]
Looks like a bug in the HashiCorp registry. The release process does not trigger the registry. It is the registry that monitors the repository. Just re-synced the module (manual). Should work now.

![Uploading image.png…]()
