### ISSUE TITLE
Slack links broken in README

### ISSUE THREAD

**Issue by cap10morgan** [philips-labs/terraform-aws-github-runner#373]
Looks like there was an app deployed to allow joining the Slack, but it appears to be down. There is a broken image in the README and clicking on it leads to a Now error page.

**Comment by npalm** [comment]
Seems broken on all our repos for some time, thanks for reporting

**Comment by mcaulifn** [comment]
@npalm is this being addressed? I'm interested in joining.

**Comment by npalm** [comment]
We haven't found a good alternative yet

**Comment by npalm** [comment]
Fixed
