### ISSUE TITLE
Scale up handler sees 0 queued workflow runs

### ISSUE THREAD

**Issue by cap10morgan** [philips-labs/terraform-aws-github-runner#374]
I have installed everything and it seems to work (to a point) when I trigger a GitHub action w/ `runs-on: self-hosted`. But then when the scale up handler runs, it says there are 0 queued workflow runs (i.e. this code: https://github.com/philips-labs/terraform-aws-github-runner/blob/452f2e6cd6c03c3ddfac8fdfa5b6f0ca32820661/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts#L66). Any idea what could be going on there?

Might this be a first run issue? There are no offline runners configured b/c I haven't run any before. So the GitHub action fails pretty quickly because it can't find a runner.

**Comment by lrytz** [comment]
You need to manually add a runner, as if you were adding your own machine as a runner. Follow through the process until running the `config.sh` script, but then don't continue. This will keep the runner registered as offline, which prevents builds from failing immediately. https://github.com/philips-labs/terraform-aws-github-runner#usages

**Comment by cap10morgan** [comment]
Ah, thanks. I somehow missed that part of the docs.
