### ISSUE TITLE
Multi-Runner Input Names are Different than Normal Runner Inputs 

### ISSUE THREAD

**Issue by srilman** [philips-labs/terraform-aws-github-runner#3740]
When I migrated a setup using the normal runner module to the multi-runner module, I had some trouble getting it working because some of the input names differ. It would be helpful is we rename the multi-runner inputs so they are consistent. Here are some examples:

- `enable_fifo_build_queue` to `fifo`
- `enable_runner_on_demand_failover_for_errors` to `enable_on_demand_failover_for_errors`

There may be more, but I didn't check yet. Happy to open a PR to rename these, but want to make sure there isn't a reason why they're supposed to be different.

**Comment by rvodden** [comment]
Not stale. I'm happy to submit a PR

**Comment by rvodden** [comment]
This hasn't been abandoned. I'm waiting for PlCI to be approved on the above PR
