### ISSUE TITLE
Gracefully terminate old runners when AMI changes

### ISSUE THREAD

**Issue by mrmeyers99** [philips-labs/terraform-aws-github-runner#3746]
We recently rolled out a new AMI for our runners which had a fix for an issue we were facing.  After running `terraform apply` with the new configurations, I had to manually terminate runners with the old AMI, some of them were still there after a couple days.  It would be great if the the old runners were gracefully terminated when the AMI switches so that the pool of runners automatically fills up with the new AMI.

**Comment by npalm** [comment]
Thx for sharing the feedback. We run in ephemeral mode, which ensures instances are only used onces. And new instances are started with the new AMI. In case you run non ephemeral the scale-down should stop old instances, however this only work once they are idle at the moment the lambda is checking. 

Please feel free to suggest improvements.
