### ISSUE TITLE
Lambda ami housekeeper and the ssm parameter store

### ISSUE THREAD

**Issue by Lraharison** [philips-labs/terraform-aws-github-runner#3752]
The Lambda Ami housekeeper is currently encountering an issue where it ignores Parameter Store entries that do not contain "ami-id" in the AMI name. Consequently, it continues to delete the AMI referenced in the Parameter Store, even if it exceeds the ami_house_keeper_minimum_days_old threshold.

 This is particularly evident in the code at line 194 [link to the code: [https://github.com/philips-labs/terraform-aws-github-runner/blob/main/lambdas/functions/ami-housekeeper/src/ami.ts#L194]].

**Comment by Lraharison** [comment]
Okay, when the value of the ssm_parameterNames parameter in the terraform ami-housekeeper module does not contain ami-id, the lambda ami housekeeper simply ignores it, so if the ami is older than the minimumDaysOld, it will be deleted. I hope I was clearer.

I'm not sure if the lambda code takes into account the value of this parameter or if it will just filter the SSM parameters containing ami-id in the name.

**Comment by npalm** [comment]
Thx for the feedback, In case you have some time feel free to suggest a change in a PR.
