### ISSUE TITLE
When to increase size of the pool

### ISSUE THREAD

**Issue by juldou** [philips-labs/terraform-aws-github-runner#3779]
Hi, have any of you found some way how to know when to increase size of the pool? (e.g. from metric, logs, etc...). The motivation is that the users don't wait too long for runners, but also taking the cost into the account.

I haven't found anything that would do it using CW metrics.

**Comment by npalm** [comment]
Currently the module has no support to adjust the pool. I think job start time should be the most logical one to adjust the pool. We start our runners based on AMI which typicall starts runners within in a minute.

**Comment by juldou** [comment]
Exactly, start time can be used to adjust the pool. However, is there any AWS metric related to that?
