### ISSUE TITLE
Question: For different AWS profiles and vpc's do I need separate Github apps?

### ISSUE THREAD

**Issue by videate-josh** [philips-labs/terraform-aws-github-runner#3788]
We are running jobs against different environments (eks clusters) that are associated with different aws profiles (dev, stage, prod).  I know the AMI's we build with packer are shareable across profiles but if we have a runner that needs to run in the same VPC as the cluster what is the recommended way to do this?

- I know the Github app has a webhook associated with it, but I'm assuming that an app would need to be created for each environment and then the assets could be created in different terraform workspaces and each webhook would need to be unique based on the enviornment.  
- Then in my github actions would I just reference `runs-on: <runner_name>-ubuntu-stage`

Just looking for guidance on using these runners across different profiles / vpc spaces.

**Comment by jkruse14** [comment]
I'll want confirmation on this - but no, I don't think so. The GitHub app provides a token for the runner to register itself with GitHub and run operations based on GitHub's platform, not against AWS services. So, as long as the GH App has permissions to the repo and Org, you should only need a single App.

**Comment by videate-josh** [comment]
I was able to handle it all with just one so that is confirmed, thank you @jkruse14

**Comment by jkruse14** [comment]
@videate-josh - are you able to close this issue since you created it?

**Comment by videate-josh** [comment]
Closing, thanks for the help
