### ISSUE TITLE
Error: ssmHousekeeper handler not found

### ISSUE THREAD

**Issue by jkruse14** [philips-labs/terraform-aws-github-runner#3801]
On version 5.8.0 I am seeing this error ssm-housekeeper lambda:

```
2024-03-06T03:17:16.873Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.HandlerNotFound",
    "errorMessage": "index.ssmHousekeeper is undefined or not exported",
    "stack": [
        "Runtime.HandlerNotFound: index.ssmHousekeeper is undefined or not exported",
        "    at Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1122:15)",
        "    at start (file:///var/runtime/index.mjs:1282:23)",
        "    at file:///var/runtime/index.mjs:1288:1"
    ]
}

**Comment by npalm** [comment]
Just doubled checked our deployment (5.8.0). But I see now issues with the ssm housekeeper.

**Comment by npalm** [comment]
We have checked the lambda in our own deployment (version 5.8.0). THe ssm housekeeper is enabled by default. We don't see errors. Please can you double check you have the correct version of the module as well the correct version of the lambda zips.
