### ISSUE TITLE
Scale down lambda terminates active runners

### ISSUE THREAD

**Issue by MounikaBattu17** [philips-labs/terraform-aws-github-runner#3802]
I'm using v5.6.3 released version, I have set up my repo with GitHub app and configured all settings for windows pre-built AMI. I have no issues in that. I'm not using ephemeral runners rather opting to use runners which can pick up next in-line jobs after the previous job completion.
I specified `  runner_boot_time_in_minutes = 30` in my `main.tf` configuration.
The problem I'm facing is after this 30 minutes, scale down lambda is terminating the runner even though the runner is still executing the jobs. As far as my knowledge, scale down lambda terminates runner only if they are idle. So, the behavior in my case is odd.
Also, I don't see any of my runners getting de-registered from GitHub repo. They stay offline forever after runner termination from GitHub.

Please provide me some clarification on why this behavior?
Also, please suggest whether using ephemeral runners will be helpful or not?

Edit: A some context on why the runners are terminated even if they are active, 
1) In cloud watch log groups, I can see instance is mentioned as "orphaned". 
2) I'm not sure why it is marking instance as orphaned even though the runner is literally executing the GitHub jobs. 

Update:
I found the root cause of this behavior. I'm using 2 runners per instance, so to differentiate both runners I have suffixed them with `InstanceId-RunnerNumber`. This make the check [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/main/lambdas/functions/control-plane/src/scale-runners/scale-down.ts#L162) fail. Thus, the instance is terminated as orphaned after boot timeout. I have updated the runner names accordingly fixing this issue.

Please share any thoughts and feel free to close the issue.

**Comment by npalm** [comment]
The module is designed for a single runner per ec2. Cases like running multipe agents on a single node are not taken into account. We even advocate to run in ephemeral mode to ensure jobs are 100% isolated. But depending on the scale you host the module different choices may apply.

Scale down is indeed designed to terminated runners marked as orphan. Or idle onces. This is mostly relevant running in non ephemeral deployments.

Feel free to improve docs, or write a short guide how to run multiple agents.

**Comment by quantizor** [comment]
@npalm how do we allow for graceful shutdown of "orphaned" runners? I have a situation where I think a new version of a runner AMI was deployed, which made a runner that was currently executing a job effectively "orphaned" and then killed the runner without letting it finish what it was doing.
