### ISSUE TITLE
Permission Issue When Running multi-runner solution: Access denied for ssm:GetParameter action

### ISSUE THREAD

**Issue by aniespica** [philips-labs/terraform-aws-github-runner#3805]
**Description:**
I deployed the example for running [multiple runners](https://github.com/philips-labs/terraform-aws-github-runner/tree/main/examples/multi-runner) on my AWS instance using the solution provided it. However, when attempting to execute an action on GitHub with exact matching labels, I encountered the following error:

```
AccessDeniedException: User: arn:aws:sts::XXXXXXXXX:assumed-role/multi-runner-action-webhook-lambda-role/multi-runner-webhook is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:eu-west-1:XXXXXXX:parameter/github-runner/runner-matcher-config because no identity-based policy allows the ssm:GetParameter action
```

**Problem:**
The `multi-runner-action-webhook-lambda-role` lambda function lacks the necessary permissions to access the `github-runner/runner-matcher-config` parameter in the AWS Systems Manager (SSM) service. The `ssm:GetParameter` action is required for the function to retrieve this parameter, but the current policy associated with the function seems to be restricted to a different parameter.

**Actions Taken:**
I investigated the policy associated with the `multi-runner-action-webhook-lambda-role` function and found the following:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "ssm:GetParameter"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:ssm:eu-west-1:XXXXXXX:parameter/github-action-runners/multi-runner/app/github_app_webhook_secret"
            ]
        }
    ]
}
```

I added the necessary policy for the ARN that was throwing the initial error. However, upon doing so, I encountered a new error:

```
ParameterNotFound: UnknownError
```

It appears that despite adding the policy for the problematic ARN, a new error related to parameter not found is being raised.

I use the version [5.8.0](https://github.com/philips-labs/terraform-aws-github-runner/releases/tag/v5.8.0) for the lambdas functions.

**Comment by npalm** [comment]
Release 5.8.0 contains a large change in the webhook. Configuration is mostly moved to SSM. But in our test environments this all works fine. Please can you double check your terraform on version 5.8.0 applied and Lambda sources are up-to-date. For validation of the module we use the default and multi-runner example. Both working fine.

**Comment by GuptaNavdeep1983** [comment]
<img width="952" alt="image" src="https://github.com/philips-labs/terraform-aws-github-runner/assets/10557183/b3f07c13-3ca1-4cdf-942f-38fa9e49bf17">

this is the code used to assign policy to webhook which is in modules/webhook/webhook.tf!
