### ISSUE TITLE
Add the ability to use custom labels only

### ISSUE THREAD

**Issue by azagarelz** [philips-labs/terraform-aws-github-runner#3822]
**Overview**
Currently, when configuring GitHub runners using this module, default labels such as "self-hosted," "os," and "architecture" are automatically appended.
https://github.com/philips-labs/terraform-aws-github-runner/blob/b2dc794f08c932470dae846dad0e0a5f33a68cc4/modules/multi-runner/runners.tf#L48
While generally beneficial, there are scenarios where these labels are inappropriate.

**Use Case**
We want a runner group where all the registered runners should have custom labels only.
People using workflows with `runs-on` on common labels should never use the runners in the above group unless it is explicitly requested or custom labels are used.

**Suggest a Fix**
Add the ability to skip the concat of self-hosted, os, and architecture labels using a var.

**Comment by mikmorley** [comment]
It looks like https://github.com/philips-labs/terraform-aws-github-runner/pull/3491 attempts to resolve this issue, however the PR has gone stale. Hopefully we can get an update on this soon. 🙏,
