### ISSUE TITLE
logging examples contains service undefined

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#3886]
## Problem

Logs of examples contains.

```
"service":"service_undefined",
```

## Fix

Ensure POWERTOOLS_SERVICE is by default corretly set.

**Comment by winwinashwin** [comment]
Seems like a typo? 
https://github.com/philips-labs/terraform-aws-github-runner/blob/2eaaab3348d07e9968d8dd100a2c526e19064e2a/modules/runners/scale-up.tf#L44
