### ISSUE TITLE
SQS_WORKFLOW_JOB_QUEUE env variable not set for webhook Lambda

### ISSUE THREAD

**Issue by jo-koe** [philips-labs/terraform-aws-github-runner#3898]
Hi,
we've just deployed the [ubuntu](https://github.com/philips-labs/terraform-aws-github-runner/tree/main/examples/ubuntu) example and the `SQS_WORKFLOW_JOB_QUEUE` environment variable is empty for the webhook lambda which leads to the issue that the function can't add new messages to the queue.

After setting the env variable manually via the AWS Console to the queue URL it works just fine.

Thanks,
Jonas

**Comment by jo-koe** [comment]
We've just found out that setting variable `enable_workflow_job_events_queue=true` solves the problem.

**Comment by supriyaaaic** [comment]
@jo-koe can you please guide me which version have you used? I am trying to use [v5.10.0](https://github.com/philips-labs/terraform-aws-github-runner/releases/tag/v5.10.0)

**Comment by jo-koe** [comment]
@supriyaaaic we have used `v5.10.4`

**Comment by supriyaaaic** [comment]
thanks @jo-koe 👍

**Comment by stuartp44** [comment]
I am closing this issue as it seems like you have solved your issue.
