### ISSUE TITLE
ebs_optimized variable is not propagated to submodules

### ISSUE THREAD

**Issue by AlexShemeshWix** [philips-labs/terraform-aws-github-runner#3902]
Runners have configuration property [ebs_optimized](https://github.com/philips-labs/terraform-aws-github-runner/blob/fd7681cfe68da3eab094f73310d32a117f3b1063/modules/runners/variables.tf#L65) variable. 
This variable cannot be set from main module. 
Ive opened [PR 3901](https://github.com/philips-labs/terraform-aws-github-runner/pull/3901) to resolve this situation.
Please approve and merge it.

**Comment by stuartp44** [comment]
It seems that you PR is now merged, so I will close this ticket
