### ISSUE TITLE
Github Enterprise configuration

### ISSUE THREAD

**Issue by ayakout-magna** [philips-labs/terraform-aws-github-runner#4050]
I'm trying to use the Terraform AWS GitHub Runner module to set up ECS runners for my GitHub Enterprise installation in AWS. I've just started looking into it but couldn't find where to set the value for the GitHub domain. Can someone guide me on how to configure the module to work with my GitHub Enterprise setup?

**Comment by stuartp44** [comment]
There is a var that is available that is ghes_url https://github.com/philips-labs/terraform-aws-github-runner/blob/6d0fa399e6285a3c900e45b19360cde6dc3c49b1/main.tf#L280 which can be used to set the enterprise URL. We as Philips have not tested this as we do not operate a Github Enterprise system but its used by a few community members here. Suggestion is you can ask in the Slack channel for more information and support regarding this topic.
