### ISSUE TITLE
Support Time Zone for Runner Pool

### ISSUE THREAD

**Issue by janslow** [philips-labs/terraform-aws-github-runner#4056]
Hey, thanks for the work you've done on this project (and for open sourcing it)!

Would you consider adding support for providing the Time Zone as part of the `pool_config` variable?

For context, we want to keep a pool of runners ready during office hours, but we'd currently need to convert the `pool_config[*].schedule_expression` to UTC and update that whenever the clocks change (e.g., I'm in the UK, where the start/end of "British Summer Time" changes every year).

## Workaround

Unfortunately, AWS EventBridge Rules (currently used to trigger the pool function) don't support time zones, but [AWS EventBridge Scheduler does](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/scheduler_schedule). This feature is [a drop-in replacement](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-scheduler/) for EventBridge Rules (including the cron expression) and [the same price](https://aws.amazon.com/eventbridge/pricing/).

My current workaround is to define the `aws_scheduler_schedule` resources outside the GitHub runners module and trigger the pool Lambda, but that has a couple of issues:
* It relies on implementation details of your module, so may break in the future (specifically, the payload to pass to the pool function)
* At least one `pool_config` expression is required, otherwise the pool resources aren't created

## Proposal

1. Add an optional `time_zone` property to the `pool_config` variable
2. Replace the use of `aws_cloudwatch_event_rule` in the `pool` module with `aws_scheduler_schedule` (and a single `aws_scheduler_schedule_group` and `aws_iam_role`), setting `schedule_expression_timezone` if necessary.

Alternatively, dynamically switch between `aws_cloudwatch_event_rule` and `aws_scheduler_schedule`, depending on whether the `time_zone` is set. This would increase the complexity of the module, but would avoid making any changes to existing users.

If you'd consider accepting one of these as a PR, I can look at implementing one of them.

**Comment by stuartp44** [comment]
For us within Philips, this is not much of issue. I can see where the suggestion will help reduce arbitrary code to workaround this issue. Any contributions are more than welcome!
