### ISSUE TITLE
job_retry.enabled=true fails to find manually downloaded runners.zip

### ISSUE THREAD

**Issue by imphil** [philips-labs/terraform-aws-github-runner#4078]
I manually download and specify the lambda zip files in my main module:

```tf
  webhook_lambda_zip                = "./webhook.zip"
  runner_binaries_syncer_lambda_zip = "./runner-binaries-syncer.zip"
  runners_lambda_zip                = "./runners.zip"
```

This has worked fine for a long time now.

When enabling the new job retry feature in v5.15.1 with
```tf
  job_retry = {
    enable           = true
  }
```

I get the following error when running `tofu apply`:
```
╷
│ Error: Error in function call
│ 
│   on .terraform/modules/gh-runner-linux/modules/lambda/main.tf line 24, in resource "aws_lambda_function" "main":
│   24:   source_code_hash  = var.lambda.s3_bucket == null ? filebase64sha256(var.lambda.zip) : null
│     ├────────────────
│     │ while calling filebase64sha256(path)
│     │ var.lambda.zip is ".terraform/modules/gh-runner-linux/modules/runners/job-retry/../../../lambdas/functions/control-plane/runners.zip"
│ 
│ Call to function "filebase64sha256" failed: open .terraform/modules/gh-runner-linux/lambdas/functions/control-plane/runners.zip: no such file or directory.
╵
```

It looks like the `runners_lambda_zip` path is not passed on to the new module.

I tried to sort out a fix, but I'm slightly confused as to how things are supposed to be. It looks like there's a bit of inconsistency introduced with `zip` vs `lambda_zip` and the variable names are around it, starting with the termination watcher, and now (it seems) copied over to the job retry functionality. 

@npalm, you probably know best how things are supposed to be? If not, let me know and I'll try to come up with something.

PS: Thanks a lot for introducing the job retry feature, I cannot wait to try it out. We repeatedly had jobs not starting, it's the only thing that didn't work for us with this fantastic module.

**Comment by npalm** [comment]
Guess similar to this problem: https://github.com/philips-labs/terraform-aws-github-runner/pull/4074

Would you have time to raise a PR. Could speed up a fix.

**Comment by imphil** [comment]
Thanks for having a look and even doing the PR and a release! I'm now running with the latest version and job retry enabled, let's see how far we get with that.
