### ISSUE TITLE
Output for syncer binary location is incorrect

### ISSUE THREAD

**Issue by driskell** [philips-labs/terraform-aws-github-runner#4137]
https://github.com/philips-labs/terraform-aws-github-runner/blob/v5.10.4/outputs.tf#L28

It appears to have a variable that doesn't exist but it is also a literal not a variable. I think it is meaning:

```
location         = "s3://${module.runner_binaries[0].bucket.id}/${module.runner_binaries[0].runner_distribution_object_key}"
```

**Comment by npalm** [comment]
Would you have time to make a fix?
