### ISSUE TITLE
Multi-region deployments not successful due to global IAM role names

### ISSUE THREAD

**Issue by evanstachowiak** [philips-labs/terraform-aws-github-runner#4206]
Hi,

I would like to deploy this module into multiple regions within the same account, however, the IAM roles are not configurable and are not unique across module instantiations. IAM role names are create within a global namespace, so this causes errors in the deployment.

Is there any way to support configurable names for the IAM roles? Or at least support adding the region into the naming?

Thanks for this module, otherwise it is working wonderfully!

**Comment by npalm** [comment]
We have multiple deployments in a single account, you can set the `prefix` variable to different values. This will be used as part of the role name (and almost any resource) to make name unique.

**Comment by evanstachowiak** [comment]
Oh, that's perfect, sorry I didn't see that. Thank you!
