### ISSUE TITLE
Unsupported event type: installation

### ISSUE THREAD

**Issue by igor-dmitriev** [philips-labs/terraform-aws-github-runner#4219]
**version**: 5.18.0

I just followed the instructions https://philips-labs.github.io/terraform-aws-github-runner/getting-started/#install-github-app
and ran into an issue: "Unsupported event type: installation"

<img width="858" alt="Screenshot 2024-10-29 at 20 13 07" src="https://github.com/user-attachments/assets/cf45255c-d5cd-4204-a984-303fec8db2dc">

<img width="1390" alt="Screenshot 2024-10-29 at 20 14 07" src="https://github.com/user-attachments/assets/3a9e14c1-a3e2-4945-a542-d319d1133a4c">

**Comment by npalm** [comment]
Thanks for reporting, this should not keep the module from working. But ineed the module is not processing the installation event (test) event sent by GitHub. Are the workflow_job events accepted? Or is the GitHub not working because of this error?

**Comment by npalm** [comment]
I tried quickly to reproduce the problem

1. Created a fresh app
2. Configure the webhook to a runner deployment (default example, no eventbridge, default config)
3. All events are accepted
4. Trigger a job, event accepted as well.

See here the log
<img width="824" alt="image" src="https://github.com/user-attachments/assets/8f2dcc5a-1e77-4e78-b209-6d5b22121b7d">

**Comment by igor-dmitriev** [comment]
I recreated everything from scratched, it works fine
