### ISSUE TITLE
[EventBridge] Dispatcher only needs workflow_job events with status queued.

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#4223]
Currently all workflow_jobs are sent to the dispatcher, only the workflow jobs with status queued are required.

https://github.com/philips-labs/terraform-aws-github-runner/blob/0c525809577fade304f5358a094663bdef9e3b7e/modules/webhook/eventbridge/dispatcher.tf#L1-L16

**Comment by winwinashwin** [comment]
Fixed by https://github.com/philips-labs/terraform-aws-github-runner/commit/a0a8322b539edab279a8570507f6f83ec11a290a
Can be closed?
