### ISSUE TITLE
Question: What happens if a spot instance is terminated by AWS?

### ISSUE THREAD

**Issue by leoblanc** [philips-labs/terraform-aws-github-runner#44]
Hi, first of all, congratulations for this great project.

We have deployed github-runner successfully and it's running very well so far.

One question please. As you know, [spot instances can be terminated by AWS](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-interruptions.html). If a GitHub Runner EC2 instance is suddenly stopped by AWS (I mean, in the middle of a pipeline), what happens to the GitHub pipeline? It fails? Is there any retry/re-schedule mechanism to re-execute the build?

Thank you very much in advance.

**Comment by npalm** [comment]
We have not implement anything to handle suddenly terminated spot instances. What will happen. Yes if you running a job, the job will be killed. No retry and I expect you end up with an orphan registred runner in GitHub.  We running already for years CI jobs on spot instances and so far we have ony a few issues. So never took the effort to make it all more resilient. 

Maybe a first step is start measuring instances that got terminated via for example cloud watch.

**Comment by leoblanc** [comment]
Glad to know that in the reality this situation doesn't occur frequently. I didn't face this situation so far. I guess that Phillips has a very big and active team of developers and devops engineers, so if it works for you it should work for us too. Thanks for your info.
