### ISSUE TITLE
Add instuction to contributers for pre-commit

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#46]
Seems no instructions / directions are documented for pre commit hooks.

**Comment by axel3rd** [comment]
The [Submitting a Merge Request](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/CONTRIBUTING.md#submitting-a-merge-request) section is clear (Installing `terraform-docs` & `tflint` is quite easy).

The `pre-commit run --all-files` is simple to use to check manually before or after some bug/feature fix.

Perhaps one attention about `Terraform docs` phase, it changes Markdown content adding many links like (Sample from `git diff`):

```sh
 ## Modules

 | Name | Source | Version |
 |------|--------|---------|
-| runner_binaries | ./modules/runner-binaries-syncer |  |
-| runners | ./modules/runners |  |
-| ssm | ./modules/ssm |  |
-| webhook | ./modules/webhook |  |
+| <a name="module_runner_binaries"></a> [runner\_binaries](#module\_runner\_binaries) | ./modules/runner-binaries-syncer | n/a |
+| <a name="module_runners"></a> [runners](#module\_runners) | ./modules/runners | n/a |
+| <a name="module_ssm"></a> [ssm](#module\_ssm) | ./modules/ssm | n/a |
+| <a name="module_webhook"></a> [webhook](#module\_webhook) | ./modules/webhook | n/a |
```

I don't know if it is really wanted, perhaps depends of `terraform-docs` version (`v0.15.0` is used).

**Comment by npalm** [comment]
Instructions are available
