### ISSUE TITLE
New VPC (and other network resources) created even though existing VPC is defined

### ISSUE THREAD

**Issue by nafpliot** [philips-labs/terraform-aws-github-runner#477]
I see that a new VPC is created even though I defined the vars `vpc_id` and `subnet_ids` with existing resources. I thought that since the setup is using existing resources of my environment there shouldn't be any new VPC / Subnet creation.

It seems also that apart from the VPC / Subnet creation, a Nat Gateway is created too. I assume this is for the runners to have access to GitHub from the private subnet, but since we defined our own subnet and we already take care of the gateway, it should not be created either.

Is there something I missed during the configuration that causes these resources to be created or is this "normal"?

Thank you for the great work you do with this module!

**Comment by npalm** [comment]
The module is not creating a VPC, subnets, or gateways. A full list of all (potential) resources you can quickly inspect here: https://registry.terraform.io/modules/philips-labs/github-runner/aws/latest?tab=resources. But of course the module (runners) requires subnets to run. Therefore the examples are creating a VPC. see https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/examples/default/vpc.tf 

So are you using an example provided? In that case a network is created for you with public subnets, private subnets and a nat gateway and internet gateway.

**Comment by nafpliot** [comment]
Hey @npalm , you are right! I started playing around with the default example and I totally missed the `vpc.tf`. Sorry about that.
