### ISSUE TITLE
Runners in different environments / VPCs

### ISSUE THREAD

**Issue by nafpliot** [philips-labs/terraform-aws-github-runner#495]
A feature request: The possibility to have the runners scale-up / down in different VPCs. This is useful when there are workflows that need to be ran in different environments (dev, prod) that belong to different VPCs.

With the current setup I don't know if there is any easy way for doing this.

**Comment by MoJo2600** [comment]
Yes, I think I'm running into this issue as well. We are using dedicated accounts for prod/qa/dev. Not sure how to use this solution in such a setup.

**Comment by ScottGuymer** [comment]
I think this probably plays into the suggestion to enable different vm configs to be spun up based on the labels passed into the webook.


https://github.com/philips-labs/terraform-aws-github-runner/discussions/1428

**Comment by MoJo2600** [comment]
Yes, @ScottGuymer I think so. Was reading #1428 a minute ago.

**Comment by ScottGuymer** [comment]
This is something on the roadmap and will be implemented sometime soon as it is also something we would like internally at Philips.

Will close this in favour of the discussion.
