### ISSUE TITLE
Idle runners on a smaller instances

### ISSUE THREAD

**Issue by Kostiantyn-Vorobiov** [philips-labs/terraform-aws-github-runner#508]
A feature request: The possibility to specify the different instance type for idle runners. 

In some pipelines, the first job is orchestrating the creation of others and don't require too much computing power. It would be nice to have this possibility to manage such instances separately.

**Comment by ScottGuymer** [comment]
Are you only using this module against a single repository?

I'm not sure this makes any sense for an org deployment as you would have no control over who kicks off what job and when.
