### ISSUE TITLE
Rename runners_maxiumum_count input (typo)

### ISSUE THREAD

**Issue by leoblanc** [philips-labs/terraform-aws-github-runner#51]
Hello, thanks for your great work here.

Can we rename the `runners_maxiumum_count` variable name please?

The word `maxiumum` has a typo. Correct name is `maximum`

Thanks!

**Comment by npalm** [comment]
Yes feel free to propose a PR

**Comment by leoblanc** [comment]
Thanks! I'll send a PR this week.

**Comment by leoblanc** [comment]
I have created this PR: https://github.com/philips-labs/terraform-aws-github-runner/pull/75
