### ISSUE TITLE
EC2 instance type

### ISSUE THREAD

**Issue by sorinsugar** [philips-labs/terraform-aws-github-runner#52]
How can you pass the instance type you want to build. I saw that the default instance is m5.large, but there is no explanation on how we can change that.

**Comment by npalm** [comment]
Only one instance type per deployment orchestrator can be set. You simple set the instance type with the terraform variable `instance_type`. The type is managed via an AWS launch configuration.

**Comment by sorinsugar** [comment]
Hi, thanks for the reply. This variable should be add in the main tf file like so? Because it was not declared in variables and terraform complains.
`module "github-runner" {
  source  = "philips-labs/github-runner/aws"
  version = "0.2.0"

  instance_type = "t3.xlarge"
}`

**Comment by npalm** [comment]
Good catch! Would you like to make a small PR?

**Comment by sorinsugar** [comment]
Yes, I'll do one and send it to you.

**Comment by sorinsugar** [comment]
Just looked at the code, and it seems that you already have the `instance_type` in variables (master and develop branches), but not on release 0.2.0.

**Comment by npalm** [comment]
oops, I will create a release asap, was also upgrading several libs., So, let's close this issue

**Comment by sorinsugar** [comment]
Perfect, I'll close it :)
