### ISSUE TITLE
Exhausted API limits for installation

### ISSUE THREAD

**Issue by mkryva** [philips-labs/terraform-aws-github-runner#607]
Hi. I've found error according to current flow of installation self hosted runners using your solution.
Today, I receive error from Github: API rate limit exceeded for installation ID ***.

Is it possible to fix it ? Is it possible to install this solutions using personal token?

**Comment by npalm** [comment]
Do you have an idea how many evens you got from the app to the webhook to the sqs queue? The rate limit on the app should be much higher then on your PAT token.

**Comment by mkryva** [comment]
Sure and can You explain how to setup your solution via PAT and without app createation/installation ?
