### ISSUE TITLE
Configurable queue delay

### ISSUE THREAD

**Issue by eestolano** [philips-labs/terraform-aws-github-runner#649]
Feature request: can you please make the SQS queue delay configurable? It's currently hardwired to 30 seconds in the module.

(The README currently says it's configurable, even though it isn't:

> Messages on this queue will be delayed for a configurable amount of seconds (default 30 seconds) to give the available runners time to pick up this build.

)

**Comment by npalm** [comment]
Good catch, feel free to create a PR

https://github.com/philips-labs/terraform-aws-github-runner/blob/acbfab38c7dbef4f35263be5f0d2b4d6b094bf01/main.tf#L20
