### ISSUE TITLE
Got any "Good First Issues"? :)

### ISSUE THREAD

**Issue by boldandbusted** [philips-labs/terraform-aws-github-runner#650]
Howdy. I'm likely going to make use of this project for a variety of clients. I'd like to contribute back, even for some things that aren't directly related to the project. Would you-all mind creating "Good First Issues" tag and creating issues good for those of us eager to contribute, but need onboarding guidance (maybe code janitor?) tasks? Cheers! Thanks for F/OSSing this code!

**Comment by michaelstepner** [comment]
I defer to @npalm since I am just a user, but the bug report I just filed in #653 is quite simple, so the fix might be simple and constitute a good first issue 🙂

**Comment by npalm** [comment]
I have added some labels. And will create some more issues later this week of small enhancements
