### ISSUE TITLE
Support disable spot instances.

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#655]
The runner module hardcoded the usages of spot usags by setting market option to spot see:

https://github.com/philips-labs/terraform-aws-github-runner/blob/b4838d789fcaa3a8fca9b6bf112002161a329e6f/modules/runners/variables.tf#L54. 

Would be better to make it configurable with default spot to support also on demand instances.

See also https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_InstanceMarketOptionsRequest.html

**Comment by dimisjim** [comment]
@npalm Implemented here: https://github.com/philips-labs/terraform-aws-github-runner/pull/657

**Comment by michaelstepner** [comment]
@npalm @dimisjim Thanks for implementing this feature! It will be super useful in my work, and I'm grateful you're providing this public good.

**Comment by michaelstepner** [comment]
Can be closed now that #657 is merged, I think. I just deployed that patch to my production server! \(^-^)/ Thanks again.

**Comment by npalm** [comment]
Spot can be disabled by setting variable `market_options`
