### ISSUE TITLE
README: The docs mention endpoint URI and secret to use in the GitHub App - but which Outputs are those?

### ISSUE THREAD

**Issue by boldandbusted** [philips-labs/terraform-aws-github-runner#726]
Howdy. The docs say:

"The terraform output displays the API gateway url (endpoint) and secret, which you need in the next step."

Can the documentation be more explicit about which Terraform output is the "secret"? There is a lot of text dumped as a result of 'terraform output', so unspecific references can be confusing, at least to my brain. :) Thanks!

**Comment by kuvaldini** [comment]
Please refer to #827 - it should help
