### ISSUE TITLE
Quesiton: Runner based on label

### ISSUE THREAD

**Issue by callum-tait-pbx** [philips-labs/terraform-aws-github-runner#73]
Hello Again!

I've got a question, how do you support spinning up different images depending on the label? My dream solution is runners are span up as required with them avaliable at the organisation level. The runner that is span up is based on the label provided, so if it's a node-12 label for instance then a node 12 instance is span up based on a node 12 launch template. How does the setup support multiple labels?

Cheers

**Comment by npalm** [comment]
@callum-tait-pbx We spin up instances based on events we get from GitHub. In other words spinning up instances is 1 to 1 connected to the connected GitHub app. The event sent by github does not contain info about the label. The only label support there is, is having multiple deployments with multiple apps, and a hard connection from repo to runner (label). Any suggestion to make it more flexible is welcome!

**Comment by lrytz** [comment]
This would also allow testing on multiple OSs (https://github.com/philips-labs/terraform-aws-github-runner/issues/347). But as you say, the GitHub API for workflows / jobs doesn't seem to expose any information about the `runs-on` labels of the job.
 - https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#workflow-runs
 - https://docs.github.com/en/free-pro-team@latest/rest/reference/actions#workflow-jobs

Might be worth reaching out to GitHub support, @npalm what do you think?

**Comment by sjagoe** [comment]
I've just noticed that `labels` are now in the workflow-jobs payload!

https://docs.github.com/en/rest/reference/actions#workflow-jobs

**Comment by npalm** [comment]
We support the workflowjob event, and have a filter for checking on labels build in. Which can be enabled or disabled. We do not support the option to spin up different instances based on label. 

For creating instances we use the launch template, to give an option for fallback in case of a spot instance is not available you can specify multiple instances types. Which leads to multiple launch instances. It seems that the way we use the launch template can be done in a better way, as suggested in #1400 . Solving this issue will remove the compleity of the launch templates we have today. And once solved supporting multiple runners tags in combination with ephemeral runners #1374  should be an option

**Comment by ScottGuymer** [comment]
This is something that is on the roadmap and discussed further here https://github.com/philips-labs/terraform-aws-github-runner/discussions/1428

Closing this in favour of the discussion
