### ISSUE TITLE
Docs: lambda_security_group_ids incorrect description

### ISSUE THREAD

**Issue by boldandbusted** [philips-labs/terraform-aws-github-runner#738]
Howdy. Currently, the README.md has this definition for `lambda_security_group_uds`:

lambda_security_group_ids | List of subnets in which the action runners will be launched, the subnets needs to be subnets in the vpc_id.
-- | --

I think there may have been a copypasta accident with the next variable description. :) Thanks!

**Comment by npalm** [comment]
Good catch

**Comment by boldandbusted** [comment]
While this could be easily changed, I don't know what text was intended to be there in the first place. :)
