### ISSUE TITLE
Ubuntu example should use /var/log/syslog instead of /var/log/messages

### ISSUE THREAD

**Issue by Procrat** [philips-labs/terraform-aws-github-runner#783]
Hi all! Thank you for the hard work on this wonderful module!

I just noticed a minor logging issue in the [Ubuntu example](https://github.com/philips-labs/terraform-aws-github-runner/tree/e829e0eb5d7a0b863cf0a50f9527859c19c2b83e/examples/ubuntu). [Logs in `/var/log/messages` are being captured and sent to CloudWatch.](https://github.com/philips-labs/terraform-aws-github-runner/blob/e829e0eb5d7a0b863cf0a50f9527859c19c2b83e/examples/ubuntu/main.tf#L56) As far as I can tell, logs are not or no longer written to `/var/log/messages`, but get stored in `/var/log/syslog` instead. It might be worth changing that over.

**Comment by npalm** [comment]
Feel free to raise a PR
