### ISSUE TITLE
Setup Github App: Organization - Administration permission does not seem to be required

### ISSUE THREAD

**Issue by davidshin** [philips-labs/terraform-aws-github-runner#801]
First off, thanks for this amazing terraform module! 

I've experimented and found that when setting up the Github App according to the [readme](https://github.com/philips-labs/terraform-aws-github-runner#setup-github-app-part-1), step 7,  the `Organization - Administration: Read & Write` permission is not required for everything to work properly.  Seems like the `Organization - Self-hosted runners: Read & Write` permission is sufficient.  

Perhaps the readme should be updated to reflect this?  Or maybe I'm missing something?

**Comment by npalm** [comment]
Thanks for reporting. We need to check. But could be that the section was added over the last year by github.

**Comment by kuvaldini** [comment]
Refer to this documentation page https://docs.github.com/en/rest/reference/permissions-required-for-github-apps#permission-on-self-hosted-runners

**Comment by npalm** [comment]
Just verified and admin permissions are not longer required. Checked a org level setup.

**Comment by davidshin** [comment]
Thanks!
