### ISSUE TITLE
[Question] Scale tuning

### ISSUE THREAD

**Issue by PavelSusloparov** [philips-labs/terraform-aws-github-runner#831]
What are the best practices for scale-up/scale-down tuning?

My terraform-aws-github-runner config:
```
module "runners" {
  source = "git::https://github.com/philips-labs/terraform-aws-github-runner.git?ref=v0.13.0"

  aws_region = local.aws_region
  vpc_id     = data.terraform_remote_state.vpc.outputs.vpc_id
  subnet_ids = data.terraform_remote_state.vpc.outputs.private_subnets

  environment = local.environment
  tags = {
    "Project" = "GitHub Actions Self-Hosted Runners"
    Terraform = "True"
  }

  github_app = {
    key_base64     = data.sops_file.this.data["github_app_key_base64"]
    id             = data.sops_file.this.data["github_app_id"]
    client_id      = data.sops_file.this.data["github_app_client_id"]
    client_secret  = data.sops_file.this.data["github_app_client_secret"]
    webhook_secret = random_password.random.result
  }

  instance_type                     = "t3.small"
  webhook_lambda_zip                = "lambdas-download/webhook.zip"
  runner_binaries_syncer_lambda_zip = "lambdas-download/runner-binaries-syncer.zip"
  runners_lambda_zip                = "lambdas-download/runners.zip"
  enable_organization_runners       = true
  runner_extra_labels               = "terraform, autoscale"

  # enable access to the runners via SSM
  enable_ssm_on_runners = true

  manage_kms_key = false
  kms_key_id     = aws_kms_key.github.key_id

  idle_config = [
    {
      cron     = "* * * * * *"
      timeZone = "America/New_York"
      # min number of instances
      idleCount = 3
    }
  ]
  # max number of instances for scalling up
  runners_maximum_count = 63
}
```

I'm running a heavy workload with GitHub Actions matrix functionality. One workflow contains 370 jobs.
There are 3 matrixes described:
* 150 jobs
* 150 jobs
* 70 jobs

I start with 3 running instances and during the workflow run, I monitor scale-up behavior. I observe that the maximum number of EC2 instances created is 37. It seems like I can not reach the full potential of 63 instances, so my matrix workflow runs slow.

What is the combination of configuration tweaks, techniques I can use to reach the runners_maximum_count instances?

**Comment by kuvaldini** [comment]
I also noticed that runners_maximum_count never reached.

**Comment by npalm** [comment]
I guess you reach the maximum spot instances. During creation of the module we have chosen to let the lambda create instances. Side effect is that the creation is not advances, only spot or non spot is supported today. During the creation a process a token is requested to GitHub and shared via SSM. This avoid that we have to share secrets (app token) with the runner instances. Would be much better if we could use the spotfleet in a more advanced way without giving up not sharing the secrets. Any idea is welcome

**Comment by fortum-vaanavil** [comment]
You are currently creating a new registration token for every instance, storing the token in SSM with the instance id as the key and then fetching and deleting the SSM secret in the instance userdata. 

However, there's nothing instance specific in the registration token, which suggests another approach: have another Lambda updating the registration token in SSM (since it's valid for an hour) and then in the userdata you could refer to an SSM secret whose name independent of the instance id. I guess this would allow you to use the spotfleet without sharing the App credentials to the instances.

**Comment by npalm** [comment]
Yes using a lambda crossed my mind already several times. Could als be one that creates adhock a token on request of an ec2 instance. Never tried if I can use a token multiple times.

At the moment we created the runners, org level runners does not exists. We also still like to support the scenario to scale back to zero. Which is in general more relevant for repo level runners. Those are reasons why we not choose the spot fleet at that time. I would be more than happy if we fine a way that we can support scaling better. But I would like to support.

- org / repo level runners
- possibility to scale back to zero (special for repo level runners).

The options I see.
- Every time we scale up / scale down create a spotfleet with size one. And let amazon choose the best fitting instance
- Change the approach and have a scaling group that creates runners, scale up / down based on load. This could support also ephemeral runners. By once the instance is up, let the instance remove itself from the scaling group, and start the runners in a run once mode. A lambda should manage the size of the scaling group based on events from github.
- Looking forward to any other alternative

**Comment by PavelSusloparov** [comment]
Great discussion! Keep it going.

The limit of spot instances in my AWS account is 64. This is the reason I set runners_maximum_count  to 63.

**Comment by npalm** [comment]
We running today over 100+ instances without an issue

**Comment by PavelSusloparov** [comment]
We run 300 instances without any problems too. 
Spot instance AWS limit is set to 512.

It's just we never reach 512, even GitHub Actions waits for new runners, which causes delays in CI workflows execution.
