### ISSUE TITLE
[Question] Why to use NatGateway, how to avoid it?

### ISSUE THREAD

**Issue by kuvaldini** [philips-labs/terraform-aws-github-runner#870]
NatGateway costs too much. Could you please tell if it is required and how to avoid using it?

**Comment by mcaulifn** [comment]
Some sort of egress is required to download other Actions, download tools, and communicate with public GH or GHES. There is no hard requirement to use NATGW.

**Comment by npalm** [comment]
@mcaulifn thanks! Fully agree the module does not enforce a NAT gateway. At the moment you require internet connectivity and run the runners in private subnet the NAT gate way is required.

**Comment by kuvaldini** [comment]
So is there a way to avoid creating and using NAT gateway?

**Comment by npalm** [comment]
You can deploy the setup in you default VPC for example, be-aware that you instances are potentially accessible from the internet (ensure you double check the ingress routes).
