### ISSUE TITLE
Lambda role does not have CreateNetworkInterface permission

### ISSUE THREAD

**Issue by mrmeyers99** [philips-labs/terraform-aws-github-runner#888]
I'm not sure if this is an issue just in my environment, but I am running into an error where terraform is failing to create all the lambdas because the associated roles do not have the permissions for CreateNetworkInterface.  For example, the action syncer role is getting this error:

```
arn:aws:sts::xxxxx:assumed-role/sbx-action-syncer-lambda-role/awslambda_744_20210612114448101  620a2b93-c9d3-4edc-81e2-ea1570523282  ec2.amazonaws.com  CreateNetworkInterface  Client.UnauthorizedOperation  You are not authorized to perform this operation.
```

I did some research and it looks like we need to add a block like this for each of the roles that get created:

```
resource "aws_iam_role_policy_attachment" "AWSLambdaVPCAccessExecutionRole" {
  role       = aws_iam_role.syncer_lambda.arn
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
}
```

When I manually tested creating a lambda function through the UI once I added that policy to the syncer role I was able to create a lambda function, whereas before I got the same error in the UI as I was getting while trying to run the terraform.

I got this errors using philips-labs/github-runner/aws version 0.13.1

**Comment by npalm** [comment]
I assume you run the lambda's in your own VPC? Do you?

**Comment by mrmeyers99** [comment]
Yes
