### ISSUE TITLE
Add prettier (format check) for lambda to CI

### ISSUE THREAD

**Issue by npalm** [philips-labs/terraform-aws-github-runner#899]
Currently code formatting of the lambd'as is not checked. Add the format check to the CI for every lambda. 

- Add prettier
- Run prettier via `yarn run format-check` in CI

**Comment by Patil2099** [comment]
I would love to work on this issue.

**Comment by npalm** [comment]
Feel free to propose a PR, let me know if you need some direction

**Comment by aadrijnberg** [comment]
I will pick this one up
