### ISSUE TITLE
Scale-Up Lambda: Signing Error?

### ISSUE THREAD

**Issue by mike-kaminski** [philips-labs/terraform-aws-github-runner#914]
I'm getting the following error on each invocation of the scale-up lambda. I've gone back and forth over my private key, double/triple/quadruple checked the base64 encoding. There's nothing out of the ordinary there. Yet the Lambda still _really_ doesn't want to use it. Any guidance?

```
2021-06-20T11:26:39.492Z	062074e7-2f1e-5076-95aa-2dae07071a74	ERROR	Error: error:0909006C:PEM routines:get_name:no start line
    at Sign.sign (internal/crypto/sig.js:103:29)
    at Object.sign (/var/task/index.js:37147:45)
    at Object.jwsSign [as sign] (/var/task/index.js:37377:24)
    at Object.module.exports [as sign] (/var/task/index.js:36754:16)
    at getToken (/var/task/index.js:54846:23)
    at Object.githubAppJwt (/var/task/index.js:54868:23)
    at getAppAuthentication (/var/task/index.js:113:57)
    at getInstallationAuthentication (/var/task/index.js:256:35) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

Thanks!

**Comment by npalm** [comment]
I cannot remember I saw this error. I would suggest, just generate a new SSH key for the app and double check the app id.

**Comment by mike-kaminski** [comment]
I wanted to follow-up on this earlier but `life`.

I took your recommendation @npalm, generated a new key, ran `base64 -w0 new-ssh-key.pem`, updated the `github_app_key_base64` variable with the new base64 encoded key, triple-checked all of the other necessary variables were set accurately,  purged the old messages from the queue, `terraform apply`'d the update, kicked off a new job.

Confirmed that the Github app was successful sending the webhook, verified that the webhook lambda received the request, verified that the message made it to the queue, observed the scale-up lambda invocation, and, like before, it failed out with the "no start line". Just to be sure, I decoded the key string I used in the variable, visually confirmed the key looks fine once decrypted, diffed the decoded output against the original pem, no variance. 

What you guys have done here is awesome and your solution is pretty much the hands-down best solution for self-hosted runners in a modern, enterprise, dev shop. I _**really**_ want this to work! So I tried like 50 different times, destroyed and rebuilt from scratch, tried multiple versions of Terraform, deleted and carefully re-created the Github App a dozen or so times, and it's always the same error.

Some things I did notice during my multiple attempts at getting this working:

1. Terraform is _definitely_ encrypting the variables that it's (correctly) identifying as sensitive. In particular, the base64 encoded key is being encoded again by Terraform. However, that encoded value is being passed as-is to the resources, and is what's being passed to the scale-up lambda as the key to decrypt. I can't confirm that this double-encrypted string is being decrypted at all by the lambda, but even if it is, the output of the decode would be the base64 encrypted string from the original value, which would in turn present as an invalid certificate. If this is what's happening then it makes sense that the function won't validate the certificate as the start line is still encoded. 
2. We encrypt everything, so naturally I used the KMS options in the module. However, the IAM policies for the various lambdas do not include any KMS permissions, my initial heads up on this was the webhook lambda being helpful in log messages and explicitly stating that it didn't have permissions for kms:decrypt that, I guess(?), it needed to decrypt _something_ in the webhook from Github (enterprise). Once I added kms:decrypt the webhook lambda worked fine. I did notice the wildcard KMS permissions in the boundary policies (naughty), but I opted not to deploy the boundary config as we're already "fenced in" by a permissions boundary enforced by enterprise.

In my efforts I tried the following versions of Terraform, all with the same outcome: v0.13.7, v0.14.11, v0.15.5, and v1.0.1.

As I previously mentioned, I _**really**_ want to get this working. I'm hoping that one of your team (or another community member), being much more familiar with the code, might have an idea or be able to reproduce this issue. I'm happy to share my revisions to the module (necessary to create IAM roles as we've got Federated Auth configured with a highly customized implementation of the [Air Lift Key Services(ALKS)](https://github.com/tuxpower/ALKS) tool. My revisions were minimal, basically swapping out the `aws_iam_role` resources for [`alks_iamrole`](https://registry.terraform.io/providers/Cox-Automotive/alks/latest/docs/resources/alks_iamrole) resources, updated policy names and paths to comply with our enterprise requirements. Nothing major.

Let me know if there's anything I can do to help you help me. Slack/Teams chats/screen share sessions, anything I can provide right here, I'm wide open to any suggestions/options.

**Comment by anupash147** [comment]
> I cannot remember I saw this error. I would suggest, just generate a new SSH key for the app and double check the app id.

I tried this as well but getting same issue. i got a different error when using `base64 -w0 new-ssh-key.pem` default mac base64 encryption mess thing infact more so rolled back to original openssl base64 encryption but getting the original method. Very impressed by the module but this error is killing all of it

**Comment by anupash147** [comment]
More error 
`2021-06-27T08:18:33.625Z	5d76beef-fa8a-5a7f-9132-e7bdcc0f3a5d	ERROR	Invoke Error 	{
    "errorType": "Error",
    "errorMessage": "Failed handling SQS event",
    "stack": [
        "Error: Failed handling SQS event",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:12:12)",
        "    at postError (/var/runtime/CallbackContext.js:29:54)",
        "    at callback (/var/runtime/CallbackContext.js:41:7)",
        "    at /var/runtime/CallbackContext.js:104:16",
        "    at /var/task/index.js:60509:16",
        "    at Generator.throw (<anonymous>)",
        "    at rejected (/var/task/index.js:60491:65)",
        "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
}
`

**Comment by npalm** [comment]
See if I can find some time to run a freshsetup. By the way there is an option to disable KMS at all. Which is of course not the default).

**Comment by mike-kaminski** [comment]
Hey guys, following up here on this. Taking Niek's advice, I tried it without the KMS encryption and things are working as-advertised. One extra thing was that I used the filebase64() function like so:

```
  github_app = {
    key_base64     = filebase64("${path.module}/app.private-key.pem")
    ...
  }
```

A little Terraform trick to save us from any copy-paste errors. :)

Now that I know it's KMS related I can narrow my scope and probably figure out what I had wrong. Thanks a lot for your help!

**Comment by npalm** [comment]
@mcaulifn is working on a PR to replace KMS completely with SSM encrypted values, including option to use CMK's. The PR is not ready yet, but feel free to have a look #587. Be-aware the PR is not working yet since some policies are not configured.

**Comment by mcaulifn** [comment]
#941 was released with https://github.com/philips-labs/terraform-aws-github-runner/releases/tag/v0.16.0
