### ISSUE TITLE
"The runner has received a shutdown signal."

### ISSUE THREAD

**Issue by kuvaldini** [philips-labs/terraform-aws-github-runner#931]
```
The runner has received a shutdown signal. This can happen when the runner service is stopped, 
or a manually started runner is canceled.
The operation was canceled.
```

Here is the link to the project's github action:  
https://github.com/hyperledger/iroha/runs/2883552949?check_suite_focus=true
It is open-source.

<img width="1080" alt="изображение" src="https://user-images.githubusercontent.com/47349143/122970267-5a642600-d396-11eb-95cb-a72fabd3aa29.png">

**Comment by npalm** [comment]
We have seen the same last week, AWS was termination a lot of spot instances. For now we have no solution other then not using spot instances by setting `market_options` variable. You can monitor on the sport termination event on the event bus to get notified

```json
{
  "source": [
    "aws.ec2"
  ],
  "detail-type": [
    "EC2 Spot Instance Interruption Warning"
  ]
}```

On one hand I would like to keep the system simple, but indeed this is really anyoing. Even listing for the event and create a non spot once you instance got terminated is not solving the issue, you build will not restart. Looking for ideas to create a better solution.

**Comment by maschwenk** [comment]
We're still getting this even in cases where we don't see any spot interruption notice
