### ISSUE TITLE
ERROR InvalidLaunchTemplateName.Malformed when setting more than one instance type

### ISSUE THREAD

**Issue by relu** [philips-labs/terraform-aws-github-runner#932]
When having more than a single instance type set i.e. `instance_types = ["t3a.2xlarge", "t3.2xlarge"]` the following error is reported by the scale-up lambda:
```
ERROR	InvalidLaunchTemplateName.Malformed: A launch template name must be between 3 and 128 characters, and may contain letters, numbers, and the following characters: - ( ) . / _.
    at Request.extractError (/var/task/index.js:41368:35)
    at Request.callListeners (/var/task/index.js:47708:20)
    at Request.emit (/var/task/index.js:47680:10)
    at Request.emit (/var/task/index.js:18440:14)
    at Request.transition (/var/task/index.js:17779:10)
    at AcceptorStateMachine.runTo (/var/task/index.js:26114:12)
    at /var/task/index.js:26126:10
    at Request.<anonymous> (/var/task/index.js:17795:9)
    at Request.<anonymous> (/var/task/index.js:18442:12)
    at Request.callListeners (/var/task/index.js:47718:18) {
  code: 'InvalidLaunchTemplateName.Malformed',
  time: 2021-06-23T09:43:21.844Z,
  requestId: 'de65aa2c-d563-475c-9af6-747e6214438e',
  statusCode: 400,
  retryable: false,
  retryDelay: 37.7343991287818
}
```

I didn't have time to look into it myself but I think it might have something to do with the way the launch template names are extracted from the `LAUNCH_TEMPLATE_NAME` env var.

**Comment by mcaulifn** [comment]
The launch template name is constructed using `environment` and the instance type [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/744d977880eb8b01ddfbbd31f742f5c8c0fc571e/modules/runners/main.tf#L41). Those names are fed to `LAUNCH_TEMPLATE_NAME` [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/744d977880eb8b01ddfbbd31f742f5c8c0fc571e/modules/runners/scale-up.tf#L42). This should result in a comma separated listed with no spaces. The names are extracted [here](https://github.com/philips-labs/terraform-aws-github-runner/blob/744d977880eb8b01ddfbbd31f742f5c8c0fc571e/modules/runners/lambdas/runners/src/scale-runners/scale-up.ts#L98), resulting in a list of strings. For the name to be malformed, it would require the environment name to have an unsupported character. 

What I'm guessing is happening is that the lambda code was not updated when you re-deployed to support multiple instance types. This also happened to us 😄

**Comment by relu** [comment]
The environment name is simply `ci` so that's definitely not the cause.

What you say about lambda code being outdated does make sense, I'll see if I can force this somehow and ensure the lambdas are updated.

**Comment by mcaulifn** [comment]
I can't find the exact doc, but what I discovered is that the code is not updated unless the file name changes, or the object version changes. If your zips are stored in S3, this module does not account for updating just the files in S3. To work around that, I'd suggest creating a bucket object lookup and using the `etag` attribute as the object version.

From https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-code.html:
>Changes to a deployment package in Amazon S3 are not detected automatically during stack updates. To update the function code, change the object key or version in the template.

**Comment by relu** [comment]
Ok, I've figured it out. The problem was that I was using the `download-lambda` module and forgot to update the version(s) on that module as well :facepalm:
Thanks for your support!
