### ISSUE TITLE
Why to ask GitHub every time for new tokens for new runners and not to use existing tokens from imagine pool. 

### ISSUE THREAD

**Issue by kuvaldini** [philips-labs/terraform-aws-github-runner#970]
Hello @npalm.

I wonder why to ask GitHub every time for new tokens for new runners and not to use tokens from pool. 

In few words the scheme could be presented as following:
```
GHAction triggered 
-> GHApp WebHook to AWS lambda 
-> Lambda asks GH to create new token to register runner 
-> EC2 instance started and NEW runner registred.
Then another lambda periodically checks for idling runners and kills them
```
right?

As for me we can keep GH runner tokens in aws storage and run new instances with old tokens.  
Going this way I imagine two benefits:
1. less requests between AWS and GH - so it could be faster
2. in github settings/actions/runners we can see total number of runners and their statuses. do not manage runners dynamically adding or removing them - just start/stop - and observe online/offline/running/idling statuses.

**Comment by npalm** [comment]
Yes you observation is right.

1. Tokens generated by GH are valid for an our. 
2. The generated token is used by the github configuration script of the runner to create an authroization. So it is not simple to re-use github runners. Therefore we made the choice to use create and remove the runners in github as well.

Furthermore we have the designed the architecture in such way that we do not have to grant any permission to the runner instance to call the github api for security reason. In this way only the lambda needs some org level permissions

**Comment by kuvaldini** [comment]
2. I believe GitHub runner authorization is just a files in filesystem.

We can simply store image of VM with authorization. I feel it is a more hacky way but it should save (up to my observations) up to 30 secs on each run which requires to register new GH runner.

And we have yet another profit - clear runners list in GH project/organization settings.

**Comment by npalm** [comment]
The scale down lambda should take care of clearing the list, if not I would consider this as a bug. Currently a scale down lambda is checking very x minutes for runner that are idle, idle ones should be removed. Next the AWS instances is terminated.

**Comment by npalm** [comment]
Due to inactivity I am closing the issue. Thanks for reaching out and feel free to re-open if needed.

**Comment by kuvaldini** [comment]
Thank you for your answer
