### ISSUE TITLE
deprecated `instance_type` is still used in main.tf to determine runner_architecture

### ISSUE THREAD

**Issue by marcofranssen** [philips-labs/terraform-aws-github-runner#987]
Due to the `instance_type` still being used in https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/main.tf#L7 consumers of the module still need to define the `instance_type` which is marked as deprecated.

Defining multiple runners using the new `instance_types` therefore will have inaccurate architectures and potential other things failing like described in https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/README.md#arm64-support-via-gravitongraviton2-instance-types and https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/README.md#arm64-configuration-for-submodules

I think it would be best on short term to un-deprecate the `instance_type` until other parts are fixed.

**Comment by npalm** [comment]
Looks like this is missed in a PR to support failing spot creation, looks like only this line is still depdending on https://github.com/philips-labs/terraform-aws-github-runner/blob/b957e263b6dbc3d299eab3236b479b9113b1fecb/main.tf#L7 on the `instance_type`. So i would prefer we make this. line working for tye variable `instance_type`

**Comment by marcofranssen** [comment]
Correct that is the line I mentioned above. However the impact could be much bigger as that also means you need to support multiple runner architectures, which is currently only one. So that might boil down way deeper into the module. Not sure on the complexity of that, as I'm not that deep into the architecture of the module itself, but I think it might be more difficult than just updating this single line.

**Comment by npalm** [comment]
I don't expect there will be much impact, since this line is only used to automatically derive the architecture type.

**Comment by ScottGuymer** [comment]
This implementation has now changed and you now have to set the [runner_architecture](https://github.com/philips-labs/terraform-aws-github-runner#input_runner_architecture) explictly.
