### ISSUE TITLE
Document `instance_types` must use same processor architecture

### ISSUE THREAD

**Issue by marcofranssen** [philips-labs/terraform-aws-github-runner#991]
See #987 .

It seems when using multiple `instance_types` they **must** have the same processor architecture.

The `instance_types` are used to have fallbacks when spot instances are not available.

e.g.:

```hcl
instance_types = ["m5large", "c5large"]
```

when `m5large` spot instance is not available, we will fall back to a `c5large` instance.

Mixing with instances of different processor architectures is not possible at this time. Documentation should clearly state this.

**Comment by ScottGuymer** [comment]
This implementation has now changed, and you now must set the [runner_architecture](https://github.com/philips-labs/terraform-aws-github-runner#input_runner_architecture) explicitly.

**Comment by ScottGuymer** [comment]
Is the current documentation sufficient for this?

**Comment by marcofranssen** [comment]
👍
