### ISSUE TITLE
Replace `repository_white_list` variable with `repository_allow_list` variable

### ISSUE THREAD

**Issue by marcofranssen** [philips-labs/terraform-aws-github-runner#992]
Would be good to replace terminology for the following variable.

`repository_white_list` » `repository_allow_list`.

Please ensure to not break backwards compatibility in first couple of release to allow consumers of this module to migrate.

`repository_white_list` should be deprecated and be used as fallback for the new `repository_allow_list`. 

In a future release we can then remove the `repository_white_list` variable, this allows migration path.

**Comment by rbrishabh** [comment]
hey! I can help with this
